package tk.darrow.tribalpower.client.wildlife;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.*;
/** Generated by tools/generate_march_wildlife.py; edit the model table there. */
public final class GeneratedWildlifeLayers {
    private GeneratedWildlifeLayers() {}
    public static LayerDefinition create(String id) {
        MeshDefinition mesh = new MeshDefinition();
        PartDefinition root = mesh.getRoot();
        switch (id) {
            case "glimmerfin" -> {
                PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-1.0F, -1.5F, -3.0F, 2.0F, 3.0F, 6.0F), PartPose.offset(0.0F, 22.0F, 0.0F));
                PartDefinition dorsal = body.addOrReplaceChild("dorsal", CubeListBuilder.create().texOffs(0, 9).addBox(0.0F, -3.5F, -1.5F, 0.0F, 2.0F, 4.0F), PartPose.offset(0.0F, 0.0F, 0.0F));
                PartDefinition belly_fin = body.addOrReplaceChild("belly_fin", CubeListBuilder.create().texOffs(10, 9).addBox(0.0F, 1.5F, -1.0F, 0.0F, 1.0F, 2.0F), PartPose.offset(0.0F, 0.0F, 0.0F));
                PartDefinition tail = root.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(16, 9).addBox(0.0F, -2.0F, 0.0F, 0.0F, 4.0F, 4.0F), PartPose.offset(0.0F, 22.0F, 3.0F));
                return LayerDefinition.create(mesh, 32, 32);
            }
            case "drift_bell" -> {
                PartDefinition bell = root.addOrReplaceChild("bell", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0F, -6.0F, -4.0F, 8.0F, 6.0F, 8.0F), PartPose.offset(0.0F, 15.0F, 0.0F));
                PartDefinition cap = bell.addOrReplaceChild("cap", CubeListBuilder.create().texOffs(0, 14).addBox(-2.5F, -8.0F, -2.5F, 5.0F, 2.0F, 5.0F), PartPose.offset(0.0F, 0.0F, 0.0F));
                PartDefinition skirt = bell.addOrReplaceChild("skirt", CubeListBuilder.create().texOffs(0, 21).addBox(-5.0F, 0.0F, -5.0F, 10.0F, 1.0F, 10.0F), PartPose.offset(0.0F, 0.0F, 0.0F));
                PartDefinition core = bell.addOrReplaceChild("core", CubeListBuilder.create().texOffs(32, 0).addBox(-2.0F, -4.0F, -2.0F, 4.0F, 3.0F, 4.0F), PartPose.offset(0.0F, 0.0F, 0.0F));
                PartDefinition tentacle0 = root.addOrReplaceChild("tentacle0", CubeListBuilder.create().texOffs(48, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 10.0F, 1.0F), PartPose.offset(3.0F, 16.0F, 0.0F));
                PartDefinition tentacle1 = root.addOrReplaceChild("tentacle1", CubeListBuilder.create().texOffs(52, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 10.0F, 1.0F), PartPose.offset(1.5F, 16.0F, 2.6F));
                PartDefinition tentacle2 = root.addOrReplaceChild("tentacle2", CubeListBuilder.create().texOffs(56, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 10.0F, 1.0F), PartPose.offset(-1.5F, 16.0F, 2.6F));
                PartDefinition tentacle3 = root.addOrReplaceChild("tentacle3", CubeListBuilder.create().texOffs(60, 0).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 10.0F, 1.0F), PartPose.offset(-3.0F, 16.0F, 0.0F));
                PartDefinition tentacle4 = root.addOrReplaceChild("tentacle4", CubeListBuilder.create().texOffs(48, 12).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 10.0F, 1.0F), PartPose.offset(-1.5F, 16.0F, -2.6F));
                PartDefinition tentacle5 = root.addOrReplaceChild("tentacle5", CubeListBuilder.create().texOffs(52, 12).addBox(-0.5F, 0.0F, -0.5F, 1.0F, 10.0F, 1.0F), PartPose.offset(1.5F, 16.0F, -2.6F));
                return LayerDefinition.create(mesh, 64, 64);
            }
            case "veil_ray" -> {
                PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-4.0F, -1.0F, -5.0F, 8.0F, 2.0F, 10.0F), PartPose.offset(0.0F, 22.0F, 0.0F));
                PartDefinition horn_l = body.addOrReplaceChild("horn_l", CubeListBuilder.create().texOffs(36, 12).addBox(2.5F, -0.5F, -7.0F, 1.0F, 1.0F, 2.0F), PartPose.offset(0.0F, 0.0F, 0.0F));
                PartDefinition horn_r = body.addOrReplaceChild("horn_r", CubeListBuilder.create().texOffs(42, 12).addBox(-3.5F, -0.5F, -7.0F, 1.0F, 1.0F, 2.0F), PartPose.offset(0.0F, 0.0F, 0.0F));
                PartDefinition wing_l = root.addOrReplaceChild("wing_l", CubeListBuilder.create().texOffs(0, 12).addBox(0.0F, -0.5F, -4.0F, 8.0F, 1.0F, 8.0F), PartPose.offset(4.0F, 22.0F, 0.0F));
                PartDefinition wing_r = root.addOrReplaceChild("wing_r", CubeListBuilder.create().texOffs(0, 24).addBox(-8.0F, -0.5F, -4.0F, 8.0F, 1.0F, 8.0F), PartPose.offset(-4.0F, 22.0F, 0.0F));
                PartDefinition tail = root.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(36, 0).addBox(-0.5F, -0.5F, 0.0F, 1.0F, 1.0F, 10.0F), PartPose.offset(0.0F, 22.0F, 5.0F));
                return LayerDefinition.create(mesh, 64, 64);
            }
            case "silt_eel" -> {
                PartDefinition head = root.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 0).addBox(-1.5F, -1.5F, -4.0F, 3.0F, 3.0F, 4.0F), PartPose.offset(0.0F, 22.0F, -6.0F));
                PartDefinition seg1 = root.addOrReplaceChild("seg1", CubeListBuilder.create().texOffs(0, 8).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 4.0F), PartPose.offset(0.0F, 22.0F, -2.0F));
                PartDefinition seg2 = seg1.addOrReplaceChild("seg2", CubeListBuilder.create().texOffs(16, 8).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 4.0F), PartPose.offset(0.0F, 0.0F, 4.0F));
                PartDefinition seg3 = seg2.addOrReplaceChild("seg3", CubeListBuilder.create().texOffs(32, 8).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 4.0F), PartPose.offset(0.0F, 0.0F, 4.0F));
                PartDefinition seg4 = seg3.addOrReplaceChild("seg4", CubeListBuilder.create().texOffs(48, 8).addBox(-1.0F, -1.0F, 0.0F, 2.0F, 2.0F, 4.0F), PartPose.offset(0.0F, 0.0F, 4.0F));
                PartDefinition fin = seg4.addOrReplaceChild("fin", CubeListBuilder.create().texOffs(0, 16).addBox(0.0F, -2.0F, 2.0F, 0.0F, 4.0F, 5.0F), PartPose.offset(0.0F, 0.0F, 0.0F));
                return LayerDefinition.create(mesh, 64, 64);
            }
            case "loom_swift" -> {
                PartDefinition body = root.addOrReplaceChild("body", CubeListBuilder.create().texOffs(0, 0).addBox(-1.5F, -1.0F, -2.5F, 3.0F, 2.0F, 5.0F), PartPose.offset(0.0F, 21.0F, 0.0F));
                PartDefinition head = body.addOrReplaceChild("head", CubeListBuilder.create().texOffs(0, 7).addBox(-1.0F, -1.5F, -2.0F, 2.0F, 2.0F, 2.0F), PartPose.offset(0.0F, -0.5F, -2.5F));
                PartDefinition beak = head.addOrReplaceChild("beak", CubeListBuilder.create().texOffs(8, 7).addBox(-0.5F, -0.5F, -3.0F, 1.0F, 1.0F, 1.0F), PartPose.offset(0.0F, 0.0F, 0.0F));
                PartDefinition wing_l = root.addOrReplaceChild("wing_l", CubeListBuilder.create().texOffs(0, 11).addBox(0.0F, 0.0F, -1.5F, 7.0F, 0.0F, 4.0F), PartPose.offset(1.5F, 20.5F, 0.0F));
                PartDefinition wing_r = root.addOrReplaceChild("wing_r", CubeListBuilder.create().texOffs(0, 16).addBox(-7.0F, 0.0F, -1.5F, 7.0F, 0.0F, 4.0F), PartPose.offset(-1.5F, 20.5F, 0.0F));
                PartDefinition tail = root.addOrReplaceChild("tail", CubeListBuilder.create().texOffs(0, 21).addBox(-1.5F, 0.0F, 0.0F, 3.0F, 0.0F, 4.0F), PartPose.offset(0.0F, 20.5F, 2.5F));
                return LayerDefinition.create(mesh, 32, 32);
            }
            default -> throw new IllegalArgumentException("Unknown wildlife: " + id);
        }
    }
}
