org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.249
loader_version_range=[4,)

mod_id=tribalpower
mod_name=Tribal Power
mod_license=GNU GPL v3
mod_group_id=tk.darrow.tribalpower
mod_version=3.2.0
mod_authors=Ahmi & Risika Darrow
mod_description=Shamanic technomancy - spirit-synced machinery, totem lattices, pulse power, and the Nine Tribes who kept the Loom.
