package tk.darrow.tribalpower.client;
import net.minecraft.client.model.geom.*;
import net.minecraft.client.model.geom.builders.*;
/**
 * The bodies of the March roster, generated by tools/creature_gen/emit_rigs.py from the same plans
 * that paint their skins, so geometry and texture can never drift apart.
 *
 * <p>{@link GeneratedCreatureLayers} holds the hand-built Blender rigs and falls through to this for
 * anything it does not know. Boxes are welded into the parts LatticeCreatureModel animates.
 */
public final class GeneratedMarchLayers {
    private GeneratedMarchLayers() {}

    /** The geometry for one creature, or null if this is not one of ours. */
    public static MeshDefinition mesh(String id) {
MeshDefinition mesh=new MeshDefinition(); var root=mesh.getRoot();
switch(id) {
case "tuftback" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-5.0F,-10.0F,-2.0F,10.0F,10.0F,4.0F).texOffs(29,0).addBox(-5.5F,-11.0F,2.0F,11.0F,11.0F,4.0F).texOffs(60,0).addBox(-6.0F,-12.0F,6.0F,12.0F,12.0F,4.0F).texOffs(93,0).addBox(-5.5F,-11.0F,10.0F,11.0F,11.0F,4.0F),PartPose.offset(0.0F,21.0F,-8.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(124,0).addBox(-3.0F,-4.0F,-4.0F,6.0F,4.0F,4.0F).texOffs(217,0).addBox(-2.5F,-9.0F,-3.5F,1.0F,5.0F,1.0F).texOffs(222,0).addBox(1.5F,-7.0F,-3.5F,1.0F,5.0F,1.0F).texOffs(227,0).addBox(-2.0F,-1.0F,-6.0F,4.0F,1.0F,2.0F),PartPose.offset(0.0F,20.0F,-12.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(145,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(-5.0F,21.0F,-8.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(154,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(5.0F,21.0F,-8.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(163,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(-5.0F,21.0F,-4.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(172,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(5.0F,21.0F,-4.0F));
root.addOrReplaceChild("leg4",CubeListBuilder.create().texOffs(181,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(-5.0F,21.0F,0.0F));
root.addOrReplaceChild("leg5",CubeListBuilder.create().texOffs(190,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(5.0F,21.0F,0.0F));
root.addOrReplaceChild("leg6",CubeListBuilder.create().texOffs(199,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(-5.0F,21.0F,4.0F));
root.addOrReplaceChild("leg7",CubeListBuilder.create().texOffs(208,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(5.0F,21.0F,4.0F));
}
case "longshank" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,-3.0F,-4.0F,5.0F,5.0F,8.0F).texOffs(27,0).addBox(-1.5F,-12.0F,-4.5F,3.0F,10.0F,3.0F).texOffs(59,0).addBox(-2.0F,-7.0F,-3.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,9.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(40,0).addBox(-2.0F,-3.0F,-4.0F,4.0F,4.0F,5.0F).texOffs(164,0).addBox(-1.8F,-8.0F,-3.5F,1.0F,5.0F,1.0F).texOffs(169,0).addBox(0.8F,-7.0F,-3.5F,1.0F,3.0F,1.0F).texOffs(174,0).addBox(-1.3F,0.0F,-6.5F,2.0F,1.0F,2.0F),PartPose.offset(0.0F,-2.0F,-5.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(76,0).addBox(-1.0F,0.0F,-1.0F,2.0F,12.0F,2.0F).texOffs(85,0).addBox(-1.5F,5.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(-2.5F,12.0F,-3.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(98,0).addBox(-1.0F,0.0F,-1.0F,2.0F,12.0F,2.0F).texOffs(107,0).addBox(-1.5F,5.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(2.5F,12.0F,-3.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(120,0).addBox(-1.0F,0.0F,-1.0F,2.0F,12.0F,2.0F).texOffs(129,0).addBox(-1.5F,5.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(-2.5F,12.0F,3.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(142,0).addBox(-1.0F,0.0F,-1.0F,2.0F,12.0F,2.0F).texOffs(151,0).addBox(-1.5F,5.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(2.5F,12.0F,3.0F));
}
case "palewing" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.0F,-3.0F,-4.0F,4.0F,6.0F,8.0F).texOffs(84,0).addBox(-5.8F,-2.0F,-4.1F,6.0F,1.0F,4.0F).texOffs(105,0).addBox(-0.2F,-2.0F,-4.1F,6.0F,1.0F,4.0F),PartPose.offset(0.0F,14.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(25,0).addBox(-2.0F,-2.0F,-3.0F,4.0F,4.0F,4.0F).texOffs(136,0).addBox(-1.5F,-3.5F,-8.0F,1.0F,1.0F,5.0F).texOffs(149,0).addBox(0.5F,-3.5F,-7.0F,1.0F,1.0F,4.0F).texOffs(160,0).addBox(-1.3F,1.0F,-5.0F,2.0F,1.0F,2.0F),PartPose.offset(0.0F,11.0F,-4.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(126,0).addBox(-0.5F,0.0F,-0.5F,1.0F,5.0F,1.0F),PartPose.offset(-1.5F,17.0F,0.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(131,0).addBox(-0.5F,0.0F,-0.5F,1.0F,5.0F,1.0F),PartPose.offset(1.5F,17.0F,0.0F));
root.addOrReplaceChild("wing0",CubeListBuilder.create().texOffs(42,0).addBox(-3.0F,-1.0F,-2.0F,6.0F,1.0F,4.0F),PartPose.offset(2.8F,13.0F,2.1F));
root.addOrReplaceChild("wing1",CubeListBuilder.create().texOffs(63,0).addBox(-3.0F,-1.0F,-2.0F,6.0F,1.0F,4.0F),PartPose.offset(-2.8F,13.0F,2.1F));
}
case "burrow_gnasher" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-4.0F,-2.0F,-4.5F,8.0F,4.0F,9.0F).texOffs(167,0).addBox(-2.7F,-4.5F,-3.5F,5.0F,2.0F,2.0F).texOffs(182,0).addBox(-2.7F,-4.5F,-0.5F,5.0F,2.0F,2.0F).texOffs(197,0).addBox(-2.7F,-4.5F,2.5F,5.0F,2.0F,2.0F).texOffs(212,0).addBox(-2.7F,-4.5F,5.5F,5.0F,2.0F,2.0F),PartPose.offset(0.0F,19.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(35,0).addBox(-3.0F,-2.0F,-3.0F,6.0F,3.0F,4.0F).texOffs(56,0).addBox(-3.0F,-1.0F,-7.0F,2.0F,2.0F,4.0F).texOffs(69,0).addBox(1.0F,-1.0F,-7.0F,2.0F,2.0F,4.0F).texOffs(136,0).addBox(-1.5F,-3.5F,-6.0F,1.0F,1.0F,3.0F).texOffs(145,0).addBox(0.5F,-3.5F,-6.0F,1.0F,1.0F,3.0F).texOffs(154,0).addBox(-2.0F,0.0F,-5.0F,4.0F,1.0F,2.0F),PartPose.offset(0.0F,19.0F,-6.5F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(82,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(-4.0F,21.0F,-3.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(91,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(4.0F,21.0F,-3.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(100,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(-4.0F,21.0F,0.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(109,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(4.0F,21.0F,0.0F));
root.addOrReplaceChild("leg4",CubeListBuilder.create().texOffs(118,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(-4.0F,21.0F,3.0F));
root.addOrReplaceChild("leg5",CubeListBuilder.create().texOffs(127,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(4.0F,21.0F,3.0F));
}
case "cragcoat" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-4.5F,-3.0F,-5.0F,9.0F,4.0F,10.0F).texOffs(39,0).addBox(-5.5F,-8.0F,-6.0F,11.0F,4.0F,12.0F).texOffs(86,0).addBox(-2.0F,-3.0F,-10.0F,4.0F,3.0F,4.0F).texOffs(139,0).addBox(-4.5F,-11.0F,-3.8F,1.0F,3.0F,1.0F).texOffs(144,0).addBox(3.5F,-11.0F,-3.8F,1.0F,3.0F,1.0F).texOffs(149,0).addBox(-4.5F,-11.0F,-1.3F,1.0F,3.0F,1.0F).texOffs(154,0).addBox(3.5F,-11.0F,-1.3F,1.0F,3.0F,1.0F).texOffs(159,0).addBox(-4.5F,-11.0F,1.2F,1.0F,3.0F,1.0F).texOffs(164,0).addBox(3.5F,-11.0F,1.2F,1.0F,3.0F,1.0F).texOffs(169,0).addBox(-4.5F,-11.0F,3.7F,1.0F,3.0F,1.0F).texOffs(174,0).addBox(3.5F,-11.0F,3.7F,1.0F,3.0F,1.0F).texOffs(179,0).addBox(-4.5F,-11.0F,6.2F,1.0F,3.0F,1.0F).texOffs(184,0).addBox(3.5F,-11.0F,6.2F,1.0F,3.0F,1.0F).texOffs(21,17).addBox(-3.0F,-5.5F,-4.0F,5.0F,2.0F,2.0F).texOffs(36,17).addBox(-3.0F,-5.5F,-1.0F,5.0F,2.0F,2.0F).texOffs(51,17).addBox(-3.0F,-5.5F,2.0F,5.0F,2.0F,2.0F),PartPose.offset(0.0F,18.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(103,0).addBox(-2.5F,-2.5F,-4.0F,5.0F,4.0F,5.0F).texOffs(0,17).addBox(-2.2F,-7.5F,-3.5F,1.0F,3.0F,1.0F).texOffs(5,17).addBox(1.2F,-7.5F,-3.5F,1.0F,4.0F,1.0F).texOffs(10,17).addBox(-1.7F,0.5F,-6.5F,3.0F,1.0F,2.0F),PartPose.offset(0.0F,16.0F,-10.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(189,0).addBox(-2.0F,0.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(-3.5F,20.0F,-3.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(206,0).addBox(-2.0F,0.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(3.5F,20.0F,-3.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(223,0).addBox(-2.0F,0.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(-3.5F,20.0F,3.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(240,0).addBox(-2.0F,0.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(3.5F,20.0F,3.0F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(124,0).addBox(-1.5F,-1.0F,0.0F,3.0F,2.0F,4.0F),PartPose.offset(0.0F,18.0F,6.0F));
}
case "bouldersnout" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-3.5F,-4.0F,-5.5F,7.0F,7.0F,11.0F).texOffs(37,0).addBox(-2.5F,-6.0F,-4.8F,5.0F,3.0F,5.0F),PartPose.offset(0.0F,16.0F,1.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(58,0).addBox(-3.0F,-3.0F,-5.0F,6.0F,5.0F,6.0F).texOffs(83,0).addBox(-2.5F,2.0F,-6.0F,1.0F,3.0F,1.0F).texOffs(88,0).addBox(1.5F,2.0F,-6.0F,1.0F,3.0F,1.0F).texOffs(161,0).addBox(-2.0F,1.0F,-8.0F,4.0F,1.0F,3.0F),PartPose.offset(0.0F,17.0F,-7.5F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(93,0).addBox(-2.0F,0.0F,-2.0F,4.0F,5.0F,4.0F),PartPose.offset(-2.5F,19.0F,-3.5F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(110,0).addBox(-2.0F,0.0F,-2.0F,4.0F,5.0F,4.0F),PartPose.offset(2.5F,19.0F,-3.5F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(127,0).addBox(-2.0F,0.0F,-2.0F,4.0F,5.0F,4.0F),PartPose.offset(-2.5F,19.0F,3.5F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(144,0).addBox(-2.0F,0.0F,-2.0F,4.0F,5.0F,4.0F),PartPose.offset(2.5F,19.0F,3.5F));
}
case "updrifter" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-3.5F,-5.0F,-3.5F,7.0F,5.0F,7.0F).texOffs(29,0).addBox(-5.0F,0.0F,-5.0F,10.0F,5.0F,10.0F).texOffs(70,0).addBox(-3.5F,5.0F,-3.5F,7.0F,5.0F,7.0F).texOffs(99,0).addBox(-2.0F,10.0F,-2.0F,4.0F,5.0F,4.0F).texOffs(116,0).addBox(-9.0F,7.5F,-2.0F,4.0F,1.0F,5.0F).texOffs(135,0).addBox(5.0F,7.5F,-2.0F,4.0F,1.0F,5.0F),PartPose.offset(0.0F,5.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(181,0).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F).texOffs(198,0).addBox(-1.3F,1.0F,-4.0F,2.0F,1.0F,2.0F),PartPose.offset(0.0F,3.0F,0.0F));
root.addOrReplaceChild("tendril0",CubeListBuilder.create().texOffs(154,0).addBox(-1.0F,0.0F,-1.0F,2.0F,13.0F,2.0F),PartPose.offset(-2.5F,19.0F,0.0F));
root.addOrReplaceChild("tendril1",CubeListBuilder.create().texOffs(163,0).addBox(-1.0F,0.0F,-1.0F,2.0F,11.0F,2.0F),PartPose.offset(0.0F,19.0F,0.0F));
root.addOrReplaceChild("tendril2",CubeListBuilder.create().texOffs(172,0).addBox(-1.0F,0.0F,-1.0F,2.0F,12.0F,2.0F),PartPose.offset(2.5F,19.0F,0.0F));
}
case "scree_lurcher" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-3.5F,0.0F,-2.0F,7.0F,11.0F,4.0F).texOffs(129,0).addBox(-4.5F,-2.0F,-2.0F,4.0F,3.0F,4.0F).texOffs(146,0).addBox(0.5F,-2.0F,-2.0F,4.0F,3.0F,4.0F),PartPose.offset(0.0F,4.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(23,0).addBox(-1.5F,0.0F,-1.5F,3.0F,10.0F,3.0F),PartPose.offset(-5.0F,5.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(36,0).addBox(-1.5F,0.0F,-1.5F,3.0F,10.0F,3.0F),PartPose.offset(5.0F,5.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(75,0).addBox(-3.5F,-5.0F,-5.0F,7.0F,5.0F,7.0F).texOffs(163,0).addBox(-2.3F,-1.0F,-8.5F,4.0F,1.0F,3.0F),PartPose.offset(0.0F,6.0F,-4.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(49,0).addBox(-1.5F,0.0F,-1.5F,3.0F,9.0F,3.0F),PartPose.offset(-2.0F,15.0F,0.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(62,0).addBox(-1.5F,0.0F,-1.5F,3.0F,9.0F,3.0F),PartPose.offset(2.0F,15.0F,0.0F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(104,0).addBox(-1.5F,-1.0F,0.0F,3.0F,3.0F,9.0F),PartPose.offset(0.0F,12.0F,3.0F));
}
case "prism_grazer" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-3.0F,-3.0F,-4.0F,6.0F,6.0F,8.0F).texOffs(55,0).addBox(-0.5F,-8.0F,1.8F,1.0F,5.0F,1.0F).texOffs(60,0).addBox(-0.5F,-6.0F,4.3F,1.0F,3.0F,1.0F).texOffs(157,0).addBox(-2.0F,-5.5F,-3.0F,3.0F,2.0F,2.0F).texOffs(168,0).addBox(-2.0F,-5.5F,0.0F,3.0F,2.0F,2.0F).texOffs(179,0).addBox(-2.0F,-5.5F,3.0F,3.0F,2.0F,2.0F),PartPose.offset(0.0F,17.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(29,0).addBox(-2.5F,-2.5F,-4.0F,5.0F,5.0F,5.0F).texOffs(50,0).addBox(-0.5F,-5.0F,5.3F,1.0F,3.0F,1.0F).texOffs(136,0).addBox(-2.2F,-6.5F,-3.5F,1.0F,4.0F,1.0F).texOffs(141,0).addBox(1.2F,-4.5F,-3.5F,1.0F,2.0F,1.0F).texOffs(146,0).addBox(-1.7F,1.5F,-6.5F,3.0F,1.0F,2.0F),PartPose.offset(0.0F,16.0F,-6.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(84,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F),PartPose.offset(-3.0F,18.0F,-2.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(97,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F),PartPose.offset(3.0F,18.0F,-2.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(110,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F),PartPose.offset(-3.0F,18.0F,2.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(123,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F),PartPose.offset(3.0F,18.0F,2.0F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(65,0).addBox(-1.0F,-1.0F,0.0F,2.0F,2.0F,7.0F),PartPose.offset(0.0F,18.0F,4.0F));
}
case "shardmoth" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-1.5F,-3.0F,-4.0F,3.0F,6.0F,8.0F),PartPose.offset(0.0F,14.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(23,0).addBox(-2.0F,-2.0F,-3.0F,4.0F,4.0F,4.0F).texOffs(193,0).addBox(-1.5F,-3.5F,-6.0F,1.0F,1.0F,3.0F).texOffs(202,0).addBox(0.5F,-3.5F,-7.0F,1.0F,1.0F,3.0F).texOffs(211,0).addBox(-1.3F,1.0F,-5.0F,2.0F,1.0F,2.0F),PartPose.offset(0.0F,11.0F,-4.0F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(178,0).addBox(-1.0F,-1.0F,0.0F,2.0F,2.0F,5.0F),PartPose.offset(0.0F,15.0F,4.0F));
root.addOrReplaceChild("wing0",CubeListBuilder.create().texOffs(40,0).addBox(-9.0F,-1.0F,-3.0F,9.0F,1.0F,5.0F).texOffs(69,0).addBox(-7.0F,-1.0F,0.5F,7.0F,1.0F,4.0F).texOffs(92,0).addBox(-5.0F,-1.0F,4.0F,5.0F,1.0F,3.0F),PartPose.offset(-1.5F,13.0F,0.0F));
root.addOrReplaceChild("wing1",CubeListBuilder.create().texOffs(109,0).addBox(0.0F,-1.0F,-3.0F,9.0F,1.0F,5.0F).texOffs(138,0).addBox(0.0F,-1.0F,0.5F,7.0F,1.0F,4.0F).texOffs(161,0).addBox(0.0F,-1.0F,4.0F,5.0F,1.0F,3.0F),PartPose.offset(1.5F,13.0F,0.0F));
}
case "glowgrub" -> {
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(0,0).addBox(-3.0F,-3.0F,-4.0F,6.0F,4.0F,5.0F).texOffs(125,0).addBox(-1.5F,-4.5F,-9.0F,1.0F,1.0F,3.0F).texOffs(134,0).addBox(0.5F,-4.5F,-9.0F,1.0F,1.0F,4.0F).texOffs(145,0).addBox(-2.0F,0.0F,-6.5F,4.0F,1.0F,2.0F),PartPose.offset(0.0F,15.0F,-18.0F));
root.addOrReplaceChild("seg0",CubeListBuilder.create().texOffs(23,0).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,15.0F,-13.0F));
root.addOrReplaceChild("seg1",CubeListBuilder.create().texOffs(40,0).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,16.0F,-9.0F));
root.addOrReplaceChild("seg2",CubeListBuilder.create().texOffs(57,0).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,16.0F,-5.0F));
root.addOrReplaceChild("seg3",CubeListBuilder.create().texOffs(74,0).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,16.0F,-1.0F));
root.addOrReplaceChild("seg4",CubeListBuilder.create().texOffs(91,0).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,16.0F,3.0F));
root.addOrReplaceChild("seg5",CubeListBuilder.create().texOffs(108,0).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,17.0F,7.0F));
}
case "facet_stalker" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.0F,-2.0F,-3.0F,4.0F,4.0F,6.0F),PartPose.offset(0.0F,13.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(21,0).addBox(-2.0F,-2.0F,-3.0F,4.0F,4.0F,4.0F).texOffs(170,0).addBox(-1.3F,1.0F,-5.0F,2.0F,1.0F,2.0F),PartPose.offset(0.0F,13.0F,-5.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(38,0).addBox(-1.0F,0.0F,-1.0F,2.0F,9.0F,2.0F).texOffs(47,0).addBox(-2.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(-3.0F,15.0F,-3.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(60,0).addBox(-1.0F,0.0F,-1.0F,2.0F,9.0F,2.0F).texOffs(69,0).addBox(-0.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(3.0F,15.0F,-3.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(82,0).addBox(-1.0F,0.0F,-1.0F,2.0F,9.0F,2.0F).texOffs(91,0).addBox(-2.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(-3.0F,15.0F,0.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(104,0).addBox(-1.0F,0.0F,-1.0F,2.0F,9.0F,2.0F).texOffs(113,0).addBox(-0.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(3.0F,15.0F,0.0F));
root.addOrReplaceChild("leg4",CubeListBuilder.create().texOffs(126,0).addBox(-1.0F,0.0F,-1.0F,2.0F,9.0F,2.0F).texOffs(135,0).addBox(-2.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(-3.0F,15.0F,3.0F));
root.addOrReplaceChild("leg5",CubeListBuilder.create().texOffs(148,0).addBox(-1.0F,0.0F,-1.0F,2.0F,9.0F,2.0F).texOffs(157,0).addBox(-0.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(3.0F,15.0F,3.0F));
}
case "driftpelt" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-6.0F,-3.0F,-6.0F,12.0F,3.0F,12.0F).texOffs(49,0).addBox(-5.0F,-6.0F,-5.0F,10.0F,3.0F,10.0F).texOffs(90,0).addBox(-3.5F,-8.0F,-3.5F,7.0F,2.0F,7.0F),PartPose.offset(0.0F,21.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(119,0).addBox(-2.5F,-2.5F,-4.0F,5.0F,5.0F,5.0F).texOffs(203,0).addBox(-2.2F,-4.5F,-3.5F,1.0F,4.0F,1.0F).texOffs(208,0).addBox(1.2F,-4.5F,-3.5F,1.0F,4.0F,1.0F).texOffs(213,0).addBox(-1.7F,1.5F,-6.5F,3.0F,1.0F,2.0F),PartPose.offset(0.0F,17.0F,-7.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(151,0).addBox(-1.5F,0.0F,-1.5F,3.0F,3.0F,3.0F),PartPose.offset(-4.0F,21.0F,-4.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(164,0).addBox(-1.5F,0.0F,-1.5F,3.0F,3.0F,3.0F),PartPose.offset(4.0F,21.0F,-4.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(177,0).addBox(-1.5F,0.0F,-1.5F,3.0F,3.0F,3.0F),PartPose.offset(-4.0F,21.0F,4.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(190,0).addBox(-1.5F,0.0F,-1.5F,3.0F,3.0F,3.0F),PartPose.offset(4.0F,21.0F,4.0F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(140,0).addBox(-1.0F,-1.0F,0.0F,2.0F,2.0F,3.0F),PartPose.offset(0.0F,19.0F,6.0F));
}
case "frost_strider" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,-3.0F,-3.5F,5.0F,5.0F,7.0F).texOffs(25,0).addBox(-1.5F,-9.0F,-4.0F,3.0F,7.0F,3.0F),PartPose.offset(0.0F,8.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(38,0).addBox(-2.0F,-3.0F,-4.0F,4.0F,4.0F,5.0F).texOffs(93,0).addBox(-1.8F,-6.0F,-3.5F,1.0F,5.0F,1.0F).texOffs(98,0).addBox(0.8F,-7.0F,-3.5F,1.0F,5.0F,1.0F).texOffs(103,0).addBox(-1.3F,0.0F,-6.5F,2.0F,1.0F,2.0F),PartPose.offset(0.0F,0.0F,-4.5F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(57,0).addBox(-1.0F,0.0F,-1.0F,2.0F,13.0F,2.0F),PartPose.offset(-2.5F,11.0F,-2.5F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(66,0).addBox(-1.0F,0.0F,-1.0F,2.0F,13.0F,2.0F),PartPose.offset(2.5F,11.0F,-2.5F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(75,0).addBox(-1.0F,0.0F,-1.0F,2.0F,13.0F,2.0F),PartPose.offset(-2.5F,11.0F,2.5F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(84,0).addBox(-1.0F,0.0F,-1.0F,2.0F,13.0F,2.0F),PartPose.offset(2.5F,11.0F,2.5F));
}
case "snowveil" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-5.0F,-3.0F,-5.0F,10.0F,3.0F,10.0F).texOffs(41,0).addBox(-5.0F,3.0F,-2.0F,4.0F,5.0F,4.0F).texOffs(58,0).addBox(1.0F,3.0F,-2.0F,4.0F,5.0F,4.0F).texOffs(75,0).addBox(-2.0F,3.0F,-5.0F,4.0F,5.0F,4.0F).texOffs(92,0).addBox(-2.0F,3.0F,1.0F,4.0F,5.0F,4.0F),PartPose.offset(0.0F,9.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(149,0).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F).texOffs(166,0).addBox(-1.3F,1.0F,-4.0F,2.0F,1.0F,2.0F),PartPose.offset(0.0F,6.0F,0.0F));
root.addOrReplaceChild("tendril0",CubeListBuilder.create().texOffs(109,0).addBox(-0.5F,0.0F,-0.5F,1.0F,5.0F,1.0F),PartPose.offset(4.0F,17.0F,0.0F));
root.addOrReplaceChild("tendril1",CubeListBuilder.create().texOffs(114,0).addBox(-0.5F,0.0F,-0.5F,1.0F,6.0F,1.0F),PartPose.offset(2.8F,17.0F,2.8F));
root.addOrReplaceChild("tendril2",CubeListBuilder.create().texOffs(119,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(0.0F,17.0F,4.0F));
root.addOrReplaceChild("tendril3",CubeListBuilder.create().texOffs(124,0).addBox(-0.5F,0.0F,-0.5F,1.0F,7.0F,1.0F),PartPose.offset(-2.8F,17.0F,2.8F));
root.addOrReplaceChild("tendril4",CubeListBuilder.create().texOffs(129,0).addBox(-0.5F,0.0F,-0.5F,1.0F,6.0F,1.0F),PartPose.offset(-4.0F,17.0F,0.0F));
root.addOrReplaceChild("tendril5",CubeListBuilder.create().texOffs(134,0).addBox(-0.5F,0.0F,-0.5F,1.0F,5.0F,1.0F),PartPose.offset(-2.8F,17.0F,-2.8F));
root.addOrReplaceChild("tendril6",CubeListBuilder.create().texOffs(139,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(-0.0F,17.0F,-4.0F));
root.addOrReplaceChild("tendril7",CubeListBuilder.create().texOffs(144,0).addBox(-0.5F,0.0F,-0.5F,1.0F,6.0F,1.0F),PartPose.offset(2.8F,17.0F,-2.8F));
}
case "rime_crawler" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-4.0F,-2.0F,-5.5F,8.0F,4.0F,11.0F).texOffs(60,0).addBox(-3.0F,-5.0F,-4.5F,6.0F,3.0F,9.0F).texOffs(195,0).addBox(-2.7F,-4.5F,-4.5F,5.0F,2.0F,2.0F).texOffs(210,0).addBox(-2.7F,-4.5F,-1.5F,5.0F,2.0F,2.0F).texOffs(225,0).addBox(-2.7F,-4.5F,1.5F,5.0F,2.0F,2.0F),PartPose.offset(0.0F,19.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(39,0).addBox(-3.0F,-2.0F,-3.0F,6.0F,3.0F,4.0F).texOffs(164,0).addBox(-1.5F,-3.5F,-7.0F,1.0F,1.0F,3.0F).texOffs(173,0).addBox(0.5F,-3.5F,-7.0F,1.0F,1.0F,3.0F).texOffs(182,0).addBox(-2.0F,0.0F,-5.0F,4.0F,1.0F,2.0F),PartPose.offset(0.0F,19.0F,-7.5F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(110,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(-4.0F,21.0F,-3.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(119,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(4.0F,21.0F,-3.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(128,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(-4.0F,21.0F,0.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(137,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(4.0F,21.0F,0.0F));
root.addOrReplaceChild("leg4",CubeListBuilder.create().texOffs(146,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(-4.0F,21.0F,3.0F));
root.addOrReplaceChild("leg5",CubeListBuilder.create().texOffs(155,0).addBox(-1.0F,0.0F,-1.0F,2.0F,3.0F,2.0F),PartPose.offset(4.0F,21.0F,3.0F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(91,0).addBox(-1.0F,-1.0F,0.0F,2.0F,2.0F,7.0F),PartPose.offset(0.0F,19.0F,5.5F));
}
case "cinderhide" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-4.0F,-3.0F,-5.5F,8.0F,4.0F,11.0F).texOffs(39,0).addBox(-5.0F,-8.0F,-6.5F,10.0F,4.0F,13.0F).texOffs(86,0).addBox(-2.0F,-3.0F,-10.5F,4.0F,3.0F,4.0F).texOffs(139,0).addBox(-1.0F,-10.0F,-3.7F,2.0F,2.0F,7.0F).texOffs(0,18).addBox(-2.7F,-5.5F,-4.5F,5.0F,2.0F,2.0F).texOffs(15,18).addBox(-2.7F,-5.5F,-1.5F,5.0F,2.0F,2.0F),PartPose.offset(0.0F,18.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(103,0).addBox(-2.5F,-2.5F,-4.0F,5.0F,4.0F,5.0F).texOffs(226,0).addBox(-2.2F,-5.5F,-3.5F,1.0F,4.0F,1.0F).texOffs(231,0).addBox(1.2F,-6.5F,-3.5F,1.0F,3.0F,1.0F).texOffs(236,0).addBox(-1.7F,0.5F,-6.5F,3.0F,1.0F,2.0F),PartPose.offset(0.0F,16.0F,-10.5F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(158,0).addBox(-2.0F,0.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(-3.0F,20.0F,-3.5F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(175,0).addBox(-2.0F,0.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(3.0F,20.0F,-3.5F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(192,0).addBox(-2.0F,0.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(-3.0F,20.0F,3.5F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(209,0).addBox(-2.0F,0.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(3.0F,20.0F,3.5F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(124,0).addBox(-1.5F,-1.0F,0.0F,3.0F,2.0F,4.0F),PartPose.offset(0.0F,18.0F,6.5F));
}
case "ashmoth" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.0F,-3.0F,-4.0F,4.0F,6.0F,8.0F),PartPose.offset(0.0F,14.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(25,0).addBox(-2.0F,-2.0F,-3.0F,4.0F,4.0F,4.0F).texOffs(179,0).addBox(-1.5F,-3.5F,-8.0F,1.0F,1.0F,3.0F).texOffs(188,0).addBox(0.5F,-3.5F,-7.0F,1.0F,1.0F,4.0F).texOffs(199,0).addBox(-1.3F,1.0F,-5.0F,2.0F,1.0F,2.0F),PartPose.offset(0.0F,11.0F,-4.0F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(150,0).addBox(-1.0F,-1.0F,0.0F,2.0F,2.0F,12.0F),PartPose.offset(0.0F,15.0F,4.0F));
root.addOrReplaceChild("wing0",CubeListBuilder.create().texOffs(42,0).addBox(-10.0F,-1.0F,-4.0F,10.0F,1.0F,4.0F).texOffs(71,0).addBox(-8.0F,2.0F,2.0F,8.0F,1.0F,4.0F),PartPose.offset(-2.0F,12.0F,-2.0F));
root.addOrReplaceChild("wing1",CubeListBuilder.create().texOffs(96,0).addBox(0.0F,-1.0F,-4.0F,10.0F,1.0F,4.0F).texOffs(125,0).addBox(0.0F,2.0F,2.0F,8.0F,1.0F,4.0F),PartPose.offset(2.0F,12.0F,-2.0F));
}
case "slaglump" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-5.0F,-4.0F,-5.0F,10.0F,4.0F,10.0F).texOffs(41,0).addBox(-4.5F,-8.0F,-4.5F,9.0F,4.0F,9.0F).texOffs(78,0).addBox(-3.5F,-12.0F,-3.5F,7.0F,4.0F,7.0F),PartPose.offset(0.0F,21.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(107,0).addBox(-2.5F,-2.5F,-4.0F,5.0F,5.0F,5.0F).texOffs(180,0).addBox(-2.2F,-6.5F,-3.5F,1.0F,4.0F,1.0F).texOffs(185,0).addBox(1.2F,-5.5F,-3.5F,1.0F,4.0F,1.0F).texOffs(190,0).addBox(-1.7F,1.5F,-6.5F,3.0F,1.0F,2.0F),PartPose.offset(0.0F,12.0F,-7.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(128,0).addBox(-1.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(-4.0F,22.0F,-4.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(141,0).addBox(-1.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(4.0F,22.0F,-4.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(154,0).addBox(-1.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(-4.0F,22.0F,4.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(167,0).addBox(-1.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(4.0F,22.0F,4.0F));
}
case "emberjaw" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-3.5F,0.0F,-2.0F,7.0F,11.0F,4.0F),PartPose.offset(0.0F,6.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(23,0).addBox(-1.5F,0.0F,-1.5F,3.0F,7.0F,3.0F),PartPose.offset(-5.0F,7.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(36,0).addBox(-1.5F,0.0F,-1.5F,3.0F,7.0F,3.0F),PartPose.offset(5.0F,7.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(75,0).addBox(-3.0F,-6.0F,-3.0F,6.0F,6.0F,6.0F).texOffs(100,0).addBox(-2.0F,-1.0F,-6.0F,4.0F,1.0F,3.0F),PartPose.offset(0.0F,6.0F,0.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(49,0).addBox(-1.5F,0.0F,-1.5F,3.0F,7.0F,3.0F),PartPose.offset(-2.0F,17.0F,0.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(62,0).addBox(-1.5F,0.0F,-1.5F,3.0F,7.0F,3.0F),PartPose.offset(2.0F,17.0F,0.0F));
}
case "marsh_hopper" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,-2.5F,-3.5F,5.0F,5.0F,7.0F),PartPose.offset(0.0F,15.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(25,0).addBox(-3.0F,-3.0F,-4.0F,6.0F,5.0F,5.0F).texOffs(48,0).addBox(-3.0F,-8.0F,-1.0F,2.0F,6.0F,1.0F).texOffs(55,0).addBox(1.0F,-8.0F,-1.0F,2.0F,6.0F,1.0F).texOffs(129,0).addBox(-2.5F,-6.0F,-3.5F,1.0F,2.0F,1.0F).texOffs(134,0).addBox(1.5F,-5.0F,-3.5F,1.0F,4.0F,1.0F).texOffs(139,0).addBox(-2.0F,1.0F,-6.5F,4.0F,1.0F,2.0F),PartPose.offset(0.0F,11.5F,-5.5F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(62,0).addBox(-2.0F,0.0F,-2.0F,4.0F,7.0F,5.0F),PartPose.offset(-2.5F,17.0F,1.5F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(81,0).addBox(-2.0F,0.0F,-2.0F,4.0F,7.0F,5.0F),PartPose.offset(2.5F,17.0F,1.5F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(100,0).addBox(-1.0F,0.0F,-1.0F,2.0F,4.0F,2.0F),PartPose.offset(-1.5F,20.0F,-2.5F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(109,0).addBox(-1.0F,0.0F,-1.0F,2.0F,4.0F,2.0F),PartPose.offset(1.5F,20.0F,-2.5F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(118,0).addBox(-1.0F,-1.0F,0.0F,2.0F,2.0F,3.0F),PartPose.offset(0.0F,15.0F,3.5F));
}
case "fen_strider" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.0F,-3.0F,-3.5F,4.0F,5.0F,7.0F).texOffs(23,0).addBox(-1.5F,-6.0F,-4.0F,3.0F,4.0F,3.0F),PartPose.offset(0.0F,8.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(36,0).addBox(-2.0F,-3.0F,-4.0F,4.0F,4.0F,5.0F).texOffs(114,0).addBox(-1.8F,-5.0F,-3.5F,1.0F,5.0F,1.0F).texOffs(119,0).addBox(0.8F,-7.0F,-3.5F,1.0F,3.0F,1.0F).texOffs(124,0).addBox(-1.3F,0.0F,-6.5F,2.0F,1.0F,2.0F),PartPose.offset(0.0F,3.0F,-4.5F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(78,0).addBox(-1.0F,0.0F,-1.0F,2.0F,13.0F,2.0F),PartPose.offset(-3.0F,11.0F,-2.5F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(87,0).addBox(-1.0F,0.0F,-1.0F,2.0F,13.0F,2.0F),PartPose.offset(3.0F,11.0F,-2.5F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(96,0).addBox(-1.0F,0.0F,-1.0F,2.0F,13.0F,2.0F),PartPose.offset(-3.0F,11.0F,2.5F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(105,0).addBox(-1.0F,0.0F,-1.0F,2.0F,13.0F,2.0F),PartPose.offset(3.0F,11.0F,2.5F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(55,0).addBox(-1.0F,-1.0F,0.0F,2.0F,2.0F,9.0F),PartPose.offset(0.0F,8.0F,3.5F));
}
case "bog_floater" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-6.0F,-2.0F,-6.0F,12.0F,2.0F,12.0F).texOffs(49,0).addBox(-5.0F,0.0F,-5.0F,10.0F,2.0F,10.0F).texOffs(90,0).addBox(-4.0F,2.0F,-4.0F,8.0F,2.0F,8.0F).texOffs(123,0).addBox(-7.0F,6.0F,-7.0F,14.0F,1.0F,14.0F),PartPose.offset(0.0F,7.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(210,0).addBox(-1.5F,-1.5F,-1.5F,3.0F,3.0F,3.0F).texOffs(223,0).addBox(-1.0F,0.5F,-3.0F,2.0F,1.0F,2.0F),PartPose.offset(0.0F,12.0F,0.0F));
root.addOrReplaceChild("tendril0",CubeListBuilder.create().texOffs(180,0).addBox(-0.5F,0.0F,-0.5F,1.0F,11.0F,1.0F),PartPose.offset(5.4F,14.0F,1.1F));
root.addOrReplaceChild("tendril1",CubeListBuilder.create().texOffs(185,0).addBox(-0.5F,0.0F,-0.5F,1.0F,8.0F,1.0F),PartPose.offset(1.6F,14.0F,5.2F));
root.addOrReplaceChild("tendril2",CubeListBuilder.create().texOffs(190,0).addBox(-0.5F,0.0F,-0.5F,1.0F,13.0F,1.0F),PartPose.offset(-3.6F,14.0F,4.1F));
root.addOrReplaceChild("tendril3",CubeListBuilder.create().texOffs(195,0).addBox(-0.5F,0.0F,-0.5F,1.0F,10.0F,1.0F),PartPose.offset(-5.4F,14.0F,-0.9F));
root.addOrReplaceChild("tendril4",CubeListBuilder.create().texOffs(200,0).addBox(-0.5F,0.0F,-0.5F,1.0F,10.0F,1.0F),PartPose.offset(-4.0F,14.0F,-3.8F));
root.addOrReplaceChild("tendril5",CubeListBuilder.create().texOffs(205,0).addBox(-0.5F,0.0F,-0.5F,1.0F,11.0F,1.0F),PartPose.offset(3.2F,14.0F,-4.5F));
}
case "reed_coil" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(63,0).addBox(-4.0F,0.0F,-3.0F,8.0F,2.0F,8.0F).texOffs(96,0).addBox(-1.5F,-6.0F,-7.0F,3.0F,3.0F,4.0F),PartPose.offset(0.0F,22.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(111,0).addBox(-2.0F,-2.0F,-4.0F,4.0F,4.0F,4.0F).texOffs(128,0).addBox(-1.5F,-6.0F,-1.5F,1.0F,4.0F,1.0F).texOffs(133,0).addBox(0.5F,-6.0F,-1.5F,1.0F,4.0F,1.0F).texOffs(138,0).addBox(-1.3F,1.0F,-6.0F,2.0F,1.0F,2.0F),PartPose.offset(0.0F,17.0F,-7.0F));
root.addOrReplaceChild("seg0",CubeListBuilder.create().texOffs(0,0).addBox(-5.0F,-10.0F,-1.5F,10.0F,10.0F,3.0F),PartPose.offset(0.0F,20.0F,1.0F));
root.addOrReplaceChild("seg1",CubeListBuilder.create().texOffs(27,0).addBox(-3.5F,-7.0F,-1.5F,7.0F,7.0F,3.0F),PartPose.offset(0.0F,18.0F,3.5F));
root.addOrReplaceChild("seg2",CubeListBuilder.create().texOffs(48,0).addBox(-2.0F,-4.0F,-1.5F,4.0F,4.0F,3.0F),PartPose.offset(0.0F,16.0F,6.0F));
}
case "chime_grazer" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-3.0F,-3.0F,-5.0F,6.0F,6.0F,10.0F).texOffs(54,0).addBox(-0.5F,-9.0F,-3.3F,1.0F,6.0F,7.0F).texOffs(144,0).addBox(-2.0F,-5.5F,-4.0F,3.0F,2.0F,2.0F).texOffs(155,0).addBox(-2.0F,-5.5F,-1.0F,3.0F,2.0F,2.0F).texOffs(166,0).addBox(-2.0F,-5.5F,2.0F,3.0F,2.0F,2.0F),PartPose.offset(0.0F,17.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(33,0).addBox(-2.5F,-2.5F,-4.0F,5.0F,5.0F,5.0F).texOffs(123,0).addBox(-2.2F,-5.5F,-3.5F,1.0F,4.0F,1.0F).texOffs(128,0).addBox(1.2F,-6.5F,-3.5F,1.0F,3.0F,1.0F).texOffs(133,0).addBox(-1.7F,1.5F,-6.5F,3.0F,1.0F,2.0F),PartPose.offset(0.0F,16.0F,-7.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(71,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F),PartPose.offset(-3.0F,18.0F,-3.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(84,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F),PartPose.offset(3.0F,18.0F,-3.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(97,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F),PartPose.offset(-3.0F,18.0F,3.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(110,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F),PartPose.offset(3.0F,18.0F,3.0F));
}
case "glass_flitter" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.0F,-3.0F,-4.0F,4.0F,6.0F,8.0F).texOffs(111,0).addBox(-2.5F,1.5F,10.0F,1.0F,1.0F,6.0F).texOffs(126,0).addBox(-0.5F,0.5F,10.0F,1.0F,1.0F,7.0F).texOffs(143,0).addBox(1.5F,1.5F,10.0F,1.0F,1.0F,7.0F),PartPose.offset(0.0F,14.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(25,0).addBox(-2.0F,-2.0F,-3.0F,4.0F,4.0F,4.0F).texOffs(160,0).addBox(-1.5F,-3.5F,-7.0F,1.0F,1.0F,4.0F).texOffs(171,0).addBox(0.5F,-3.5F,-8.0F,1.0F,1.0F,3.0F).texOffs(180,0).addBox(-1.3F,1.0F,-5.0F,2.0F,1.0F,2.0F),PartPose.offset(0.0F,11.0F,-4.0F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(96,0).addBox(-0.5F,-1.0F,0.0F,1.0F,2.0F,6.0F),PartPose.offset(0.0F,15.0F,4.0F));
root.addOrReplaceChild("wing0",CubeListBuilder.create().texOffs(42,0).addBox(-10.0F,-1.0F,-2.0F,10.0F,1.0F,3.0F),PartPose.offset(-2.0F,13.0F,-1.0F));
root.addOrReplaceChild("wing1",CubeListBuilder.create().texOffs(69,0).addBox(0.0F,-1.0F,-2.0F,10.0F,1.0F,3.0F),PartPose.offset(2.0F,13.0F,-1.0F));
}
case "geode_grub" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-7.0F,-3.0F,-7.0F,14.0F,3.0F,14.0F).texOffs(57,0).addBox(-6.0F,-6.0F,-6.0F,12.0F,3.0F,12.0F).texOffs(106,0).addBox(-4.5F,-8.0F,-4.5F,9.0F,2.0F,9.0F).texOffs(164,0).addBox(-8.0F,-3.0F,-6.5F,3.0F,2.0F,3.0F).texOffs(177,0).addBox(6.0F,-3.0F,-6.5F,3.0F,2.0F,3.0F).texOffs(190,0).addBox(-8.0F,-4.0F,-3.5F,3.0F,2.0F,3.0F).texOffs(203,0).addBox(6.0F,-4.0F,-3.5F,3.0F,2.0F,3.0F).texOffs(216,0).addBox(-8.0F,-5.0F,-0.5F,3.0F,2.0F,3.0F).texOffs(229,0).addBox(6.0F,-5.0F,-0.5F,3.0F,2.0F,3.0F).texOffs(242,0).addBox(-8.0F,-6.0F,2.5F,3.0F,2.0F,3.0F).texOffs(0,18).addBox(6.0F,-6.0F,2.5F,3.0F,2.0F,3.0F),PartPose.offset(0.0F,21.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(143,0).addBox(-2.5F,-2.5F,-4.0F,5.0F,5.0F,5.0F).texOffs(65,18).addBox(-2.2F,-5.5F,-3.5F,1.0F,2.0F,1.0F).texOffs(70,18).addBox(1.2F,-4.5F,-3.5F,1.0F,5.0F,1.0F).texOffs(75,18).addBox(-1.7F,1.5F,-6.5F,3.0F,1.0F,2.0F),PartPose.offset(0.0F,17.0F,-8.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(13,18).addBox(-1.5F,0.0F,-1.5F,3.0F,3.0F,3.0F),PartPose.offset(-5.0F,21.0F,-5.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(26,18).addBox(-1.5F,0.0F,-1.5F,3.0F,3.0F,3.0F),PartPose.offset(5.0F,21.0F,-5.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(39,18).addBox(-1.5F,0.0F,-1.5F,3.0F,3.0F,3.0F),PartPose.offset(-5.0F,21.0F,5.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(52,18).addBox(-1.5F,0.0F,-1.5F,3.0F,3.0F,3.0F),PartPose.offset(5.0F,21.0F,5.0F));
}
case "shard_stalker" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.0F,-2.0F,-3.0F,4.0F,4.0F,6.0F).texOffs(38,0).addBox(-3.0F,-6.0F,2.0F,6.0F,5.0F,6.0F),PartPose.offset(0.0F,11.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(21,0).addBox(-2.0F,-2.0F,-3.0F,4.0F,4.0F,4.0F).texOffs(63,0).addBox(-2.0F,0.5F,-6.0F,1.0F,1.0F,3.0F).texOffs(72,0).addBox(1.0F,0.5F,-6.0F,1.0F,1.0F,3.0F).texOffs(0,14).addBox(-1.3F,1.0F,-5.0F,2.0F,1.0F,2.0F),PartPose.offset(0.0F,11.0F,-5.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(81,0).addBox(-1.0F,0.0F,-1.0F,2.0F,11.0F,2.0F).texOffs(90,0).addBox(-2.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(-3.0F,13.0F,-6.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(103,0).addBox(-1.0F,0.0F,-1.0F,2.0F,11.0F,2.0F).texOffs(112,0).addBox(-0.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(3.0F,13.0F,-6.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(125,0).addBox(-1.0F,0.0F,-1.0F,2.0F,11.0F,2.0F).texOffs(134,0).addBox(-2.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(-3.0F,13.0F,-3.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(147,0).addBox(-1.0F,0.0F,-1.0F,2.0F,11.0F,2.0F).texOffs(156,0).addBox(-0.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(3.0F,13.0F,-3.0F));
root.addOrReplaceChild("leg4",CubeListBuilder.create().texOffs(169,0).addBox(-1.0F,0.0F,-1.0F,2.0F,11.0F,2.0F).texOffs(178,0).addBox(-2.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(-3.0F,13.0F,0.0F));
root.addOrReplaceChild("leg5",CubeListBuilder.create().texOffs(191,0).addBox(-1.0F,0.0F,-1.0F,2.0F,11.0F,2.0F).texOffs(200,0).addBox(-0.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(3.0F,13.0F,0.0F));
root.addOrReplaceChild("leg6",CubeListBuilder.create().texOffs(213,0).addBox(-1.0F,0.0F,-1.0F,2.0F,11.0F,2.0F).texOffs(222,0).addBox(-2.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(-3.0F,13.0F,3.0F));
root.addOrReplaceChild("leg7",CubeListBuilder.create().texOffs(235,0).addBox(-1.0F,0.0F,-1.0F,2.0F,11.0F,2.0F).texOffs(244,0).addBox(-0.5F,0.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(3.0F,13.0F,3.0F));
}
case "silt_glider" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(38,0).addBox(-0.5F,-2.0F,-2.0F,1.0F,2.0F,4.0F).texOffs(66,0).addBox(-0.5F,-1.0F,2.0F,1.0F,2.0F,4.0F).texOffs(92,0).addBox(-0.5F,-0.5F,6.0F,1.0F,2.0F,4.0F).texOffs(118,0).addBox(-0.5F,-1.5F,10.0F,1.0F,2.0F,4.0F).texOffs(142,0).addBox(-0.5F,-1.0F,14.0F,1.0F,2.0F,4.0F).texOffs(166,0).addBox(-0.5F,-2.0F,18.0F,1.0F,2.0F,4.0F),PartPose.offset(0.0F,12.0F,-12.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,-2.0F,-4.0F,5.0F,4.0F,5.0F).texOffs(188,0).addBox(-1.7F,1.0F,-6.5F,3.0F,1.0F,2.0F),PartPose.offset(0.0F,14.0F,-16.0F));
root.addOrReplaceChild("seg0",CubeListBuilder.create().texOffs(21,0).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,14.0F,-12.0F));
root.addOrReplaceChild("seg1",CubeListBuilder.create().texOffs(49,0).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,15.0F,-8.0F));
root.addOrReplaceChild("seg2",CubeListBuilder.create().texOffs(77,0).addBox(-1.5F,-1.5F,-2.0F,3.0F,3.0F,4.0F),PartPose.offset(0.0F,15.0F,-4.0F));
root.addOrReplaceChild("seg3",CubeListBuilder.create().texOffs(103,0).addBox(-1.5F,-1.5F,-2.0F,3.0F,3.0F,4.0F),PartPose.offset(0.0F,14.0F,0.0F));
root.addOrReplaceChild("seg4",CubeListBuilder.create().texOffs(129,0).addBox(-1.0F,-1.0F,-2.0F,2.0F,2.0F,4.0F),PartPose.offset(0.0F,14.0F,4.0F));
root.addOrReplaceChild("seg5",CubeListBuilder.create().texOffs(153,0).addBox(-1.0F,-1.0F,-2.0F,2.0F,2.0F,4.0F),PartPose.offset(0.0F,13.0F,8.0F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(177,0).addBox(-0.5F,-3.0F,0.0F,1.0F,6.0F,4.0F),PartPose.offset(0.0F,14.0F,12.0F));
}
case "pale_drifter" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-8.0F,-2.0F,-6.0F,16.0F,2.0F,12.0F),PartPose.offset(0.0F,11.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(129,0).addBox(-2.5F,-2.0F,-3.0F,5.0F,3.0F,4.0F).texOffs(148,0).addBox(-1.7F,0.0F,-5.0F,3.0F,1.0F,2.0F),PartPose.offset(0.0F,10.0F,-7.0F));
root.addOrReplaceChild("tendril0",CubeListBuilder.create().texOffs(119,0).addBox(-0.5F,0.0F,-0.5F,1.0F,13.0F,1.0F),PartPose.offset(-2.0F,13.0F,5.0F));
root.addOrReplaceChild("tendril1",CubeListBuilder.create().texOffs(124,0).addBox(-0.5F,0.0F,-0.5F,1.0F,17.0F,1.0F),PartPose.offset(2.0F,13.0F,5.0F));
root.addOrReplaceChild("wing0",CubeListBuilder.create().texOffs(57,0).addBox(-5.0F,-1.0F,-5.0F,5.0F,1.0F,10.0F),PartPose.offset(-8.0F,12.0F,0.0F));
root.addOrReplaceChild("wing1",CubeListBuilder.create().texOffs(88,0).addBox(0.0F,-1.0F,-5.0F,5.0F,1.0F,10.0F),PartPose.offset(8.0F,12.0F,0.0F));
}
case "shoal_darter" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-3.0F,-2.0F,-5.0F,6.0F,4.0F,10.0F).texOffs(52,0).addBox(-0.5F,-5.0F,-2.5F,1.0F,4.0F,5.0F).texOffs(74,0).addBox(-6.0F,0.5F,-2.0F,3.0F,1.0F,4.0F).texOffs(89,0).addBox(3.0F,0.5F,-2.0F,3.0F,1.0F,4.0F),PartPose.offset(0.0F,14.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(33,0).addBox(-2.5F,-1.5F,-4.0F,5.0F,3.0F,4.0F).texOffs(104,0).addBox(-1.7F,0.5F,-6.0F,3.0F,1.0F,2.0F),PartPose.offset(0.0F,14.0F,-7.0F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(65,0).addBox(-0.5F,-3.0F,0.0F,1.0F,6.0F,3.0F),PartPose.offset(0.0F,14.0F,5.0F));
}
case "brine_lurker" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(44,0).addBox(-0.5F,-3.0F,-1.5F,1.0F,3.0F,3.0F).texOffs(89,0).addBox(-0.5F,-3.0F,6.5F,1.0F,3.0F,3.0F).texOffs(130,0).addBox(-0.5F,-3.0F,14.5F,1.0F,3.0F,3.0F),PartPose.offset(0.0F,17.0F,-10.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(0,0).addBox(-3.5F,-3.0F,-4.0F,7.0F,4.0F,5.0F).texOffs(150,0).addBox(-1.5F,-4.5F,-8.0F,1.0F,1.0F,4.0F).texOffs(161,0).addBox(0.5F,-4.5F,-9.0F,1.0F,1.0F,5.0F).texOffs(174,0).addBox(-2.3F,0.0F,-6.5F,4.0F,1.0F,2.0F),PartPose.offset(0.0F,11.0F,-15.0F));
root.addOrReplaceChild("seg0",CubeListBuilder.create().texOffs(25,0).addBox(-2.5F,-2.0F,-2.0F,5.0F,4.0F,4.0F),PartPose.offset(0.0F,19.0F,-10.0F));
root.addOrReplaceChild("seg1",CubeListBuilder.create().texOffs(53,0).addBox(-2.5F,-2.0F,-2.0F,5.0F,4.0F,4.0F),PartPose.offset(0.0F,19.0F,-6.0F));
root.addOrReplaceChild("seg2",CubeListBuilder.create().texOffs(72,0).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,19.0F,-2.0F));
root.addOrReplaceChild("seg3",CubeListBuilder.create().texOffs(98,0).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,19.0F,2.0F));
root.addOrReplaceChild("seg4",CubeListBuilder.create().texOffs(115,0).addBox(-1.5F,-2.0F,-2.0F,3.0F,4.0F,4.0F),PartPose.offset(0.0F,19.0F,6.0F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(139,0).addBox(-0.5F,-3.0F,0.0F,1.0F,6.0F,4.0F),PartPose.offset(0.0F,19.0F,10.0F));
}
case "hearth_warden" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-4.0F,-3.0F,-4.0F,8.0F,3.0F,8.0F).texOffs(33,0).addBox(-4.0F,-6.0F,-4.0F,8.0F,3.0F,8.0F).texOffs(66,0).addBox(-4.0F,-9.0F,-4.0F,8.0F,3.0F,8.0F).texOffs(27,12).addBox(-13.0F,-3.0F,-0.5F,9.0F,2.0F,4.0F).texOffs(54,12).addBox(4.0F,-3.0F,-0.5F,10.0F,2.0F,4.0F).texOffs(83,12).addBox(-6.5F,-14.0F,-6.5F,13.0F,4.0F,13.0F).texOffs(136,12).addBox(-13.5F,-12.0F,-4.5F,9.0F,4.0F,9.0F).texOffs(173,12).addBox(4.5F,-12.0F,-4.5F,9.0F,4.0F,9.0F).texOffs(210,12).addBox(-4.5F,-12.0F,-13.5F,9.0F,4.0F,9.0F).texOffs(0,30).addBox(-4.5F,-12.0F,4.5F,9.0F,4.0F,9.0F).texOffs(37,30).addBox(-5.5F,-3.5F,-1.5F,3.0F,3.0F,1.0F).texOffs(46,30).addBox(2.5F,-4.5F,0.5F,3.0F,3.0F,1.0F).texOffs(55,30).addBox(2.5F,-4.5F,-2.5F,3.0F,3.0F,1.0F).texOffs(64,30).addBox(2.5F,-3.5F,0.5F,3.0F,3.0F,1.0F).texOffs(73,30).addBox(-5.5F,-4.5F,-1.5F,3.0F,3.0F,1.0F),PartPose.offset(0.0F,20.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(228,0).addBox(-8.0F,-2.0F,-2.0F,8.0F,2.0F,4.0F),PartPose.offset(-4.0F,15.0F,-1.5F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(0,12).addBox(0.0F,-2.0F,-2.0F,9.0F,2.0F,4.0F),PartPose.offset(4.0F,15.0F,-1.5F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(99,0).addBox(-3.0F,-5.0F,-1.0F,6.0F,5.0F,2.0F),PartPose.offset(0.0F,15.9F,-4.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(116,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(129,0).addBox(-1.5F,2.0F,-4.0F,2.0F,2.0F,5.0F),PartPose.offset(-3.5F,20.0F,-3.5F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(144,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(157,0).addBox(-0.5F,2.0F,-4.0F,2.0F,2.0F,5.0F),PartPose.offset(3.5F,20.0F,-3.5F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(172,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(185,0).addBox(-1.5F,2.0F,-1.0F,2.0F,2.0F,5.0F),PartPose.offset(-3.5F,20.0F,3.5F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(200,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(213,0).addBox(-0.5F,2.0F,-1.0F,2.0F,2.0F,5.0F),PartPose.offset(3.5F,20.0F,3.5F));
}
case "grove_elder" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-3.0F,-3.7F,-3.0F,6.0F,3.7F,6.0F).texOffs(25,0).addBox(-3.0F,-7.3F,-3.0F,6.0F,3.7F,6.0F).texOffs(50,0).addBox(-3.0F,-11.0F,-3.0F,6.0F,3.7F,6.0F).texOffs(217,0).addBox(-8.0F,-7.0F,-1.0F,2.0F,5.0F,2.0F).texOffs(241,0).addBox(5.0F,-5.0F,-1.0F,2.0F,3.0F,2.0F).texOffs(0,11).addBox(-10.0F,-7.0F,-1.5F,7.0F,2.0F,3.0F).texOffs(21,11).addBox(-10.0F,-8.0F,-1.0F,2.0F,3.0F,2.0F).texOffs(30,11).addBox(3.0F,-7.0F,-1.5F,6.0F,2.0F,3.0F).texOffs(49,11).addBox(7.0F,-10.0F,-1.0F,2.0F,4.0F,2.0F).texOffs(58,11).addBox(-9.0F,-10.0F,-1.5F,6.0F,2.0F,3.0F).texOffs(77,11).addBox(-9.0F,-13.0F,-1.0F,2.0F,5.0F,2.0F).texOffs(86,11).addBox(3.0F,-10.0F,-1.5F,4.0F,2.0F,3.0F).texOffs(101,11).addBox(5.0F,-13.0F,-1.0F,2.0F,3.0F,2.0F).texOffs(110,11).addBox(-4.5F,-16.0F,-4.5F,9.0F,4.0F,9.0F).texOffs(147,11).addBox(-8.0F,-14.0F,-3.0F,6.0F,4.0F,6.0F).texOffs(172,11).addBox(2.0F,-17.0F,-3.0F,6.0F,4.0F,6.0F).texOffs(197,11).addBox(-3.0F,-15.0F,-8.0F,6.0F,4.0F,6.0F).texOffs(222,11).addBox(-3.0F,-13.0F,2.0F,6.0F,4.0F,6.0F).texOffs(247,11).addBox(-4.5F,-3.5F,-1.5F,3.0F,3.0F,1.0F).texOffs(0,25).addBox(-4.5F,-3.5F,-1.5F,3.0F,3.0F,1.0F).texOffs(9,25).addBox(1.5F,-3.5F,-1.5F,3.0F,3.0F,1.0F).texOffs(18,25).addBox(1.5F,-4.5F,-0.5F,3.0F,3.0F,1.0F).texOffs(27,25).addBox(-4.5F,-3.5F,0.5F,3.0F,3.0F,1.0F),PartPose.offset(0.0F,20.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(200,0).addBox(-5.0F,-2.0F,-1.5F,5.0F,2.0F,3.0F),PartPose.offset(-3.0F,18.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(226,0).addBox(0.0F,-2.0F,-1.5F,4.0F,2.0F,3.0F),PartPose.offset(3.0F,18.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(75,0).addBox(-2.0F,-5.0F,-1.0F,4.0F,5.0F,2.0F),PartPose.offset(0.0F,15.1F,-3.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(88,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(101,0).addBox(-1.5F,2.0F,-4.0F,2.0F,2.0F,5.0F),PartPose.offset(-2.5F,20.0F,-2.5F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(116,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(129,0).addBox(-0.5F,2.0F,-4.0F,2.0F,2.0F,5.0F),PartPose.offset(2.5F,20.0F,-2.5F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(144,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(157,0).addBox(-1.5F,2.0F,-1.0F,2.0F,2.0F,5.0F),PartPose.offset(-2.5F,20.0F,2.5F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(172,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(185,0).addBox(-0.5F,2.0F,-1.0F,2.0F,2.0F,5.0F),PartPose.offset(2.5F,20.0F,2.5F));
}
case "frostpine_sentinel" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,-3.0F,-2.5F,5.0F,3.0F,5.0F).texOffs(21,0).addBox(-2.5F,-6.0F,-2.5F,5.0F,3.0F,5.0F).texOffs(42,0).addBox(-2.5F,-9.0F,-2.5F,5.0F,3.0F,5.0F).texOffs(63,0).addBox(-2.5F,-12.0F,-2.5F,5.0F,3.0F,5.0F).texOffs(84,0).addBox(-2.0F,-15.0F,-2.0F,4.0F,3.0F,4.0F).texOffs(101,0).addBox(-2.0F,-18.0F,-2.0F,4.0F,3.0F,4.0F).texOffs(0,9).addBox(-6.5F,-7.0F,-6.5F,13.0F,2.0F,13.0F).texOffs(53,9).addBox(-7.0F,-9.0F,-5.5F,3.0F,2.0F,11.0F).texOffs(82,9).addBox(4.0F,-9.0F,-5.5F,3.0F,2.0F,11.0F).texOffs(111,9).addBox(-5.5F,-9.4F,-5.5F,11.0F,2.0F,11.0F).texOffs(156,9).addBox(-6.0F,-11.4F,-4.5F,3.0F,2.0F,9.0F).texOffs(181,9).addBox(3.0F,-11.4F,-4.5F,3.0F,2.0F,9.0F).texOffs(206,9).addBox(-4.5F,-11.8F,-4.5F,9.0F,2.0F,9.0F).texOffs(0,25).addBox(-5.0F,-13.8F,-3.5F,3.0F,2.0F,7.0F).texOffs(21,25).addBox(2.0F,-13.8F,-3.5F,3.0F,2.0F,7.0F).texOffs(42,25).addBox(-3.5F,-14.2F,-3.5F,7.0F,2.0F,7.0F).texOffs(71,25).addBox(-4.0F,-16.2F,-2.5F,3.0F,2.0F,5.0F).texOffs(88,25).addBox(1.0F,-16.2F,-2.5F,3.0F,2.0F,5.0F).texOffs(105,25).addBox(-2.5F,-16.6F,-2.5F,5.0F,2.0F,5.0F).texOffs(126,25).addBox(-3.0F,-18.6F,-1.5F,3.0F,2.0F,3.0F).texOffs(139,25).addBox(0.0F,-18.6F,-1.5F,3.0F,2.0F,3.0F).texOffs(152,25).addBox(-2.0F,-21.0F,-2.0F,4.0F,4.0F,4.0F).texOffs(169,25).addBox(1.0F,-4.5F,1.5F,3.0F,3.0F,1.0F).texOffs(178,25).addBox(1.0F,-3.5F,-1.5F,3.0F,3.0F,1.0F).texOffs(187,25).addBox(-4.0F,-3.5F,1.5F,3.0F,3.0F,1.0F),PartPose.offset(0.0F,20.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(118,0).addBox(-1.5F,-5.0F,-1.0F,3.0F,5.0F,2.0F),PartPose.offset(0.0F,11.9F,-2.5F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(129,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(142,0).addBox(-1.5F,2.0F,-4.0F,2.0F,2.0F,5.0F),PartPose.offset(-2.0F,20.0F,-2.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(157,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(170,0).addBox(-0.5F,2.0F,-4.0F,2.0F,2.0F,5.0F),PartPose.offset(2.0F,20.0F,-2.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(185,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(198,0).addBox(-1.5F,2.0F,-1.0F,2.0F,2.0F,5.0F),PartPose.offset(-2.0F,20.0F,2.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(213,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(226,0).addBox(-0.5F,2.0F,-1.0F,2.0F,2.0F,5.0F),PartPose.offset(2.0F,20.0F,2.0F));
}
case "snagwalker" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,-3.0F,-2.5F,5.0F,3.0F,5.0F).texOffs(21,0).addBox(-1.1F,-6.0F,-2.5F,5.0F,3.0F,5.0F).texOffs(42,0).addBox(0.4F,-9.0F,-2.5F,5.0F,3.0F,5.0F).texOffs(63,0).addBox(1.8F,-12.0F,-2.5F,5.0F,3.0F,5.0F).texOffs(224,0).addBox(-4.8F,-7.0F,-1.0F,2.0F,4.0F,2.0F).texOffs(0,9).addBox(8.2F,-10.0F,-1.0F,2.0F,2.0F,2.0F).texOffs(9,9).addBox(-3.8F,-11.0F,-1.5F,4.0F,2.0F,3.0F).texOffs(24,9).addBox(-3.8F,-11.0F,-1.0F,2.0F,4.0F,2.0F).texOffs(33,9).addBox(5.2F,-14.0F,-1.5F,5.0F,2.0F,3.0F).texOffs(50,9).addBox(8.2F,-16.0F,-1.0F,2.0F,4.0F,2.0F).texOffs(59,9).addBox(1.8F,-12.0F,-3.5F,3.0F,2.0F,3.0F).texOffs(72,9).addBox(4.3F,-11.0F,-1.5F,3.0F,2.0F,3.0F).texOffs(85,9).addBox(6.8F,-10.0F,0.5F,3.0F,2.0F,3.0F).texOffs(98,9).addBox(-4.0F,-3.5F,1.5F,3.0F,3.0F,1.0F).texOffs(107,9).addBox(-4.0F,-4.5F,-1.5F,3.0F,3.0F,1.0F).texOffs(116,9).addBox(1.0F,-3.5F,1.5F,3.0F,3.0F,1.0F).texOffs(125,9).addBox(1.0F,-4.5F,-1.5F,3.0F,3.0F,1.0F).texOffs(134,9).addBox(-4.0F,-3.5F,-0.5F,3.0F,3.0F,1.0F),PartPose.offset(0.0F,20.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(207,0).addBox(-5.0F,-2.0F,-1.5F,5.0F,2.0F,3.0F),PartPose.offset(0.2F,17.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(233,0).addBox(0.0F,-2.0F,-1.5F,5.0F,2.0F,3.0F),PartPose.offset(5.2F,14.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(84,0).addBox(-1.5F,-5.0F,-1.0F,3.0F,5.0F,2.0F),PartPose.offset(2.9F,14.6F,-2.5F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(95,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(108,0).addBox(-1.5F,2.0F,-4.0F,2.0F,2.0F,5.0F),PartPose.offset(-2.0F,20.0F,-2.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(123,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(136,0).addBox(-0.5F,2.0F,-4.0F,2.0F,2.0F,5.0F),PartPose.offset(2.0F,20.0F,-2.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(151,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(164,0).addBox(-1.5F,2.0F,-1.0F,2.0F,2.0F,5.0F),PartPose.offset(-2.0F,20.0F,2.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(179,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(192,0).addBox(-0.5F,2.0F,-1.0F,2.0F,2.0F,5.0F),PartPose.offset(2.0F,20.0F,2.0F));
}
case "weeping_warden" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,-3.4F,-2.5F,5.0F,3.4F,5.0F).texOffs(21,0).addBox(-2.5F,-6.8F,-2.5F,5.0F,3.4F,5.0F).texOffs(42,0).addBox(-2.5F,-10.2F,-2.5F,5.0F,3.4F,5.0F).texOffs(63,0).addBox(-2.0F,-13.6F,-2.0F,4.0F,3.4F,4.0F).texOffs(80,0).addBox(-2.0F,-17.0F,-2.0F,4.0F,3.4F,4.0F).texOffs(241,0).addBox(-9.5F,-1.0F,-1.0F,2.0F,7.0F,2.0F).texOffs(19,10).addBox(6.5F,-1.0F,-1.0F,2.0F,11.0F,2.0F).texOffs(28,10).addBox(-7.5F,-7.0F,-1.5F,5.0F,2.0F,3.0F).texOffs(45,10).addBox(-7.5F,-4.0F,-1.0F,2.0F,12.0F,2.0F).texOffs(54,10).addBox(2.5F,-7.0F,-1.5F,6.0F,2.0F,3.0F).texOffs(73,10).addBox(6.5F,-4.0F,-1.0F,2.0F,12.0F,2.0F).texOffs(82,10).addBox(-9.5F,-10.0F,-1.5F,7.0F,2.0F,3.0F).texOffs(103,10).addBox(-9.5F,-7.0F,-1.0F,2.0F,7.0F,2.0F).texOffs(112,10).addBox(2.5F,-10.0F,-1.5F,5.0F,2.0F,3.0F).texOffs(129,10).addBox(5.5F,-7.0F,-1.0F,2.0F,8.0F,2.0F).texOffs(138,10).addBox(-4.5F,-19.0F,-4.5F,9.0F,3.0F,9.0F).texOffs(175,10).addBox(-3.5F,-21.0F,-3.5F,7.0F,3.0F,7.0F).texOffs(204,10).addBox(-2.5F,-23.0F,-2.5F,5.0F,3.0F,5.0F).texOffs(225,10).addBox(1.0F,-4.5F,-2.5F,3.0F,3.0F,1.0F).texOffs(234,10).addBox(1.0F,-3.5F,-0.5F,3.0F,3.0F,1.0F).texOffs(243,10).addBox(-4.0F,-3.5F,-1.5F,3.0F,3.0F,1.0F).texOffs(0,25).addBox(1.0F,-3.5F,-0.5F,3.0F,3.0F,1.0F).texOffs(9,25).addBox(1.0F,-4.5F,-1.5F,3.0F,3.0F,1.0F),PartPose.offset(0.0F,20.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(220,0).addBox(-7.0F,-2.0F,-1.5F,7.0F,2.0F,3.0F),PartPose.offset(-2.5F,18.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(0,10).addBox(0.0F,-2.0F,-1.5F,6.0F,2.0F,3.0F),PartPose.offset(2.5F,18.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(97,0).addBox(-1.5F,-5.0F,-1.0F,3.0F,5.0F,2.0F),PartPose.offset(0.0F,12.4F,-2.5F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(108,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(121,0).addBox(-1.5F,2.0F,-4.0F,2.0F,2.0F,5.0F),PartPose.offset(-2.0F,20.0F,-2.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(136,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(149,0).addBox(-0.5F,2.0F,-4.0F,2.0F,2.0F,5.0F),PartPose.offset(2.0F,20.0F,-2.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(164,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(177,0).addBox(-1.5F,2.0F,-1.0F,2.0F,2.0F,5.0F),PartPose.offset(-2.0F,20.0F,2.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(192,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(205,0).addBox(-0.5F,2.0F,-1.0F,2.0F,2.0F,5.0F),PartPose.offset(2.0F,20.0F,2.0F));
}
case "bellcap_elder" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.0F,-3.0F,-2.0F,4.0F,3.0F,4.0F).texOffs(17,0).addBox(-2.0F,-6.0F,-2.0F,4.0F,3.0F,4.0F).texOffs(34,0).addBox(-2.0F,-9.0F,-2.0F,4.0F,3.0F,4.0F).texOffs(51,0).addBox(-1.5F,-12.0F,-1.5F,3.0F,3.0F,3.0F).texOffs(64,0).addBox(-1.5F,-15.0F,-1.5F,3.0F,3.0F,3.0F).texOffs(198,0).addBox(-3.0F,-16.0F,-3.0F,6.0F,3.0F,6.0F).texOffs(0,10).addBox(-5.0F,-14.0F,-5.0F,10.0F,3.0F,10.0F).texOffs(41,10).addBox(-7.0F,-12.0F,-7.0F,14.0F,3.0F,14.0F).texOffs(98,10).addBox(5.0F,-7.0F,-1.0F,2.0F,3.0F,2.0F).texOffs(107,10).addBox(2.0F,-7.0F,4.2F,2.0F,3.0F,2.0F).texOffs(116,10).addBox(-4.0F,-7.0F,4.2F,2.0F,3.0F,2.0F).texOffs(125,10).addBox(-7.0F,-7.0F,-1.0F,2.0F,3.0F,2.0F).texOffs(134,10).addBox(-4.0F,-7.0F,-6.2F,2.0F,3.0F,2.0F).texOffs(143,10).addBox(2.0F,-7.0F,-6.2F,2.0F,3.0F,2.0F).texOffs(152,10).addBox(0.5F,-3.5F,-1.5F,3.0F,3.0F,1.0F).texOffs(161,10).addBox(0.5F,-4.5F,-0.5F,3.0F,3.0F,1.0F).texOffs(170,10).addBox(-3.5F,-4.5F,0.5F,3.0F,3.0F,1.0F).texOffs(179,10).addBox(0.5F,-3.5F,0.5F,3.0F,3.0F,1.0F).texOffs(188,10).addBox(0.5F,-3.5F,-1.5F,3.0F,3.0F,1.0F),PartPose.offset(0.0F,20.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(77,0).addBox(-1.0F,-5.0F,-1.0F,2.0F,5.0F,2.0F),PartPose.offset(0.0F,13.2F,-2.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(86,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(99,0).addBox(-1.5F,2.0F,-4.0F,2.0F,2.0F,5.0F),PartPose.offset(-1.5F,20.0F,-1.5F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(114,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(127,0).addBox(-0.5F,2.0F,-4.0F,2.0F,2.0F,5.0F),PartPose.offset(1.5F,20.0F,-1.5F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(142,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(155,0).addBox(-1.5F,2.0F,-1.0F,2.0F,2.0F,5.0F),PartPose.offset(-1.5F,20.0F,1.5F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(170,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F).texOffs(183,0).addBox(-0.5F,2.0F,-1.0F,2.0F,2.0F,5.0F),PartPose.offset(1.5F,20.0F,1.5F));
}
case "stiltwood" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,-3.3F,-2.5F,5.0F,3.3F,5.0F).texOffs(21,0).addBox(-2.5F,-6.7F,-2.5F,5.0F,3.3F,5.0F).texOffs(42,0).addBox(-2.5F,-10.0F,-2.5F,5.0F,3.3F,5.0F).texOffs(230,0).addBox(1.0F,-10.0F,-2.0F,8.0F,2.0F,4.0F).texOffs(0,10).addBox(-2.5F,-10.0F,2.8F,8.0F,2.0F,4.0F).texOffs(25,10).addBox(-8.0F,-10.0F,0.9F,8.0F,2.0F,4.0F).texOffs(50,10).addBox(-8.0F,-10.0F,-4.9F,8.0F,2.0F,4.0F).texOffs(75,10).addBox(-2.5F,-10.0F,-6.8F,8.0F,2.0F,4.0F).texOffs(100,10).addBox(-3.0F,-13.0F,-3.0F,6.0F,3.0F,6.0F).texOffs(125,10).addBox(-5.5F,-7.0F,1.0F,2.0F,9.0F,2.0F).texOffs(134,10).addBox(-2.5F,-7.0F,1.0F,2.0F,7.0F,2.0F).texOffs(143,10).addBox(0.5F,-7.0F,1.0F,2.0F,9.0F,2.0F).texOffs(152,10).addBox(3.5F,-7.0F,1.0F,2.0F,10.0F,2.0F).texOffs(161,10).addBox(-4.0F,-4.5F,-1.5F,3.0F,3.0F,1.0F).texOffs(170,10).addBox(1.0F,-4.5F,-0.5F,3.0F,3.0F,1.0F).texOffs(179,10).addBox(1.0F,-4.5F,-1.5F,3.0F,3.0F,1.0F).texOffs(188,10).addBox(1.0F,-4.5F,-0.5F,3.0F,3.0F,1.0F),PartPose.offset(0.0F,15.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(63,0).addBox(-1.5F,-5.0F,-1.0F,3.0F,5.0F,2.0F),PartPose.offset(0.0F,10.5F,-2.5F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(74,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F).texOffs(87,0).addBox(-3.0F,5.0F,-2.5F,3.0F,4.0F,3.0F),PartPose.offset(-3.5F,15.0F,-3.5F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(100,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F).texOffs(113,0).addBox(0.0F,5.0F,-2.5F,3.0F,4.0F,3.0F),PartPose.offset(3.5F,15.0F,-3.5F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(126,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F).texOffs(139,0).addBox(-3.0F,5.0F,-0.5F,3.0F,4.0F,3.0F),PartPose.offset(-3.5F,15.0F,3.5F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(152,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F).texOffs(165,0).addBox(0.0F,5.0F,-0.5F,3.0F,4.0F,3.0F),PartPose.offset(3.5F,15.0F,3.5F));
root.addOrReplaceChild("leg4",CubeListBuilder.create().texOffs(178,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F).texOffs(191,0).addBox(-3.0F,5.0F,-1.5F,3.0F,4.0F,3.0F),PartPose.offset(-3.5F,15.0F,0.0F));
root.addOrReplaceChild("leg5",CubeListBuilder.create().texOffs(204,0).addBox(-1.5F,0.0F,-1.5F,3.0F,6.0F,3.0F).texOffs(217,0).addBox(0.0F,5.0F,-1.5F,3.0F,4.0F,3.0F),PartPose.offset(3.5F,15.0F,0.0F));
}
case "colossus_warden" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-6.5F,-7.2F,-6.5F,13.0F,7.2F,13.0F).texOffs(53,0).addBox(-6.5F,-14.5F,-6.5F,13.0F,7.2F,13.0F).texOffs(106,0).addBox(-6.5F,-21.8F,-6.5F,13.0F,7.2F,13.0F).texOffs(159,0).addBox(-6.5F,-29.0F,-6.5F,13.0F,7.2F,13.0F).texOffs(232,22).addBox(-20.5F,-2.0F,-2.0F,4.0F,24.0F,4.0F).texOffs(41,51).addBox(16.5F,-2.0F,-2.0F,4.0F,14.0F,4.0F).texOffs(58,51).addBox(-18.5F,-14.0F,-3.0F,12.0F,4.0F,6.0F).texOffs(95,51).addBox(-18.5F,-8.0F,-2.0F,4.0F,20.0F,4.0F).texOffs(112,51).addBox(6.5F,-14.0F,-3.0F,10.0F,4.0F,6.0F).texOffs(145,51).addBox(12.5F,-8.0F,-2.0F,4.0F,24.0F,4.0F).texOffs(162,51).addBox(-18.5F,-20.0F,-3.0F,12.0F,4.0F,6.0F).texOffs(199,51).addBox(-18.5F,-14.0F,-2.0F,4.0F,18.0F,4.0F).texOffs(216,51).addBox(6.5F,-20.0F,-3.0F,10.0F,4.0F,6.0F).texOffs(0,80).addBox(12.5F,-14.0F,-2.0F,4.0F,20.0F,4.0F).texOffs(17,80).addBox(-18.5F,-26.0F,-3.0F,12.0F,4.0F,6.0F).texOffs(54,80).addBox(-18.5F,-20.0F,-2.0F,4.0F,24.0F,4.0F).texOffs(71,80).addBox(6.5F,-26.0F,-3.0F,10.0F,4.0F,6.0F).texOffs(104,80).addBox(12.5F,-20.0F,-2.0F,4.0F,20.0F,4.0F).texOffs(121,80).addBox(-11.5F,-33.0F,-11.5F,23.0F,6.0F,23.0F).texOffs(0,110).addBox(-9.5F,-37.0F,-9.5F,19.0F,6.0F,19.0F).texOffs(77,110).addBox(-7.5F,-41.0F,-7.5F,15.0F,6.0F,15.0F).texOffs(138,110).addBox(-8.0F,-3.5F,-0.5F,3.0F,3.0F,1.0F).texOffs(147,110).addBox(5.0F,-3.5F,0.5F,3.0F,3.0F,1.0F).texOffs(156,110).addBox(5.0F,-4.5F,0.5F,3.0F,3.0F,1.0F).texOffs(165,110).addBox(5.0F,-4.5F,0.5F,3.0F,3.0F,1.0F),PartPose.offset(0.0F,20.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(191,22).addBox(-14.0F,-4.0F,-3.0F,14.0F,4.0F,6.0F),PartPose.offset(-6.5F,16.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(0,51).addBox(0.0F,-4.0F,-3.0F,14.0F,4.0F,6.0F),PartPose.offset(6.5F,16.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(212,0).addBox(-3.5F,-8.0F,-1.0F,7.0F,8.0F,2.0F),PartPose.offset(0.0F,7.0F,-6.5F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(231,0).addBox(-3.0F,0.0F,-3.0F,6.0F,8.0F,6.0F).texOffs(0,22).addBox(-2.5F,4.0F,-6.5F,4.0F,4.0F,10.0F),PartPose.offset(-6.0F,20.0F,-6.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(29,22).addBox(-3.0F,0.0F,-3.0F,6.0F,8.0F,6.0F).texOffs(54,22).addBox(-1.5F,4.0F,-6.5F,4.0F,4.0F,10.0F),PartPose.offset(6.0F,20.0F,-6.0F));
root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(83,22).addBox(-3.0F,0.0F,-3.0F,6.0F,8.0F,6.0F).texOffs(108,22).addBox(-2.5F,4.0F,-3.5F,4.0F,4.0F,10.0F),PartPose.offset(-6.0F,20.0F,6.0F));
root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(137,22).addBox(-3.0F,0.0F,-3.0F,6.0F,8.0F,6.0F).texOffs(162,22).addBox(-1.5F,4.0F,-3.5F,4.0F,4.0F,10.0F),PartPose.offset(6.0F,20.0F,6.0F));
}
case "crag_troll" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-5.0F,0.0F,-3.0F,10.0F,10.0F,6.0F).texOffs(197,0).addBox(-4.0F,-1.0F,2.0F,8.0F,2.0F,3.0F).texOffs(220,0).addBox(-3.5F,1.5F,2.0F,7.0F,2.0F,3.0F).texOffs(0,17).addBox(-3.0F,4.0F,2.0F,6.0F,2.0F,3.0F).texOffs(19,17).addBox(-2.5F,6.5F,2.0F,5.0F,2.0F,3.0F),PartPose.offset(0.0F,7.0F,1.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(79,0).addBox(-2.0F,0.0F,-2.0F,4.0F,12.0F,4.0F).texOffs(113,0).addBox(-2.5F,12.0F,-2.5F,5.0F,4.0F,5.0F),PartPose.offset(-6.0F,8.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(96,0).addBox(-2.0F,0.0F,-2.0F,4.0F,12.0F,4.0F).texOffs(134,0).addBox(-2.5F,12.0F,-2.5F,5.0F,4.0F,5.0F),PartPose.offset(6.0F,8.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(33,0).addBox(-3.0F,-4.0F,-3.5F,6.0F,5.0F,7.0F).texOffs(60,0).addBox(-2.5F,4.0F,-4.0F,5.0F,2.0F,4.0F).texOffs(36,17).addBox(-3.5F,-8.0F,0.0F,2.0F,4.0F,2.0F).texOffs(45,17).addBox(1.5F,-8.0F,0.0F,2.0F,4.0F,2.0F),PartPose.offset(0.0F,8.0F,-3.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(155,0).addBox(-2.5F,0.0F,-2.5F,5.0F,7.0F,5.0F),PartPose.offset(-3.0F,17.0F,1.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(176,0).addBox(-2.5F,0.0F,-2.5F,5.0F,7.0F,5.0F),PartPose.offset(3.0F,17.0F,1.0F));
}
case "rime_troll" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-5.0F,0.0F,-3.0F,10.0F,12.0F,6.0F).texOffs(197,0).addBox(-3.5F,-4.0F,2.0F,2.0F,5.0F,2.0F).texOffs(206,0).addBox(1.5F,-5.0F,2.0F,2.0F,6.0F,2.0F).texOffs(215,0).addBox(-3.5F,-2.0F,2.0F,2.0F,6.0F,2.0F).texOffs(224,0).addBox(1.5F,0.0F,2.0F,2.0F,4.0F,2.0F).texOffs(233,0).addBox(-3.5F,2.0F,2.0F,2.0F,5.0F,2.0F).texOffs(0,19).addBox(-4.0F,-1.0F,1.0F,8.0F,2.0F,3.0F),PartPose.offset(0.0F,5.0F,1.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(79,0).addBox(-2.0F,0.0F,-2.0F,4.0F,12.0F,4.0F).texOffs(113,0).addBox(-2.5F,12.0F,-2.5F,5.0F,4.0F,5.0F),PartPose.offset(-6.0F,6.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(96,0).addBox(-2.0F,0.0F,-2.0F,4.0F,12.0F,4.0F).texOffs(134,0).addBox(-2.5F,12.0F,-2.5F,5.0F,4.0F,5.0F),PartPose.offset(6.0F,6.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(33,0).addBox(-3.0F,-4.0F,-3.5F,6.0F,5.0F,7.0F).texOffs(60,0).addBox(-2.5F,4.0F,-4.0F,5.0F,2.0F,4.0F),PartPose.offset(0.0F,6.0F,-3.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(155,0).addBox(-2.5F,0.0F,-2.5F,5.0F,7.0F,5.0F),PartPose.offset(-3.0F,17.0F,1.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(176,0).addBox(-2.5F,0.0F,-2.5F,5.0F,7.0F,5.0F),PartPose.offset(3.0F,17.0F,1.0F));
}
case "slag_troll" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-6.0F,0.0F,-3.0F,12.0F,12.0F,6.0F).texOffs(201,0).addBox(-6.0F,0.5F,1.5F,4.0F,2.0F,3.0F).texOffs(216,0).addBox(-2.0F,0.5F,1.5F,4.0F,2.0F,3.0F).texOffs(231,0).addBox(2.0F,0.5F,1.5F,4.0F,2.0F,3.0F).texOffs(0,19).addBox(-6.0F,-2.0F,1.0F,12.0F,3.0F,4.0F).texOffs(33,19).addBox(-4.0F,-3.0F,-4.0F,8.0F,3.0F,6.0F),PartPose.offset(0.0F,8.0F,1.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(83,0).addBox(-2.0F,0.0F,-2.0F,4.0F,12.0F,4.0F).texOffs(117,0).addBox(-2.5F,12.0F,-2.5F,5.0F,4.0F,5.0F),PartPose.offset(-7.0F,9.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(100,0).addBox(-2.0F,0.0F,-2.0F,4.0F,12.0F,4.0F).texOffs(138,0).addBox(-2.5F,12.0F,-2.5F,5.0F,4.0F,5.0F),PartPose.offset(7.0F,9.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(37,0).addBox(-3.0F,-4.0F,-3.5F,6.0F,5.0F,7.0F).texOffs(64,0).addBox(-2.5F,4.0F,-4.0F,5.0F,2.0F,4.0F),PartPose.offset(0.0F,9.0F,-3.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(159,0).addBox(-2.5F,0.0F,-2.5F,5.0F,4.0F,5.0F),PartPose.offset(-3.0F,20.0F,1.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(180,0).addBox(-2.5F,0.0F,-2.5F,5.0F,4.0F,5.0F),PartPose.offset(3.0F,20.0F,1.0F));
}
case "fen_goblin" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-3.0F,0.0F,-2.0F,6.0F,6.0F,4.0F).texOffs(133,0).addBox(-9.0F,-7.0F,-1.0F,1.0F,2.0F,2.0F).texOffs(160,0).addBox(8.0F,-7.0F,-1.0F,1.0F,2.0F,2.0F),PartPose.offset(0.0F,14.0F,1.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(61,0).addBox(-1.5F,0.0F,-1.5F,3.0F,8.0F,3.0F),PartPose.offset(-4.5F,15.0F,-1.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(74,0).addBox(-1.5F,0.0F,-1.5F,3.0F,8.0F,3.0F).texOffs(167,0).addBox(1.0F,-13.0F,-1.5F,1.0F,18.0F,1.0F).texOffs(172,0).addBox(0.5F,-16.0F,-2.0F,2.0F,4.0F,2.0F),PartPose.offset(4.5F,15.0F,-1.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(21,0).addBox(-3.0F,-6.0F,-3.0F,6.0F,6.0F,6.0F).texOffs(46,0).addBox(-2.0F,-4.0F,-6.0F,4.0F,2.0F,3.0F).texOffs(113,0).addBox(-6.0F,-4.0F,-1.0F,3.0F,2.0F,2.0F).texOffs(124,0).addBox(-7.5F,-5.0F,0.0F,2.0F,2.0F,2.0F).texOffs(140,0).addBox(3.0F,-4.0F,-1.0F,3.0F,2.0F,2.0F).texOffs(151,0).addBox(5.5F,-5.0F,0.0F,2.0F,2.0F,2.0F).texOffs(181,0).addBox(-2.0F,-8.0F,-0.5F,4.0F,2.0F,4.0F),PartPose.offset(0.0F,13.0F,-1.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(87,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F),PartPose.offset(-2.0F,20.0F,0.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(100,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F),PartPose.offset(2.0F,20.0F,0.0F));
}
case "tunnel_goblin" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-3.0F,0.0F,-2.0F,6.0F,8.0F,4.0F).texOffs(133,0).addBox(-9.0F,-7.0F,-1.0F,1.0F,2.0F,2.0F).texOffs(160,0).addBox(8.0F,-7.0F,-1.0F,1.0F,2.0F,2.0F).texOffs(194,0).addBox(-2.5F,-2.0F,1.0F,5.0F,6.0F,3.0F).texOffs(211,0).addBox(-3.0F,1.0F,3.5F,2.0F,2.0F,2.0F).texOffs(220,0).addBox(-1.0F,1.0F,3.5F,2.0F,2.0F,2.0F).texOffs(229,0).addBox(1.0F,1.0F,3.5F,2.0F,2.0F,2.0F),PartPose.offset(0.0F,12.0F,1.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(61,0).addBox(-1.5F,0.0F,-1.5F,3.0F,7.0F,3.0F),PartPose.offset(-4.5F,13.0F,-1.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(74,0).addBox(-1.5F,0.0F,-1.5F,3.0F,7.0F,3.0F).texOffs(167,0).addBox(0.0F,4.5F,-12.0F,3.0F,3.0F,10.0F),PartPose.offset(4.5F,13.0F,-1.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(21,0).addBox(-3.0F,-6.0F,-3.0F,6.0F,6.0F,6.0F).texOffs(46,0).addBox(-2.0F,-4.0F,-6.0F,4.0F,2.0F,3.0F).texOffs(113,0).addBox(-6.0F,-4.0F,-1.0F,3.0F,2.0F,2.0F).texOffs(124,0).addBox(-7.5F,-5.0F,0.0F,2.0F,2.0F,2.0F).texOffs(140,0).addBox(3.0F,-4.0F,-1.0F,3.0F,2.0F,2.0F).texOffs(151,0).addBox(5.5F,-5.0F,0.0F,2.0F,2.0F,2.0F),PartPose.offset(0.0F,11.0F,-1.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(87,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F),PartPose.offset(-2.0F,20.0F,0.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(100,0).addBox(-1.5F,0.0F,-1.5F,3.0F,4.0F,3.0F),PartPose.offset(2.0F,20.0F,0.0F));
}
case "ridge_kobold" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,0.0F,-2.0F,5.0F,5.0F,4.0F).texOffs(125,0).addBox(-2.0F,-9.0F,3.5F,1.0F,3.0F,1.0F).texOffs(143,0).addBox(1.0F,-9.0F,3.5F,1.0F,3.0F,1.0F),PartPose.offset(0.0F,14.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(76,0).addBox(-1.0F,0.0F,-1.0F,2.0F,7.0F,2.0F).texOffs(176,0).addBox(-2.0F,2.5F,-0.5F,3.0F,3.0F,3.0F),PartPose.offset(-3.5F,15.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(85,0).addBox(-1.0F,0.0F,-1.0F,2.0F,6.0F,2.0F).texOffs(148,0).addBox(0.5F,-9.0F,-0.5F,1.0F,13.0F,1.0F).texOffs(153,0).addBox(-4.0F,-10.0F,-0.5F,10.0F,2.0F,1.0F),PartPose.offset(3.5F,15.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(19,0).addBox(-2.5F,-5.0F,-2.5F,5.0F,5.0F,5.0F).texOffs(40,0).addBox(-1.5F,-4.0F,-9.0F,3.0F,3.0F,5.0F).texOffs(112,0).addBox(-2.0F,-6.0F,1.0F,1.0F,2.0F,5.0F).texOffs(130,0).addBox(1.0F,-6.0F,1.0F,1.0F,2.0F,5.0F),PartPose.offset(0.0F,14.0F,-1.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(94,0).addBox(-1.0F,0.0F,-1.0F,2.0F,5.0F,2.0F),PartPose.offset(-1.5F,19.0F,0.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(103,0).addBox(-1.0F,0.0F,-1.0F,2.0F,5.0F,2.0F),PartPose.offset(1.5F,19.0F,0.0F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(57,0).addBox(-1.0F,-1.0F,0.0F,2.0F,2.0F,7.0F),PartPose.offset(0.0F,17.0F,3.0F));
}
case "geode_kobold" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,0.0F,-2.0F,5.0F,7.0F,4.0F).texOffs(125,0).addBox(-2.0F,-9.0F,3.5F,1.0F,3.0F,1.0F).texOffs(143,0).addBox(1.0F,-9.0F,3.5F,1.0F,3.0F,1.0F),PartPose.offset(0.0F,11.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(76,0).addBox(-1.0F,0.0F,-1.0F,2.0F,7.0F,2.0F).texOffs(168,0).addBox(-1.5F,-2.0F,-2.5F,1.0F,7.0F,5.0F),PartPose.offset(-3.5F,12.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(85,0).addBox(-1.0F,0.0F,-1.0F,2.0F,5.0F,2.0F),PartPose.offset(3.5F,12.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(19,0).addBox(-2.5F,-5.0F,-2.5F,5.0F,5.0F,5.0F).texOffs(40,0).addBox(-1.5F,-4.0F,-9.0F,3.0F,3.0F,5.0F).texOffs(112,0).addBox(-2.0F,-6.0F,1.0F,1.0F,2.0F,5.0F).texOffs(130,0).addBox(1.0F,-6.0F,1.0F,1.0F,2.0F,5.0F).texOffs(148,0).addBox(-0.5F,-4.0F,1.5F,1.0F,3.0F,1.0F).texOffs(153,0).addBox(-0.5F,-4.0F,3.0F,1.0F,4.0F,1.0F).texOffs(158,0).addBox(-0.5F,-2.0F,4.5F,1.0F,3.0F,1.0F).texOffs(163,0).addBox(-0.5F,0.0F,6.0F,1.0F,2.0F,1.0F),PartPose.offset(0.0F,11.0F,-1.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(94,0).addBox(-1.0F,0.0F,-1.0F,2.0F,6.0F,2.0F),PartPose.offset(-1.5F,18.0F,0.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(103,0).addBox(-1.0F,0.0F,-1.0F,2.0F,6.0F,2.0F),PartPose.offset(1.5F,18.0F,0.0F));
root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(57,0).addBox(-1.0F,-1.0F,0.0F,2.0F,2.0F,7.0F),PartPose.offset(0.0F,16.0F,3.0F));
}
case "glimmer_fay" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-1.5F,-4.0F,-1.0F,3.0F,5.0F,2.0F),PartPose.offset(0.0F,13.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(28,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(-2.0F,10.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(33,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(2.0F,10.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(11,0).addBox(-2.0F,-3.0F,-2.0F,4.0F,3.0F,4.0F),PartPose.offset(0.0F,9.0F,0.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(38,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(-1.0F,14.0F,0.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(43,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(1.0F,14.0F,0.0F));
root.addOrReplaceChild("wing0",CubeListBuilder.create().texOffs(48,0).addBox(-7.0F,-7.0F,-0.5F,7.0F,7.0F,1.0F).texOffs(65,0).addBox(-5.0F,1.0F,-0.5F,5.0F,4.0F,1.0F),PartPose.offset(-1.0F,9.0F,1.0F));
root.addOrReplaceChild("wing1",CubeListBuilder.create().texOffs(78,0).addBox(0.0F,-7.0F,-0.5F,7.0F,7.0F,1.0F).texOffs(95,0).addBox(0.0F,1.0F,-0.5F,5.0F,4.0F,1.0F),PartPose.offset(1.0F,9.0F,1.0F));
}
case "prism_fay" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-1.5F,-4.0F,-1.0F,3.0F,5.0F,2.0F),PartPose.offset(0.0F,13.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(28,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(-2.0F,10.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(33,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(2.0F,10.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(11,0).addBox(-2.0F,-3.0F,-2.0F,4.0F,3.0F,4.0F).texOffs(78,0).addBox(1.5F,-5.0F,-1.0F,2.0F,2.0F,2.0F).texOffs(87,0).addBox(-0.2F,-5.0F,1.4F,2.0F,2.0F,2.0F).texOffs(96,0).addBox(-3.0F,-5.0F,0.5F,2.0F,2.0F,2.0F).texOffs(105,0).addBox(-3.0F,-5.0F,-2.5F,2.0F,2.0F,2.0F).texOffs(114,0).addBox(-0.2F,-5.0F,-3.4F,2.0F,2.0F,2.0F).texOffs(123,0).addBox(-1.5F,-6.0F,-1.5F,1.0F,3.0F,1.0F).texOffs(128,0).addBox(0.5F,-6.0F,-1.5F,1.0F,3.0F,1.0F),PartPose.offset(0.0F,9.0F,0.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(38,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(-1.0F,14.0F,0.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(43,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(1.0F,14.0F,0.0F));
root.addOrReplaceChild("wing0",CubeListBuilder.create().texOffs(48,0).addBox(-6.0F,-5.0F,-0.5F,6.0F,6.0F,1.0F),PartPose.offset(-1.0F,9.0F,1.0F));
root.addOrReplaceChild("wing1",CubeListBuilder.create().texOffs(63,0).addBox(0.0F,-5.0F,-0.5F,6.0F,6.0F,1.0F),PartPose.offset(1.0F,9.0F,1.0F));
}
case "marsh_fay" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-1.5F,-4.0F,-1.0F,3.0F,5.0F,2.0F),PartPose.offset(0.0F,13.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(28,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(-2.0F,10.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(33,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(2.0F,10.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(11,0).addBox(-2.0F,-3.0F,-2.0F,4.0F,3.0F,4.0F),PartPose.offset(0.0F,9.0F,0.0F));
root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(38,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(-1.0F,14.0F,0.0F));
root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(43,0).addBox(-0.5F,0.0F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(1.0F,14.0F,0.0F));
root.addOrReplaceChild("tendril0",CubeListBuilder.create().texOffs(116,0).addBox(-0.5F,-0.5F,0.0F,1.0F,1.0F,2.0F),PartPose.offset(0.0F,15.0F,2.0F));
root.addOrReplaceChild("tendril1",CubeListBuilder.create().texOffs(123,0).addBox(-0.5F,-0.5F,0.0F,1.0F,1.0F,2.0F),PartPose.offset(0.0F,16.0F,4.5F));
root.addOrReplaceChild("tendril2",CubeListBuilder.create().texOffs(130,0).addBox(-0.5F,-0.5F,0.0F,1.0F,1.0F,2.0F),PartPose.offset(0.0F,17.0F,7.0F));
root.addOrReplaceChild("wing0",CubeListBuilder.create().texOffs(48,0).addBox(-8.0F,-1.0F,-0.5F,8.0F,2.0F,1.0F).texOffs(67,0).addBox(-6.0F,2.0F,-0.5F,6.0F,2.0F,1.0F),PartPose.offset(-1.0F,9.0F,1.0F));
root.addOrReplaceChild("wing1",CubeListBuilder.create().texOffs(82,0).addBox(0.0F,-1.0F,-0.5F,8.0F,2.0F,1.0F).texOffs(101,0).addBox(0.0F,2.0F,-0.5F,6.0F,2.0F,1.0F),PartPose.offset(1.0F,9.0F,1.0F));
}
case "barrow_shade" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,-6.0F,-1.5F,5.0F,7.0F,3.0F).texOffs(17,0).addBox(-4.5F,-8.0F,-1.5F,9.0F,2.0F,3.0F),PartPose.offset(0.0F,12.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(170,0).addBox(-1.5F,0.0F,-1.5F,3.0F,9.0F,3.0F),PartPose.offset(-4.0F,6.0F,0.0F));
root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(188,0).addBox(-1.5F,0.0F,-1.5F,3.0F,7.0F,3.0F),PartPose.offset(4.0F,6.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(42,0).addBox(-2.0F,-4.0F,-2.0F,4.0F,4.0F,4.0F).texOffs(145,0).addBox(-3.0F,-4.0F,-3.0F,6.0F,5.0F,6.0F),PartPose.offset(0.0F,4.0F,0.0F));
root.addOrReplaceChild("tendril0",CubeListBuilder.create().texOffs(59,0).addBox(-2.5F,0.0F,-2.5F,5.0F,3.0F,5.0F).texOffs(183,0).addBox(-4.5F,3.0F,-0.5F,1.0F,6.0F,1.0F),PartPose.offset(0.0F,13.0F,0.0F));
root.addOrReplaceChild("tendril1",CubeListBuilder.create().texOffs(80,0).addBox(-2.1F,0.0F,-2.1F,4.2F,3.0F,4.2F).texOffs(201,0).addBox(3.5F,0.5F,-0.5F,1.0F,4.0F,1.0F),PartPose.offset(0.0F,15.5F,0.0F));
root.addOrReplaceChild("tendril2",CubeListBuilder.create().texOffs(101,0).addBox(-1.7F,0.0F,-1.7F,3.4F,3.0F,3.4F),PartPose.offset(0.0F,18.0F,0.0F));
root.addOrReplaceChild("tendril3",CubeListBuilder.create().texOffs(118,0).addBox(-1.3F,0.0F,-1.3F,2.6F,3.0F,2.6F),PartPose.offset(0.0F,20.5F,0.0F));
root.addOrReplaceChild("tendril4",CubeListBuilder.create().texOffs(131,0).addBox(-0.9F,0.0F,-0.9F,1.8F,3.0F,1.8F),PartPose.offset(0.0F,23.0F,0.0F));
root.addOrReplaceChild("tendril5",CubeListBuilder.create().texOffs(140,0).addBox(-0.5F,0.0F,-0.5F,1.0F,3.0F,1.0F),PartPose.offset(0.0F,25.5F,0.0F));
}
case "pale_wraith" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,-6.0F,-1.5F,5.0F,7.0F,3.0F).texOffs(17,0).addBox(-4.5F,-8.0F,-1.5F,9.0F,2.0F,3.0F).texOffs(175,0).addBox(-6.0F,-6.0F,-1.0F,12.0F,2.0F,2.0F),PartPose.offset(0.0F,12.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(42,0).addBox(-2.0F,-4.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,4.0F,0.0F));
root.addOrReplaceChild("tendril0",CubeListBuilder.create().texOffs(59,0).addBox(-2.5F,0.0F,-2.5F,5.0F,3.0F,5.0F).texOffs(145,0).addBox(3.0F,0.0F,-0.5F,1.0F,10.0F,1.0F),PartPose.offset(0.0F,13.0F,0.0F));
root.addOrReplaceChild("tendril1",CubeListBuilder.create().texOffs(80,0).addBox(-2.1F,0.0F,-2.1F,4.2F,3.0F,4.2F).texOffs(150,0).addBox(1.3F,-2.5F,1.2F,1.0F,9.0F,1.0F),PartPose.offset(0.0F,15.5F,0.0F));
root.addOrReplaceChild("tendril2",CubeListBuilder.create().texOffs(101,0).addBox(-1.7F,0.0F,-1.7F,3.4F,3.0F,3.4F).texOffs(155,0).addBox(-2.2F,-5.0F,1.2F,1.0F,13.0F,1.0F),PartPose.offset(0.0F,18.0F,0.0F));
root.addOrReplaceChild("tendril3",CubeListBuilder.create().texOffs(118,0).addBox(-1.3F,0.0F,-1.3F,2.6F,3.0F,2.6F).texOffs(160,0).addBox(-4.0F,-7.5F,-0.5F,1.0F,9.0F,1.0F),PartPose.offset(0.0F,20.5F,0.0F));
root.addOrReplaceChild("tendril4",CubeListBuilder.create().texOffs(131,0).addBox(-0.9F,0.0F,-0.9F,1.8F,3.0F,1.8F).texOffs(165,0).addBox(-2.3F,-10.0F,-2.2F,1.0F,7.0F,1.0F),PartPose.offset(0.0F,23.0F,0.0F));
root.addOrReplaceChild("tendril5",CubeListBuilder.create().texOffs(140,0).addBox(-0.5F,0.0F,-0.5F,1.0F,3.0F,1.0F).texOffs(170,0).addBox(1.2F,-12.5F,-2.2F,1.0F,12.0F,1.0F),PartPose.offset(0.0F,25.5F,0.0F));
}
case "cinder_shade" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,-6.0F,-1.5F,5.0F,7.0F,3.0F).texOffs(17,0).addBox(-4.5F,-8.0F,-1.5F,9.0F,2.0F,3.0F).texOffs(188,0).addBox(-4.5F,4.5F,-1.5F,1.0F,1.0F,1.0F).texOffs(193,0).addBox(-4.5F,6.5F,-1.5F,1.0F,1.0F,1.0F).texOffs(198,0).addBox(-4.5F,8.5F,-1.5F,1.0F,1.0F,1.0F).texOffs(203,0).addBox(-4.5F,10.5F,-1.5F,1.0F,1.0F,1.0F),PartPose.offset(0.0F,12.0F,0.0F));
root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(145,0).addBox(-1.0F,0.0F,-1.0F,2.0F,7.0F,2.0F).texOffs(154,0).addBox(-1.5F,6.5F,-1.5F,3.0F,3.0F,3.0F),PartPose.offset(-4.0F,6.0F,-1.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(42,0).addBox(-2.0F,-4.0F,-2.0F,4.0F,4.0F,4.0F).texOffs(167,0).addBox(-2.5F,-5.0F,-2.5F,5.0F,1.0F,5.0F),PartPose.offset(0.0F,4.0F,0.0F));
root.addOrReplaceChild("tendril0",CubeListBuilder.create().texOffs(59,0).addBox(-2.5F,0.0F,-2.5F,5.0F,3.0F,5.0F).texOffs(208,0).addBox(-2.5F,2.0F,0.5F,1.0F,5.0F,1.0F),PartPose.offset(0.0F,13.0F,0.0F));
root.addOrReplaceChild("tendril1",CubeListBuilder.create().texOffs(80,0).addBox(-2.1F,0.0F,-2.1F,4.2F,3.0F,4.2F).texOffs(213,0).addBox(1.5F,-0.5F,0.5F,1.0F,6.0F,1.0F),PartPose.offset(0.0F,15.5F,0.0F));
root.addOrReplaceChild("tendril2",CubeListBuilder.create().texOffs(101,0).addBox(-1.7F,0.0F,-1.7F,3.4F,3.0F,3.4F),PartPose.offset(0.0F,18.0F,0.0F));
root.addOrReplaceChild("tendril3",CubeListBuilder.create().texOffs(118,0).addBox(-1.3F,0.0F,-1.3F,2.6F,3.0F,2.6F),PartPose.offset(0.0F,20.5F,0.0F));
root.addOrReplaceChild("tendril4",CubeListBuilder.create().texOffs(131,0).addBox(-0.9F,0.0F,-0.9F,1.8F,3.0F,1.8F),PartPose.offset(0.0F,23.0F,0.0F));
root.addOrReplaceChild("tendril5",CubeListBuilder.create().texOffs(140,0).addBox(-0.5F,0.0F,-0.5F,1.0F,3.0F,1.0F),PartPose.offset(0.0F,25.5F,0.0F));
}
case "drowned_shade" -> {
root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-2.5F,-6.0F,-1.5F,5.0F,7.0F,3.0F).texOffs(17,0).addBox(-4.5F,-8.0F,-1.5F,9.0F,2.0F,3.0F).texOffs(199,0).addBox(-4.5F,-4.0F,-1.0F,9.0F,2.0F,4.0F),PartPose.offset(0.0F,12.0F,0.0F));
root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(42,0).addBox(-2.0F,-4.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,4.0F,0.0F));
root.addOrReplaceChild("tendril0",CubeListBuilder.create().texOffs(59,0).addBox(-2.5F,0.0F,-2.5F,5.0F,3.0F,5.0F).texOffs(145,0).addBox(-6.0F,-4.0F,0.5F,2.0F,14.0F,2.0F),PartPose.offset(0.0F,13.0F,0.0F));
root.addOrReplaceChild("tendril1",CubeListBuilder.create().texOffs(80,0).addBox(-2.1F,0.0F,-2.1F,4.2F,3.0F,4.2F).texOffs(154,0).addBox(-4.0F,-6.5F,0.5F,2.0F,13.0F,2.0F),PartPose.offset(0.0F,15.5F,0.0F));
root.addOrReplaceChild("tendril2",CubeListBuilder.create().texOffs(101,0).addBox(-1.7F,0.0F,-1.7F,3.4F,3.0F,3.4F).texOffs(163,0).addBox(-2.0F,-9.0F,0.5F,2.0F,9.0F,2.0F),PartPose.offset(0.0F,18.0F,0.0F));
root.addOrReplaceChild("tendril3",CubeListBuilder.create().texOffs(118,0).addBox(-1.3F,0.0F,-1.3F,2.6F,3.0F,2.6F).texOffs(172,0).addBox(0.0F,-11.5F,0.5F,2.0F,13.0F,2.0F),PartPose.offset(0.0F,20.5F,0.0F));
root.addOrReplaceChild("tendril4",CubeListBuilder.create().texOffs(131,0).addBox(-0.9F,0.0F,-0.9F,1.8F,3.0F,1.8F).texOffs(181,0).addBox(2.0F,-14.0F,0.5F,2.0F,8.0F,2.0F),PartPose.offset(0.0F,23.0F,0.0F));
root.addOrReplaceChild("tendril5",CubeListBuilder.create().texOffs(140,0).addBox(-0.5F,0.0F,-0.5F,1.0F,3.0F,1.0F).texOffs(190,0).addBox(4.0F,-16.5F,0.5F,2.0F,9.0F,2.0F),PartPose.offset(0.0F,25.5F,0.0F));
}
default -> { return null; }
}
return mesh;
}
}
