package tk.darrow.tribalpower.client;
import net.minecraft.client.model.geom.*;
import net.minecraft.client.model.geom.builders.*;
/** The bodies of the eight guardians, generated by tools/generate_guardians.py. Boxes are welded into the parts GuardianModel animates. */
public final class GeneratedGuardianLayers {
    private GeneratedGuardianLayers() {}
    public static LayerDefinition create(String id) {
        MeshDefinition mesh = new MeshDefinition(); var root = mesh.getRoot();
        switch (id) {
            case "slag_titan" -> {
                root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-8.0F,-16.0F,-5.0F,16.0F,16.0F,10.0F).texOffs(53,0).addBox(-6.0F,-19.0F,-4.0F,12.0F,4.0F,8.0F).texOffs(94,0).addBox(-11.0F,-20.0F,-4.0F,5.0F,5.0F,8.0F).texOffs(121,0).addBox(6.0F,-20.0F,-4.0F,5.0F,5.0F,8.0F),PartPose.offset(0.0F,16.0F,0.0F));
                root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(148,0).addBox(-4.0F,-6.0F,-4.0F,8.0F,6.0F,7.0F).texOffs(179,0).addBox(-5.0F,-8.0F,-4.0F,10.0F,3.0F,3.0F),PartPose.offset(0.0F,-3.0F,-1.0F));
                root.addOrReplaceChild("jaw",CubeListBuilder.create().texOffs(206,0).addBox(-3.0F,0.0F,-4.0F,6.0F,2.0F,5.0F),PartPose.offset(0.0F,3.0F,-1.0F));
                root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(229,0).addBox(-3.0F,0.0F,-3.0F,6.0F,14.0F,6.0F).texOffs(0,27).addBox(-4.0F,14.0F,-4.0F,8.0F,6.0F,8.0F),PartPose.offset(-11.0F,-1.0F,0.0F));
                root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(33,27).addBox(-3.0F,0.0F,-3.0F,6.0F,14.0F,6.0F).texOffs(58,27).addBox(-4.0F,14.0F,-4.0F,8.0F,6.0F,8.0F),PartPose.offset(11.0F,-1.0F,0.0F));
                root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(91,27).addBox(-3.0F,0.0F,-3.0F,6.0F,8.0F,7.0F),PartPose.offset(-4.0F,16.0F,0.0F));
                root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(118,27).addBox(-3.0F,0.0F,-3.0F,6.0F,8.0F,7.0F),PartPose.offset(4.0F,16.0F,0.0F));
            }
            case "bog_matriarch" -> {
                root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-9.0F,-8.0F,-10.0F,18.0F,9.0F,20.0F).texOffs(77,0).addBox(-6.0F,-12.0F,-6.0F,12.0F,4.0F,12.0F),PartPose.offset(0.0F,16.0F,0.0F));
                root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(126,0).addBox(-5.0F,-4.0F,-7.0F,10.0F,6.0F,8.0F).texOffs(194,0).addBox(-5.5F,-3.0F,-3.0F,1.0F,2.0F,2.0F).texOffs(201,0).addBox(4.5F,-3.0F,-3.0F,1.0F,2.0F,2.0F),PartPose.offset(0.0F,13.0F,-10.0F));
                root.addOrReplaceChild("jaw",CubeListBuilder.create().texOffs(163,0).addBox(-4.0F,0.0F,-7.0F,8.0F,2.0F,7.0F),PartPose.offset(0.0F,15.0F,-10.0F));
                root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(208,0).addBox(-1.5F,0.0F,-1.5F,3.0F,7.0F,3.0F).texOffs(221,0).addBox(-2.5F,6.0F,-2.5F,5.0F,2.0F,5.0F),PartPose.offset(-10.0F,17.0F,-7.0F));
                root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(242,0).addBox(-1.5F,0.0F,-1.5F,3.0F,7.0F,3.0F).texOffs(0,30).addBox(-2.5F,6.0F,-2.5F,5.0F,2.0F,5.0F),PartPose.offset(10.0F,17.0F,-7.0F));
                root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(21,30).addBox(-1.5F,0.0F,-1.5F,3.0F,7.0F,3.0F).texOffs(34,30).addBox(-2.5F,6.0F,-2.5F,5.0F,2.0F,5.0F),PartPose.offset(-10.0F,17.0F,0.0F));
                root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(55,30).addBox(-1.5F,0.0F,-1.5F,3.0F,7.0F,3.0F).texOffs(68,30).addBox(-2.5F,6.0F,-2.5F,5.0F,2.0F,5.0F),PartPose.offset(10.0F,17.0F,0.0F));
                root.addOrReplaceChild("leg4",CubeListBuilder.create().texOffs(89,30).addBox(-1.5F,0.0F,-1.5F,3.0F,7.0F,3.0F).texOffs(102,30).addBox(-2.5F,6.0F,-2.5F,5.0F,2.0F,5.0F),PartPose.offset(-10.0F,17.0F,7.0F));
                root.addOrReplaceChild("leg5",CubeListBuilder.create().texOffs(123,30).addBox(-1.5F,0.0F,-1.5F,3.0F,7.0F,3.0F).texOffs(136,30).addBox(-2.5F,6.0F,-2.5F,5.0F,2.0F,5.0F),PartPose.offset(10.0F,17.0F,7.0F));
                root.addOrReplaceChild("tendril0",CubeListBuilder.create().texOffs(157,30).addBox(-0.5F,-9.0F,-0.5F,1.0F,9.0F,1.0F).texOffs(162,30).addBox(-1.5F,-12.0F,-0.5F,3.0F,3.0F,1.0F),PartPose.offset(-6.0F,4.0F,-4.0F));
                root.addOrReplaceChild("tendril1",CubeListBuilder.create().texOffs(171,30).addBox(-0.5F,-9.0F,-0.5F,1.0F,9.0F,1.0F).texOffs(176,30).addBox(-1.5F,-12.0F,-0.5F,3.0F,3.0F,1.0F),PartPose.offset(-3.0F,4.0F,2.0F));
                root.addOrReplaceChild("tendril2",CubeListBuilder.create().texOffs(185,30).addBox(-0.5F,-9.0F,-0.5F,1.0F,9.0F,1.0F).texOffs(190,30).addBox(-1.5F,-12.0F,-0.5F,3.0F,3.0F,1.0F),PartPose.offset(0.0F,4.0F,-4.0F));
                root.addOrReplaceChild("tendril3",CubeListBuilder.create().texOffs(199,30).addBox(-0.5F,-9.0F,-0.5F,1.0F,9.0F,1.0F).texOffs(204,30).addBox(-1.5F,-12.0F,-0.5F,3.0F,3.0F,1.0F),PartPose.offset(3.0F,4.0F,2.0F));
                root.addOrReplaceChild("tendril4",CubeListBuilder.create().texOffs(213,30).addBox(-0.5F,-9.0F,-0.5F,1.0F,9.0F,1.0F).texOffs(218,30).addBox(-1.5F,-12.0F,-0.5F,3.0F,3.0F,1.0F),PartPose.offset(6.0F,4.0F,-4.0F));
            }
            case "cairn_wight" -> {
                root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-5.0F,-16.0F,-4.0F,10.0F,16.0F,8.0F).texOffs(37,0).addBox(-7.0F,-13.0F,-5.0F,14.0F,4.0F,10.0F).texOffs(86,0).addBox(-6.0F,-6.0F,-5.0F,12.0F,4.0F,10.0F).texOffs(131,0).addBox(-8.0F,-18.0F,-5.0F,16.0F,4.0F,10.0F),PartPose.offset(0.0F,14.0F,0.0F));
                root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(184,0).addBox(-4.0F,-8.0F,-4.0F,8.0F,8.0F,8.0F).texOffs(217,0).addBox(-6.0F,-13.0F,-1.0F,3.0F,7.0F,3.0F).texOffs(230,0).addBox(3.0F,-13.0F,-1.0F,3.0F,7.0F,3.0F).texOffs(0,25).addBox(-5.0F,-9.0F,-5.0F,10.0F,3.0F,10.0F),PartPose.offset(0.0F,-4.0F,0.0F));
                root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(41,25).addBox(-2.0F,0.0F,-2.0F,4.0F,16.0F,4.0F).texOffs(58,25).addBox(-3.0F,16.0F,-3.0F,6.0F,4.0F,6.0F),PartPose.offset(-9.0F,-2.0F,0.0F));
                root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(83,25).addBox(-2.0F,0.0F,-2.0F,4.0F,16.0F,4.0F).texOffs(100,25).addBox(-3.0F,16.0F,-3.0F,6.0F,4.0F,6.0F),PartPose.offset(9.0F,-2.0F,0.0F));
                root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(125,25).addBox(-2.0F,0.0F,-2.0F,4.0F,10.0F,4.0F),PartPose.offset(-3.0F,14.0F,0.0F));
                root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(142,25).addBox(-2.0F,0.0F,-2.0F,4.0F,10.0F,4.0F),PartPose.offset(3.0F,14.0F,0.0F));
                root.addOrReplaceChild("tendril0",CubeListBuilder.create().texOffs(159,25).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(9.0F,4.0F,0.0F));
                root.addOrReplaceChild("tendril1",CubeListBuilder.create().texOffs(176,25).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,9.0F,9.0F));
                root.addOrReplaceChild("tendril2",CubeListBuilder.create().texOffs(193,25).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(-9.0F,4.0F,0.0F));
                root.addOrReplaceChild("tendril3",CubeListBuilder.create().texOffs(210,25).addBox(-2.0F,-2.0F,-2.0F,4.0F,4.0F,4.0F),PartPose.offset(0.0F,9.0F,-9.0F));
            }
            case "prism_serpent" -> {
                root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(0,0).addBox(-5.0F,-4.0F,-8.0F,10.0F,7.0F,9.0F).texOffs(72,0).addBox(-5.0F,-8.0F,-3.0F,2.0F,5.0F,2.0F).texOffs(81,0).addBox(3.0F,-8.0F,-3.0F,2.0F,5.0F,2.0F),PartPose.offset(0.0F,10.0F,-24.0F));
                root.addOrReplaceChild("jaw",CubeListBuilder.create().texOffs(39,0).addBox(-4.0F,0.0F,-8.0F,8.0F,2.0F,8.0F),PartPose.offset(0.0F,13.0F,-24.0F));
                root.addOrReplaceChild("seg0",CubeListBuilder.create().texOffs(90,0).addBox(-4.0F,-4.0F,-3.0F,8.0F,8.0F,6.0F).texOffs(119,0).addBox(-0.5F,-8.0F,-2.0F,1.0F,4.0F,4.0F),PartPose.offset(0.0F,12.0F,-20.0F));
                root.addOrReplaceChild("seg1",CubeListBuilder.create().texOffs(130,0).addBox(-4.0F,-4.0F,-3.0F,8.0F,8.0F,6.0F),PartPose.offset(0.0F,12.0F,-14.0F));
                root.addOrReplaceChild("seg2",CubeListBuilder.create().texOffs(159,0).addBox(-3.5F,-3.5F,-3.0F,7.0F,7.0F,6.0F).texOffs(186,0).addBox(-0.5F,-7.5F,-2.0F,1.0F,4.0F,4.0F),PartPose.offset(0.0F,13.0F,-8.0F));
                root.addOrReplaceChild("seg3",CubeListBuilder.create().texOffs(197,0).addBox(-3.5F,-3.5F,-3.0F,7.0F,7.0F,6.0F),PartPose.offset(0.0F,16.0F,-2.0F));
                root.addOrReplaceChild("seg4",CubeListBuilder.create().texOffs(224,0).addBox(-3.0F,-3.0F,-3.0F,6.0F,6.0F,6.0F).texOffs(0,17).addBox(-0.5F,-7.0F,-2.0F,1.0F,4.0F,4.0F),PartPose.offset(0.0F,17.0F,4.0F));
                root.addOrReplaceChild("seg5",CubeListBuilder.create().texOffs(11,17).addBox(-3.0F,-3.0F,-3.0F,6.0F,6.0F,6.0F),PartPose.offset(0.0F,17.0F,10.0F));
                root.addOrReplaceChild("seg6",CubeListBuilder.create().texOffs(36,17).addBox(-2.5F,-2.5F,-3.0F,5.0F,5.0F,6.0F).texOffs(59,17).addBox(-0.5F,-6.5F,-2.0F,1.0F,4.0F,4.0F),PartPose.offset(0.0F,18.0F,16.0F));
                root.addOrReplaceChild("seg7",CubeListBuilder.create().texOffs(70,17).addBox(-2.5F,-2.5F,-3.0F,5.0F,5.0F,6.0F),PartPose.offset(0.0F,18.0F,22.0F));
                root.addOrReplaceChild("seg8",CubeListBuilder.create().texOffs(93,17).addBox(-2.0F,-2.0F,-3.0F,4.0F,4.0F,6.0F).texOffs(114,17).addBox(-0.5F,-6.0F,-2.0F,1.0F,4.0F,4.0F),PartPose.offset(0.0F,19.0F,28.0F));
                root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(125,17).addBox(-1.0F,-1.0F,0.0F,2.0F,2.0F,8.0F),PartPose.offset(0.0F,21.0F,34.0F));
            }
            case "vault_sentinel" -> {
                root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-7.0F,-16.0F,-4.0F,14.0F,16.0F,8.0F).texOffs(45,0).addBox(-10.0F,-17.0F,-4.0F,4.0F,5.0F,8.0F).texOffs(70,0).addBox(6.0F,-17.0F,-4.0F,4.0F,5.0F,8.0F).texOffs(95,0).addBox(-7.5F,-4.0F,-4.5F,15.0F,3.0F,9.0F),PartPose.offset(0.0F,15.0F,0.0F));
                root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(144,0).addBox(-3.5F,-7.0F,-3.5F,7.0F,7.0F,7.0F).texOffs(173,0).addBox(-4.0F,-5.0F,-4.5F,8.0F,3.0F,1.0F).texOffs(192,0).addBox(-0.5F,-11.0F,-3.0F,1.0F,4.0F,7.0F),PartPose.offset(0.0F,-1.0F,0.0F));
                root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(209,0).addBox(-2.5F,0.0F,-2.5F,5.0F,14.0F,5.0F).texOffs(230,0).addBox(-4.0F,4.0F,-6.0F,2.0F,12.0F,10.0F),PartPose.offset(-9.0F,-1.0F,0.0F));
                root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(0,25).addBox(-2.5F,0.0F,-2.5F,5.0F,14.0F,5.0F).texOffs(21,25).addBox(-3.0F,12.0F,-3.0F,6.0F,4.0F,6.0F),PartPose.offset(9.0F,-1.0F,0.0F));
                root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(46,25).addBox(-2.5F,0.0F,-2.5F,5.0F,9.0F,5.0F),PartPose.offset(-3.5F,15.0F,0.0F));
                root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(67,25).addBox(-2.5F,0.0F,-2.5F,5.0F,9.0F,5.0F),PartPose.offset(3.5F,15.0F,0.0F));
                root.addOrReplaceChild("tendril0",CubeListBuilder.create().texOffs(88,25).addBox(-1.5F,-1.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(7.0F,-12.0F,0.0F));
                root.addOrReplaceChild("tendril1",CubeListBuilder.create().texOffs(101,25).addBox(-1.5F,-1.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(0.0F,-12.0F,7.0F));
                root.addOrReplaceChild("tendril2",CubeListBuilder.create().texOffs(114,25).addBox(-1.5F,-1.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(-7.0F,-12.0F,0.0F));
                root.addOrReplaceChild("tendril3",CubeListBuilder.create().texOffs(127,25).addBox(-1.5F,-1.0F,-1.5F,3.0F,2.0F,3.0F),PartPose.offset(0.0F,-12.0F,-7.0F));
            }
            case "tide_drummer" -> {
                root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-8.0F,-12.0F,-6.0F,16.0F,12.0F,12.0F).texOffs(57,0).addBox(-9.0F,-15.0F,-7.0F,18.0F,4.0F,14.0F).texOffs(122,0).addBox(-6.0F,-8.0F,-9.0F,12.0F,8.0F,3.0F).texOffs(153,0).addBox(-3.0F,-14.0F,-10.0F,6.0F,6.0F,5.0F),PartPose.offset(0.0F,18.0F,0.0F));
                root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(176,0).addBox(-4.5F,-6.0F,-8.0F,9.0F,6.0F,8.0F).texOffs(240,0).addBox(-6.0F,-9.0F,-3.0F,1.5F,5.0F,6.0F).texOffs(0,25).addBox(4.5F,-9.0F,-3.0F,1.5F,5.0F,6.0F),PartPose.offset(0.0F,4.0F,-10.0F));
                root.addOrReplaceChild("jaw",CubeListBuilder.create().texOffs(211,0).addBox(-3.5F,0.0F,-8.0F,7.0F,2.0F,7.0F),PartPose.offset(0.0F,4.0F,-10.0F));
                root.addOrReplaceChild("arm0",CubeListBuilder.create().texOffs(17,25).addBox(-2.0F,0.0F,-2.0F,4.0F,11.0F,4.0F).texOffs(34,25).addBox(-3.0F,10.0F,-3.0F,6.0F,4.0F,6.0F),PartPose.offset(-9.0F,7.0F,-4.0F));
                root.addOrReplaceChild("arm1",CubeListBuilder.create().texOffs(59,25).addBox(-2.0F,0.0F,-2.0F,4.0F,11.0F,4.0F).texOffs(76,25).addBox(-3.0F,10.0F,-3.0F,6.0F,4.0F,6.0F),PartPose.offset(9.0F,7.0F,-4.0F));
                root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(101,25).addBox(-2.5F,0.0F,-2.5F,5.0F,6.0F,5.0F),PartPose.offset(-4.0F,18.0F,3.0F));
                root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(122,25).addBox(-2.5F,0.0F,-2.5F,5.0F,6.0F,5.0F),PartPose.offset(4.0F,18.0F,3.0F));
                root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(143,25).addBox(-1.0F,-2.0F,0.0F,2.0F,4.0F,9.0F).texOffs(166,25).addBox(-0.5F,-6.0F,5.0F,1.0F,8.0F,4.0F),PartPose.offset(0.0F,14.0F,6.0F));
            }
            case "stampede_spirit" -> {
                root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-6.0F,-8.0F,-11.0F,12.0F,12.0F,22.0F).texOffs(69,0).addBox(-7.0F,-11.0F,-12.0F,14.0F,5.0F,10.0F),PartPose.offset(0.0F,12.0F,0.0F));
                root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(118,0).addBox(-4.0F,-5.0F,-8.0F,8.0F,8.0F,8.0F).texOffs(151,0).addBox(-3.0F,-1.0F,-12.0F,6.0F,4.0F,4.0F).texOffs(172,0).addBox(-8.0F,-8.0F,-3.0F,5.0F,2.0F,2.0F).texOffs(187,0).addBox(3.0F,-8.0F,-3.0F,5.0F,2.0F,2.0F).texOffs(202,0).addBox(-8.0F,-12.0F,-3.0F,2.0F,5.0F,2.0F).texOffs(211,0).addBox(6.0F,-12.0F,-3.0F,2.0F,5.0F,2.0F),PartPose.offset(0.0F,6.0F,-12.0F));
                root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(220,0).addBox(-2.0F,0.0F,-2.0F,4.0F,12.0F,4.0F),PartPose.offset(-4.0F,12.0F,-8.0F));
                root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(237,0).addBox(-2.0F,0.0F,-2.0F,4.0F,12.0F,4.0F),PartPose.offset(4.0F,12.0F,-8.0F));
                root.addOrReplaceChild("leg2",CubeListBuilder.create().texOffs(0,35).addBox(-2.0F,0.0F,-2.0F,4.0F,12.0F,4.0F),PartPose.offset(-4.0F,12.0F,8.0F));
                root.addOrReplaceChild("leg3",CubeListBuilder.create().texOffs(17,35).addBox(-2.0F,0.0F,-2.0F,4.0F,12.0F,4.0F),PartPose.offset(4.0F,12.0F,8.0F));
                root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(34,35).addBox(-1.0F,-1.0F,0.0F,2.0F,2.0F,8.0F),PartPose.offset(0.0F,6.0F,11.0F));
                root.addOrReplaceChild("tendril0",CubeListBuilder.create().texOffs(55,35).addBox(-1.5F,-1.5F,-1.5F,3.0F,3.0F,3.0F),PartPose.offset(-8.0F,2.0F,9.0F));
                root.addOrReplaceChild("tendril1",CubeListBuilder.create().texOffs(68,35).addBox(-1.5F,-1.5F,-1.5F,3.0F,3.0F,3.0F),PartPose.offset(-3.0F,5.0F,9.0F));
                root.addOrReplaceChild("tendril2",CubeListBuilder.create().texOffs(81,35).addBox(-1.5F,-1.5F,-1.5F,3.0F,3.0F,3.0F),PartPose.offset(2.0F,2.0F,9.0F));
                root.addOrReplaceChild("tendril3",CubeListBuilder.create().texOffs(94,35).addBox(-1.5F,-1.5F,-1.5F,3.0F,3.0F,3.0F),PartPose.offset(7.0F,5.0F,9.0F));
            }
            case "storm_roc" -> {
                root.addOrReplaceChild("body",CubeListBuilder.create().texOffs(0,0).addBox(-4.0F,-4.0F,-9.0F,8.0F,8.0F,18.0F).texOffs(53,0).addBox(-5.0F,-3.0F,-8.0F,10.0F,6.0F,6.0F),PartPose.offset(0.0F,8.0F,0.0F));
                root.addOrReplaceChild("head",CubeListBuilder.create().texOffs(86,0).addBox(-3.0F,-3.0F,-6.0F,6.0F,6.0F,7.0F).texOffs(113,0).addBox(-1.5F,-1.0F,-11.0F,3.0F,3.0F,5.0F).texOffs(130,0).addBox(-1.0F,1.0F,-12.0F,2.0F,2.0F,2.0F).texOffs(139,0).addBox(-0.5F,-7.0F,-3.0F,1.0F,4.0F,5.0F),PartPose.offset(0.0F,6.0F,-10.0F));
                root.addOrReplaceChild("wing0",CubeListBuilder.create().texOffs(152,0).addBox(-24.0F,-1.0F,-5.0F,24.0F,2.0F,12.0F).texOffs(225,0).addBox(-30.0F,-1.0F,-3.0F,6.0F,1.0F,8.0F),PartPose.offset(-4.0F,6.0F,0.0F));
                root.addOrReplaceChild("wing1",CubeListBuilder.create().texOffs(0,27).addBox(0.0F,-1.0F,-5.0F,24.0F,2.0F,12.0F).texOffs(73,27).addBox(24.0F,-1.0F,-3.0F,6.0F,1.0F,8.0F),PartPose.offset(4.0F,6.0F,0.0F));
                root.addOrReplaceChild("tail",CubeListBuilder.create().texOffs(102,27).addBox(-3.0F,-1.0F,0.0F,6.0F,2.0F,10.0F).texOffs(135,27).addBox(-1.0F,-3.0F,8.0F,2.0F,5.0F,4.0F),PartPose.offset(0.0F,8.0F,9.0F));
                root.addOrReplaceChild("leg0",CubeListBuilder.create().texOffs(148,27).addBox(-1.0F,0.0F,-1.0F,2.0F,6.0F,2.0F).texOffs(166,27).addBox(-2.0F,5.0F,-2.0F,4.0F,1.0F,4.0F),PartPose.offset(-2.0F,12.0F,2.0F));
                root.addOrReplaceChild("leg1",CubeListBuilder.create().texOffs(157,27).addBox(-1.0F,0.0F,-1.0F,2.0F,6.0F,2.0F).texOffs(183,27).addBox(-2.0F,5.0F,-2.0F,4.0F,1.0F,4.0F),PartPose.offset(2.0F,12.0F,2.0F));
            }
            default -> throw new IllegalArgumentException("No guardian rig: " + id);
        }
        return LayerDefinition.create(mesh, 256, 256);
    }
}
