package tk.darrow.tribalpower.entity;

import java.util.Set;

/**
 * Which body each creature is drawn with.
 *
 * <p>Every creature's rig is generated by {@code tools/creature_gen} into GeneratedMarchLayers -- the March
 * roster and, since the older beasts were rebuilt there too, the creatures that predate it -- and the client
 * prefers it over the hand-built Blender export. A creature with no rig used to throw on the render thread the
 * moment the game loaded, which nothing on the server could see, so the mapping lives here, in common code,
 * where a test can hold it to the roster.
 *
 * <p>The 3.9 creatures once borrowed the nearest existing body (six of them walked about as the Lantern Fox);
 * each has its own now, so nothing is aliased any more.
 */
public final class CreatureRigs {
    /** Every id the exporter has actually built geometry for. */
    public static final Set<String> BUILT = Set.of(
            "dawn_stag", "lantern_fox", "mossback", "ashbound", "rootbound", "reed_stalker", "shardback",
            "hollow_sentinel", "storm_moth", "cinder_imp", "mourning_bell", "rift_hound", "echo_weaver",
            "ash_hopper", "ridge_grazer", "glimmer_moth", "deep_lurker", "pale_stalker", "dust_flitter",
            "veil_drifter", "crag_bounder", "stone_grub", "gloom_crawler", "ember_drifter", "magma_creeper",
            "tuftback", "longshank", "palewing", "burrow_gnasher", "cragcoat", "bouldersnout", "updrifter",
            "scree_lurcher", "prism_grazer", "shardmoth", "glowgrub", "facet_stalker", "driftpelt",
            "frost_strider", "snowveil", "rime_crawler", "cinderhide", "ashmoth", "slaglump", "emberjaw",
            "marsh_hopper", "fen_strider", "bog_floater", "reed_coil", "chime_grazer", "glass_flitter",
            "geode_grub", "shard_stalker", "silt_glider", "pale_drifter", "shoal_darter", "brine_lurker",
            "hearth_warden", "grove_elder", "frostpine_sentinel", "snagwalker", "weeping_warden",
            "bellcap_elder", "stiltwood", "colossus_warden", "crag_troll", "rime_troll", "slag_troll",
            "fen_goblin", "tunnel_goblin", "ridge_kobold", "geode_kobold", "glimmer_fay", "prism_fay",
            "marsh_fay", "barrow_shade", "pale_wraith", "cinder_shade", "drowned_shade");

    private CreatureRigs() {}

    /** The rig a creature is drawn with: every creature has its own now. */
    public static String rig(String id) {
        return id;
    }
}
