package tk.darrow.tribalpower.entity;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.world.entity.EntityType;
public enum CreatureProfile {
    DAWN_STAG("dawn_stag", true, false, 24, 0.25, 0, 1, 0.8F, 1.625F, "none", "dawn_velvet", 0x405d55, 0x7effcb),
    LANTERN_FOX("lantern_fox", true, false, 14, 0.3, 0, 0, 0.8F, 0.875F, "none", "lantern_down", 0x603e68, 0x7affe1),
    MOSSBACK("mossback", true, false, 30, 0.15, 0, 6, 1.3F, 1.0F, "none", "mossback_scale", 0x344f44, 0xc4ffad),
    ASHBOUND("ashbound", false, false, 24, 0.23, 4, 2, 0.8F, 1.438F, "ember", "ember_heart", 0x473c42, 0xffb46c),
    ROOTBOUND("rootbound", false, false, 38, 0.18, 6, 5, 0.8F, 1.438F, "root", "knotted_root", 0x494735, 0xb1e0a0),
    REED_STALKER("reed_stalker", false, false, 22, 0.3, 4, 1, 0.8F, 1.188F, "venom", "reed_fang", 0x294b4a, 0xa2e8b9),
    SHARDBACK("shardback", false, false, 36, 0.18, 5, 8, 1.3F, 1.188F, "shove", "prism_carapace", 0x455272, 0x87fff0),
    HOLLOW_SENTINEL("hollow_sentinel", false, false, 44, 0.2, 6, 6, 0.8F, 1.812F, "weaken", "sentinel_sigil", 0x313f53, 0xbafbe8),
    STORM_MOTH("storm_moth", false, true, 20, 0.24, 4, 0, 0.65F, 1.438F, "gust", "storm_wing", 0x42415e, 0xadffff),
    CINDER_IMP("cinder_imp", false, false, 18, 0.27, 4, 1, 0.8F, 1.25F, "bolt", "cinder_knot", 0x563943, 0xffcb89),
    MOURNING_BELL("mourning_bell", false, true, 28, 0.2, 4, 3, 0.65F, 1.312F, "chill", "bell_fragment", 0x364760, 0xb6e4ff),
    RIFT_HOUND("rift_hound", false, false, 28, 0.34, 5, 2, 0.8F, 0.875F, "hound", "rift_tooth", 0x323848, 0xb5a3ff),
    ECHO_WEAVER("echo_weaver", false, false, 26, 0.25, 4, 3, 1.3F, 0.688F, "weave", "echo_silk", 0x463b59, 0xe4baff),
    // 3.9: the March had three animals to ten hostiles, so most of it stood empty, and nothing at all
    // lived in its caves. Three grazers for the open ground and two things that hunt in the dark.
    ASH_HOPPER("ash_hopper", true, false, 12, 0.32, 0, 0, 0.7F, 0.75F, "none", "ash_tuft", 0x6b5a4f, 0xffad6b),
    RIDGE_GRAZER("ridge_grazer", true, false, 26, 0.22, 0, 2, 1.0F, 1.25F, "none", "grazer_wool", 0x8c9099, 0xdfe9f5),
    GLIMMER_MOTH("glimmer_moth", true, true, 10, 0.28, 0, 0, 0.6F, 0.7F, "none", "glimmer_dust", 0x4a5c72, 0xbfe9ff),
    DEEP_LURKER("deep_lurker", false, false, 32, 0.26, 5, 3, 0.9F, 1.5F, "hound", "lurker_claw", 0x2b2f38, 0x8fd6c4),
    PALE_STALKER("pale_stalker", false, false, 24, 0.31, 4, 1, 0.8F, 1.75F, "weaken", "pale_fang", 0x3a3f4a, 0xe8eef6),
    // Filling the niches: every biome wanted something in the air, something on the ground, something
    // in its caves, and something that can stand near lava. "ember" and "bolt" are what make an entity
    // fire immune (see CreatureEntities), which is why the lava dwellers carry them.
    DUST_FLITTER("dust_flitter", true, true, 8, 0.30, 0, 0, 0.6F, 0.6F, "none", "flitter_wing", 0x7a6a55, 0xffe2a8),
    VEIL_DRIFTER("veil_drifter", false, true, 18, 0.26, 3, 1, 0.7F, 1.1F, "gust", "veil_tatter", 0x46506b, 0xcfe0ff),
    CRAG_BOUNDER("crag_bounder", true, false, 20, 0.27, 0, 2, 0.9F, 1.1F, "none", "bounder_horn", 0x7d8490, 0xe6eef7),
    STONE_GRUB("stone_grub", true, false, 10, 0.14, 0, 4, 0.7F, 0.5F, "none", "grub_husk", 0x5c5a52, 0xb8c6a8),
    GLOOM_CRAWLER("gloom_crawler", false, false, 22, 0.28, 4, 2, 1.1F, 0.7F, "weave", "gloom_silk", 0x24262e, 0x9fb0c8),
    EMBER_DRIFTER("ember_drifter", true, true, 12, 0.24, 0, 0, 0.6F, 0.8F, "ember", "ember_mote", 0x5a3326, 0xffc178),
    MAGMA_CREEPER("magma_creeper", true, false, 22, 0.18, 0, 6, 0.9F, 0.7F, "ember", "magma_scale", 0x4a2a20, 0xff9a4d),
    // 4.0: the March gets its own bestiary. Thirty-two beasts built from fourteen body plans, the
    // folk that the stories put in each biome -- ents of every tree, trolls, goblins, kobolds,
    // fairies and the dead -- and one boss. Generated by tools/creature_gen; the plans that place
    // these boxes are the same ones that paint their skins.
    TUFTBACK("tuftback",true,false,26,0.14,0,5,1.1F,0.9F,"none","tuft_wool",0x1e261c,0xc0d6a0),
    LONGSHANK("longshank",true,false,22,0.28,0,1,0.9F,1.6F,"none","shank_sinew",0x2e281e,0xecdcaa),
    PALEWING("palewing",true,true,10,0.28,0,0,0.7F,0.7F,"none","pale_down",0x2c3036,0xe8f0fa),
    BURROW_GNASHER("burrow_gnasher",false,false,23,0.22,4,3,1.1F,0.7F,"venom","gnasher_tooth",0x22242c,0xd4e0f0),
    CRAGCOAT("cragcoat",true,false,30,0.16,0,7,1.2F,0.9F,"none","crag_fleece",0x34322c,0xf0ecde),
    BOULDERSNOUT("bouldersnout",true,false,30,0.2,0,4,1.3F,1.1F,"none","boulder_tusk",0x22242c,0xd4e0f0),
    UPDRIFTER("updrifter",true,true,12,0.22,0,0,0.8F,1.0F,"none","drift_bladder",0x2c3036,0xe8f0fa),
    SCREE_LURCHER("scree_lurcher",false,false,32,0.26,6,3,0.9F,1.9F,"shove","scree_knuckle",0x201c1c,0xcac0b8),
    PRISM_GRAZER("prism_grazer",true,false,24,0.22,0,3,1.0F,1.2F,"none","prism_crest",0x283644,0xe0f4ff),
    SHARDMOTH("shardmoth",true,true,10,0.28,0,0,0.7F,0.7F,"none","shard_wing",0x221c30,0xd4c6f2),
    GLOWGRUB("glowgrub",true,false,18,0.24,0,1,0.8F,0.7F,"none","glow_husk",0x142a28,0xaae0ce),
    FACET_STALKER("facet_stalker",false,false,21,0.3,5,1,1.0F,1.2F,"venom","facet_barb",0x22242c,0xd4e0f0),
    DRIFTPELT("driftpelt",true,false,26,0.14,0,5,1.1F,0.9F,"none","drift_pelt",0x2c3036,0xe8f0fa),
    FROST_STRIDER("frost_strider",true,false,22,0.28,0,1,0.9F,1.6F,"none","frost_hoof",0x283644,0xe0f4ff),
    SNOWVEIL("snowveil",true,true,12,0.22,0,0,0.8F,1.0F,"none","snow_veil",0x2c3036,0xe8f0fa),
    RIME_CRAWLER("rime_crawler",false,false,23,0.22,4,3,1.1F,0.7F,"venom","rime_mandible",0x283644,0xe0f4ff),
    CINDERHIDE("cinderhide",true,false,30,0.16,0,7,1.2F,0.9F,"ember","cinder_plate",0x301a14,0xfcc478),
    ASHMOTH("ashmoth",true,true,10,0.28,0,0,0.7F,0.7F,"none","ash_wing",0x201c1c,0xcac0b8),
    SLAGLUMP("slaglump",true,false,26,0.14,0,5,1.1F,0.9F,"ember","slag_curd",0x302016,0xf0c48c),
    EMBERJAW("emberjaw",false,false,32,0.26,6,3,0.9F,1.9F,"shove","ember_fang",0x301a14,0xfcc478),
    MARSH_HOPPER("marsh_hopper",true,false,12,0.3,0,0,0.7F,0.8F,"none","marsh_foot",0x1e261c,0xc0d6a0),
    FEN_STRIDER("fen_strider",true,false,22,0.28,0,1,0.9F,1.6F,"none","fen_hoof",0x142a28,0xaae0ce),
    BOG_FLOATER("bog_floater",true,true,12,0.22,0,0,0.8F,1.0F,"none","bog_bladder",0x1e261c,0xc0d6a0),
    REED_COIL("reed_coil",false,false,30,0.14,5,6,1.0F,0.9F,"shove","reed_whorl",0x142a28,0xaae0ce),
    CHIME_GRAZER("chime_grazer",true,false,24,0.22,0,3,1.0F,1.2F,"none","chime_crest",0x221c30,0xd4c6f2),
    GLASS_FLITTER("glass_flitter",true,true,10,0.28,0,0,0.7F,0.7F,"none","glass_wing",0x283644,0xe0f4ff),
    GEODE_GRUB("geode_grub",true,false,26,0.14,0,5,1.1F,0.9F,"none","geode_husk",0x221c30,0xd4c6f2),
    SHARD_STALKER("shard_stalker",false,false,21,0.3,5,1,1.0F,1.2F,"venom","shard_barb",0x221c30,0xd4c6f2),
    SILT_GLIDER("silt_glider",true,false,14,0.26,0,1,0.8F,0.7F,"none","silt_fin",0x122632,0xa0d6ec),
    PALE_DRIFTER("pale_drifter",true,false,12,0.22,0,0,0.8F,1.0F,"none","pale_streamer",0x122632,0xa0d6ec),
    SHOAL_DARTER("shoal_darter",true,false,14,0.26,0,1,0.8F,0.7F,"none","shoal_scale",0x142a28,0xaae0ce),
    BRINE_LURKER("brine_lurker",false,false,21,0.24,4,1,0.8F,0.7F,"venom","brine_fang",0x122632,0xa0d6ec),
    HEARTH_WARDEN("hearth_warden",true,false,48,0.16,0,8,1.4F,2.8F,"none","hearth_bark",0x221a12,0x7eb054),
    GROVE_ELDER("grove_elder",true,false,48,0.16,0,8,1.4F,2.8F,"none","elder_bark",0x1e1a16,0x769e50),
    FROSTPINE_SENTINEL("frostpine_sentinel",true,false,48,0.16,0,8,1.4F,2.8F,"none","frostpine_bark",0x261614,0xc4e6fa),
    SNAGWALKER("snagwalker",true,false,48,0.16,0,8,1.4F,2.8F,"none","cinder_bark",0x100e0e,0xfcb048),
    WEEPING_WARDEN("weeping_warden",true,false,48,0.16,0,8,1.4F,2.8F,"none","weeping_knot",0x262a1c,0xbce088),
    BELLCAP_ELDER("bellcap_elder",true,false,48,0.16,0,8,1.4F,2.8F,"none","bellcap_spore",0x22162a,0xd69ef4),
    STILTWOOD("stiltwood",true,false,48,0.16,0,8,1.4F,2.8F,"none","stilt_root",0x162628,0x96e6e2),
    COLOSSUS_WARDEN("colossus_warden",false,false,260,0.16,12,14,3.4F,7.0F,"root","heartwood_core",0x262a1c,0xbce088),
    CRAG_TROLL("crag_troll",false,false,69,0.22,9,6,1.6F,2.6F,"shove","troll_hide",0x22242c,0xd4e0f0),
    RIME_TROLL("rime_troll",false,false,69,0.22,9,6,1.6F,2.6F,"shove","rime_hide",0x283644,0xe0f4ff),
    SLAG_TROLL("slag_troll",false,false,69,0.22,9,6,1.6F,2.6F,"ember","slag_hide",0x301a14,0xfcc478),
    FEN_GOBLIN("fen_goblin",false,false,18,0.3,4,1,0.7F,1.2F,"hound","goblin_ear",0x1a2214,0xbace78),
    TUNNEL_GOBLIN("tunnel_goblin",false,false,18,0.3,4,1,0.7F,1.2F,"hound","goblin_fang",0x201c1c,0xcac0b8),
    RIDGE_KOBOLD("ridge_kobold",false,false,21,0.29,4,2,0.7F,1.1F,"hound","kobold_scale",0x2a1412,0xeea460),
    GEODE_KOBOLD("geode_kobold",false,false,21,0.29,4,2,0.7F,1.1F,"hound","kobold_horn",0x221c30,0xd4c6f2),
    GLIMMER_FAY("glimmer_fay",true,true,8,0.3,0,0,0.5F,0.6F,"none","fay_dust",0x3a2a0e,0xffeca0),
    PRISM_FAY("prism_fay",true,true,8,0.3,0,0,0.5F,0.6F,"none","fay_petal",0x361a28,0xfcbedc),
    MARSH_FAY("marsh_fay",true,true,8,0.3,0,0,0.5F,0.6F,"none","fay_spark",0x182e1a,0xbaec96),
    BARROW_SHADE("barrow_shade",false,false,25,0.25,5,0,0.8F,1.6F,"weaken","barrow_shroud",0x34322c,0xf0ecde),
    PALE_WRAITH("pale_wraith",false,true,25,0.25,5,0,0.8F,1.6F,"chill","wraith_veil",0x1e2834,0xd8f0ff),
    CINDER_SHADE("cinder_shade",false,true,25,0.25,5,0,0.8F,1.6F,"bolt","shade_ember",0x301a14,0xfcc478),
    DROWNED_SHADE("drowned_shade",false,false,25,0.25,5,0,0.8F,1.6F,"weaken","drowned_weed",0x122632,0xa0d6ec);
    public final String id,attack,reagent;
    public final boolean animal,flying;
    public final double health,speed,damage,armor;
    public final float width,height;
    public final int color,glow;
    CreatureProfile(String id,boolean animal,boolean flying,double health,double speed,double damage,double armor,float width,float height,String attack,String reagent,int color,int glow) {
        this.id=id;this.animal=animal;this.flying=flying;this.health=health;this.speed=speed;this.damage=damage;this.armor=armor;this.width=width;this.height=height;this.attack=attack;this.reagent=reagent;this.color=color;this.glow=glow;
    }
    private static final java.util.Set<String> BOSS_IDS=java.util.Set.of("colossus_warden");
    /** Bosses get a boss bar, an escort and a loot table worth the fight. */
    public boolean boss() { return BOSS_IDS.contains(id); }
    public static CreatureProfile of(EntityType<?> type) {
        String id=BuiltInRegistries.ENTITY_TYPE.getKey(type).getPath();
        for(var profile:values()) if(profile.id.equals(id)) return profile;
        throw new IllegalArgumentException("Unknown Tribal creature: "+id);
    }
    public boolean ranged() { return attack.equals("gust") || attack.equals("bolt") || attack.equals("chill"); }
}
