package tk.darrow.tribalpower.world;

import java.util.List;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.ResourceKey;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.biome.Biome;

/**
 * Every biome of the March, by band. Generated by tools/generate_march_breadth.py from tools/march_biomes.py;
 * the survey, the census, the weather, the insects and the GameTests all read this rather than their own lists.
 */
public enum MarchBiomes {
    MARCH_SNOW_FIELDS("march_snow_fields", Band.FROZEN, Family.LAND, false, false),
    MARCH_GLIMMER_RIDGE("march_glimmer_ridge", Band.COLD, Family.PEAK, true, true),
    MARCH_STEPPE("march_steppe", Band.TEMPERATE, Family.LAND, false, false),
    MARCH_REED_FEN("march_reed_fen", Band.TEMPERATE, Family.LAND, false, false),
    MARCH_CRYSTAL_FIELDS("march_crystal_fields", Band.TEMPERATE, Family.LAND, false, true),
    MARCH_SHALLOWS("march_shallows", Band.TEMPERATE, Family.OCEAN, true, false),
    MARCH_HIGHLANDS("march_highlands", Band.WARM, Family.PEAK, false, false),
    MARCH_EMBER_WASTES("march_ember_wastes", Band.HOT, Family.LAND, true, false),
    MARCH_RIME_SPIRES("march_rime_spires", Band.FROZEN, Family.LAND, true, false),
    MARCH_RIMEBIRCH_TAIGA("march_rimebirch_taiga", Band.FROZEN, Family.LAND, false, false),
    MARCH_FROST_SHORE("march_frost_shore", Band.FROZEN, Family.BEACH, true, false),
    MARCH_FROZEN_MERE("march_frozen_mere", Band.FROZEN, Family.RIVER, true, false),
    MARCH_RIME_SEA("march_rime_sea", Band.FROZEN, Family.OCEAN, true, false),
    MARCH_DEEP_RIME_SEA("march_deep_rime_sea", Band.FROZEN, Family.OCEAN, true, false),
    MARCH_HOAR_PEAKS("march_hoar_peaks", Band.FROZEN, Family.PEAK, true, false),
    MARCH_SHARD_PEAKS("march_shard_peaks", Band.FROZEN, Family.PEAK, true, true),
    MARCH_FROSTPINE_SLOPES("march_frostpine_slopes", Band.FROZEN, Family.LAND, false, false),
    MARCH_VEIL_FLATS("march_veil_flats", Band.FROZEN, Family.LAND, true, false),
    MARCH_THORNFIR_TAIGA("march_thornfir_taiga", Band.COLD, Family.LAND, false, false),
    MARCH_ELDER_THORNFIR_TAIGA("march_elder_thornfir_taiga", Band.COLD, Family.LAND, false, false),
    MARCH_BARROW_MOOR("march_barrow_moor", Band.COLD, Family.LAND, false, false),
    MARCH_SCREE_FELLS("march_scree_fells", Band.COLD, Family.LAND, true, false),
    MARCH_WINDSWEPT_THORNFIR("march_windswept_thornfir", Band.COLD, Family.LAND, false, false),
    MARCH_HOARMOSS_GROVE("march_hoarmoss_grove", Band.COLD, Family.LAND, false, false),
    MARCH_GREY_SHORE("march_grey_shore", Band.COLD, Family.BEACH, true, false),
    MARCH_COLD_SHALLOWS("march_cold_shallows", Band.COLD, Family.OCEAN, true, false),
    MARCH_DEEP_COLD_SHALLOWS("march_deep_cold_shallows", Band.COLD, Family.OCEAN, true, false),
    MARCH_TARN_COUNTRY("march_tarn_country", Band.COLD, Family.LAND, false, false),
    MARCH_SONGMAPLE_WOOD("march_songmaple_wood", Band.TEMPERATE, Family.LAND, false, false),
    MARCH_BLOOM_MEADOW("march_bloom_meadow", Band.TEMPERATE, Family.LAND, false, false),
    MARCH_HEARTHOAK_WOLD("march_hearthoak_wold", Band.TEMPERATE, Family.LAND, false, false),
    MARCH_ELDER_HEARTHOAK_WOLD("march_elder_hearthoak_wold", Band.TEMPERATE, Family.LAND, false, false),
    MARCH_VEILWOOD("march_veilwood", Band.TEMPERATE, Family.LAND, false, false),
    MARCH_CHIME_ORCHARD("march_chime_orchard", Band.TEMPERATE, Family.LAND, false, false),
    MARCH_HIGH_MEADOW("march_high_meadow", Band.TEMPERATE, Family.LAND, false, false),
    MARCH_SUNWHEEL_STEPPE("march_sunwheel_steppe", Band.TEMPERATE, Family.LAND, false, false),
    MARCH_LOOM_RIVER("march_loom_river", Band.TEMPERATE, Family.RIVER, true, false),
    MARCH_SILT_STRAND("march_silt_strand", Band.TEMPERATE, Family.BEACH, true, false),
    MARCH_DEEP_SHALLOWS("march_deep_shallows", Band.TEMPERATE, Family.OCEAN, true, false),
    MARCH_GLOWCAP_MIRE("march_glowcap_mire", Band.TEMPERATE, Family.LAND, false, true),
    MARCH_DRUMPALM_SAVANNA("march_drumpalm_savanna", Band.WARM, Family.LAND, false, false),
    MARCH_DRUMPALM_PLATEAU("march_drumpalm_plateau", Band.WARM, Family.LAND, false, false),
    MARCH_WINDSWEPT_DRUMPALM("march_windswept_drumpalm", Band.WARM, Family.LAND, false, false),
    MARCH_TANGLEWOOD("march_tanglewood", Band.WARM, Family.LAND, false, false),
    MARCH_OPEN_TANGLEWOOD("march_open_tanglewood", Band.WARM, Family.LAND, false, false),
    MARCH_CANE_THICKET("march_cane_thicket", Band.WARM, Family.LAND, false, false),
    MARCH_STRIDER_MANGROVE("march_strider_mangrove", Band.WARM, Family.LAND, false, false),
    MARCH_SUN_PEAKS("march_sun_peaks", Band.WARM, Family.PEAK, true, false),
    MARCH_WARM_SHALLOWS("march_warm_shallows", Band.WARM, Family.OCEAN, true, false),
    MARCH_DEEP_WARM_SHALLOWS("march_deep_warm_shallows", Band.WARM, Family.OCEAN, true, false),
    MARCH_SALT_FLATS("march_salt_flats", Band.HOT, Family.LAND, true, false),
    MARCH_KILN_MESA("march_kiln_mesa", Band.HOT, Family.PEAK, true, false),
    MARCH_CUT_MESA("march_cut_mesa", Band.HOT, Family.LAND, true, false),
    MARCH_SUNBARK_MESA("march_sunbark_mesa", Band.HOT, Family.LAND, false, false),
    MARCH_GLASS_SHALLOWS("march_glass_shallows", Band.HOT, Family.OCEAN, true, false),
    MARCH_SINGING_CAVES("march_singing_caves", Band.UNDERGROUND, Family.CAVE, true, false),
    MARCH_GLOOMCAP_HOLLOWS("march_gloomcap_hollows", Band.UNDERGROUND, Family.CAVE, true, true),
    MARCH_THE_HUSH("march_the_hush", Band.UNDERGROUND, Family.CAVE, true, false),
    MARCH_LEY_VEINS("march_ley_veins", Band.UNDERGROUND, Family.CAVE, true, true);

    public enum Band { FROZEN, COLD, TEMPERATE, WARM, HOT, UNDERGROUND }
    /** land: open ground; peak: mountain; beach and river: the shore and the valleys; ocean: open sea; cave: placed by depth. */
    public enum Family { LAND, PEAK, BEACH, RIVER, OCEAN, CAVE }

    public final String id;
    public final Band band;
    public final Family family;
    /** Meant to be nearly bare of plants (ash, rock, ice, sand): the survey does not hold it to a plant floor. */
    public final boolean bare;
    /** Meant to glow: the survey allows it more light than the rest. */
    public final boolean glow;
    public final ResourceKey<Biome> key;

    MarchBiomes(String id, Band band, Family family, boolean bare, boolean glow) {
        this.id = id; this.band = band; this.family = family; this.bare = bare; this.glow = glow;
        this.key = ResourceKey.create(Registries.BIOME, ResourceLocation.fromNamespaceAndPath("tribalpower", id));
    }

    private static final java.util.Map<String, MarchBiomes> BY_ID = new java.util.HashMap<>();
    static { for (MarchBiomes b : values()) BY_ID.put(b.id, b); }

    public static MarchBiomes of(String id) {
        return id == null ? null : BY_ID.get(id);
    }

    public static MarchBiomes of(ResourceKey<Biome> key) {
        return key == null ? null : of(key.location().getPath());
    }

    /** Ground a player can stand on at the surface: everything but the open sea and the caves. */
    public static List<MarchBiomes> land() {
        return java.util.Arrays.stream(values()).filter(b -> b.family != Family.OCEAN && b.family != Family.CAVE).toList();
    }

    public static List<MarchBiomes> caves() {
        return java.util.Arrays.stream(values()).filter(b -> b.family == Family.CAVE).toList();
    }

    public static List<String> ids() {
        return java.util.Arrays.stream(values()).map(b -> b.id).toList();
    }
}
