package tk.darrow.tribalpower.world;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.dimension.DimensionType;
import net.minecraft.world.level.storage.LevelResource;
import net.neoforged.neoforge.event.entity.player.PlayerEvent;
import net.neoforged.neoforge.event.server.ServerAboutToStartEvent;
import tk.darrow.tribalpower.TribalPower;
import tk.darrow.tribalpower.config.TribalConfig;

/**
 * One-time retrogen. A March generated by an older Tribal Power keeps its old terrain and its old flora
 * load for ever, because finished chunks are never generated again. The first time a save meets a newer
 * {@link #WORLDGEN_VERSION}, the old March is set aside and the dimension regenerates as it is explored.
 *
 * <p>It runs before any level loads, so no chunk is open while its region file moves. Nothing is deleted:
 * the old chunks go to {@code tribalpower_backups} inside the save, and copying them back restores them.
 * The marker file is what makes it once only.
 */
public final class MarchRetrogen {
    /** Bump when March terrain changes enough that old chunks should not sit beside new ones. */
    public static final int WORLDGEN_VERSION = 3;
    private static final String MARKER = "tribalpower_march_worldgen.txt";
    private static final String PLAYER_VERSION = "TribalMarchWorldgen";
    /** The last March reset this player has been brought through; compared with the marker's generation. */
    private static final String PLAYER_RESET = "TribalMarchReset";
    /** Everything chunk-shaped. The dimension's {@code data} folder holds no Tribal Power state. */
    private static final List<String> CHUNK_FOLDERS = List.of("region", "entities", "poi");

    /** How many times this save's March has been set aside; players caught inside it need ground again. */
    private static int resetGeneration;

    private MarchRetrogen() {}

    public static void onServerAboutToStart(ServerAboutToStartEvent event) {
        Path root = event.getServer().getWorldPath(LevelResource.ROOT);
        Path march = DimensionType.getStorageFolder(ModDimensions.THE_MARCH, root);
        Path marker = root.resolve(MARKER);
        resetGeneration = 0;
        try {
            Marker state = Marker.read(marker);
            resetGeneration = state.generation;
            if (state.version >= WORLDGEN_VERSION) return;
            if (!hasChunks(march)) {
                // A new save, or one that never opened a gate: nothing to redo.
                new Marker(WORLDGEN_VERSION, state.reset, state.generation).write(marker);
                return;
            }
            if (!TribalConfig.retrogenMarch()) {
                TribalPower.LOGGER.info("The March predates worldgen {} but retrogenMarch is off; leaving it as it is", WORLDGEN_VERSION);
                return; // no marker, so turning the option on later still works
            }
            Path backup = setAside(root, march, state.version);
            resetGeneration = state.generation + 1;
            new Marker(WORLDGEN_VERSION, true, resetGeneration).write(marker);            TribalPower.LOGGER.info("The March was generated by an older Tribal Power (worldgen {} -> {}). Its chunks were moved to {} and the dimension will regenerate.",
                    state.version, WORLDGEN_VERSION, backup);
        } catch (IOException error) {
            // No marker is written, so the next start tries again rather than leaving a half-old March.
            TribalPower.LOGGER.error("Could not set the old March aside; it is left as it was", error);
        }
    }

    /** Any of the folders counts, so a set-aside that stopped half way is finished on the next start. */
    private static boolean hasChunks(Path march) throws IOException {
        for (String folder : CHUNK_FOLDERS) {
            Path dir = march.resolve(folder);
            if (!Files.isDirectory(dir)) continue;
            try (var files = Files.list(dir)) {
                if (files.anyMatch(file -> file.getFileName().toString().endsWith(".mca") && size(file) > 0)) return true;
            }
        }
        return false;
    }

    private static long size(Path file) {
        try {
            return Files.size(file);
        } catch (IOException error) {
            return 0;
        }
    }

    private static Path setAside(Path root, Path march, int oldVersion) throws IOException {
        Path base = root.resolve("tribalpower_backups");
        Path backup = base.resolve("the_march_worldgen_" + oldVersion);
        for (int attempt = 2; Files.exists(backup); attempt++) backup = base.resolve("the_march_worldgen_" + oldVersion + "_" + attempt);
        Files.createDirectories(backup);
        List<String> moved = new java.util.ArrayList<>();
        try {
            for (String folder : CHUNK_FOLDERS) {
                Path source = march.resolve(folder);
                // Same volume, so this is a rename: instant, and either whole or not at all.
                if (Files.isDirectory(source)) {
                    Files.move(source, backup.resolve(folder));
                    moved.add(folder);
                }
            }
        } catch (IOException error) {
            // Put back what already moved so the March is never left half old, half new.
            for (String folder : moved) {
                try {
                    Files.move(backup.resolve(folder), march.resolve(folder));
                } catch (IOException undo) {
                    error.addSuppressed(undo);
                }
            }
            throw error;
        }
        return backup;
    }

    /** A player who logged out inside the old March wakes at coordinates that now mean something else. */
    public static void onLogin(PlayerEvent.PlayerLoggedInEvent event) {
        if (!(event.getEntity() instanceof ServerPlayer player)) return;
        var root = player.getPersistentData();
        var persisted = root.getCompound(Player.PERSISTED_NBT_TAG);
        root.put(Player.PERSISTED_NBT_TAG, persisted);
        // Players stamped by the older worldgen-version marker count as brought through the first reset.
        int seen = persisted.contains(PLAYER_RESET) ? persisted.getInt(PLAYER_RESET)
                : persisted.getInt(PLAYER_VERSION) >= WORLDGEN_VERSION ? Math.min(1, resetGeneration) : 0;
        if (seen >= resetGeneration) return;
        if (!player.level().dimension().equals(ModDimensions.THE_MARCH)) {
            persisted.putInt(PLAYER_RESET, resetGeneration);
            return;
        }
        BlockPos feet = ModDimensions.resolveArrival(player.serverLevel(), player.blockPosition());
        if (feet == null) feet = ModDimensions.resolveArrival(player.serverLevel(), player.serverLevel().getSharedSpawnPos());
        if (feet == null) return; // not marked, so the next login tries again
        persisted.putInt(PLAYER_RESET, resetGeneration);
        player.teleportTo(feet.getX() + 0.5, feet.getY(), feet.getZ() + 0.5);
        player.fallDistance = 0;
        player.displayClientMessage(Component.translatable("message.tribalpower.march.retrogen"), false);
    }

    private record Marker(int version, boolean reset, int generation) {
        /** A save with no marker was last generated by worldgen 1, the terrain of 3.4.3 and earlier. */
        static Marker read(Path file) throws IOException {
            if (!Files.isRegularFile(file)) return new Marker(1, false, 0);
            int version = 1;
            boolean reset = false;
            int generation = -1;
            for (String line : Files.readAllLines(file, StandardCharsets.UTF_8)) {
                String[] pair = line.split("=", 2);
                if (pair.length != 2) continue;
                if (pair[0].trim().equals("version")) {
                    try {
                        version = Integer.parseInt(pair[1].trim());
                    } catch (NumberFormatException ignored) {
                        // A hand-edited marker that no longer parses counts as old.
                    }
                } else if (pair[0].trim().equals("reset")) reset = Boolean.parseBoolean(pair[1].trim());
                else if (pair[0].trim().equals("generation")) {
                    try {
                        generation = Integer.parseInt(pair[1].trim());
                    } catch (NumberFormatException ignored) {
                        // Falls back to what reset implies.
                    }
                }
            }
            // Markers written before generations existed had at most one reset.
            if (generation < 0) generation = reset ? 1 : 0;
            return new Marker(version, reset, generation);
        }

        void write(Path file) throws IOException {
            Files.write(file, List.of("# Tribal Power: the worldgen version this save's March was generated with.",
                    "# Deleting this file makes the next start treat the March as old and set it aside again.",
                    "version=" + version, "reset=" + reset, "generation=" + generation), StandardCharsets.UTF_8);
        }
    }
}
