package tk.darrow.tribalpower.world;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.level.dimension.DimensionType;
import net.minecraft.world.level.storage.LevelResource;
import net.neoforged.neoforge.event.entity.player.PlayerEvent;
import net.neoforged.neoforge.event.server.ServerAboutToStartEvent;
import tk.darrow.tribalpower.TribalPower;
import tk.darrow.tribalpower.config.TribalConfig;

/**
 * One-time retrogen. A March generated by an older Tribal Power keeps its old terrain and its old flora
 * load for ever, because finished chunks are never generated again. The first time a save meets a newer
 * {@link #WORLDGEN_VERSION}, the old March is set aside and the dimension regenerates as it is explored.
 *
 * <p>It runs before any level loads, so no chunk is open while its region file moves. Nothing is deleted:
 * the old chunks go to {@code tribalpower_backups} inside the save, and copying them back restores them.
 * The marker file is what makes it once only.
 */
public final class MarchRetrogen {
    /** Bump when March terrain changes enough that old chunks should not sit beside new ones. */
    public static final int WORLDGEN_VERSION = 2;
    private static final String MARKER = "tribalpower_march_worldgen.txt";
    private static final String PLAYER_VERSION = "TribalMarchWorldgen";
    /** Everything chunk-shaped. The dimension's {@code data} folder holds no Tribal Power state. */
    private static final List<String> CHUNK_FOLDERS = List.of("region", "entities", "poi");

    /** Whether this save's March has ever been set aside; players caught inside it need ground again. */
    private static boolean marchWasReset;

    private MarchRetrogen() {}

    public static void onServerAboutToStart(ServerAboutToStartEvent event) {
        Path root = event.getServer().getWorldPath(LevelResource.ROOT);
        Path march = DimensionType.getStorageFolder(ModDimensions.THE_MARCH, root);
        Path marker = root.resolve(MARKER);
        try {
            Marker state = Marker.read(marker);
            marchWasReset = state.reset;
            if (state.version >= WORLDGEN_VERSION) return;
            if (!hasChunks(march)) {
                // A new save, or one that never opened a gate: nothing to redo.
                new Marker(WORLDGEN_VERSION, state.reset).write(marker);
                return;
            }
            if (!TribalConfig.retrogenMarch()) {
                TribalPower.LOGGER.info("The March predates worldgen {} but retrogenMarch is off; leaving it as it is", WORLDGEN_VERSION);
                return; // no marker, so turning the option on later still works
            }
            Path backup = setAside(root, march, state.version);
            marchWasReset = true;
            new Marker(WORLDGEN_VERSION, true).write(marker);
            TribalPower.LOGGER.info("The March was generated by an older Tribal Power (worldgen {} -> {}). Its chunks were moved to {} and the dimension will regenerate.",
                    state.version, WORLDGEN_VERSION, backup);
        } catch (IOException error) {
            // No marker is written, so the next start tries again rather than leaving a half-old March.
            TribalPower.LOGGER.error("Could not set the old March aside; it is left as it was", error);
        }
    }

    private static boolean hasChunks(Path march) throws IOException {
        Path region = march.resolve("region");
        if (!Files.isDirectory(region)) return false;
        try (var files = Files.list(region)) {
            return files.anyMatch(file -> file.getFileName().toString().endsWith(".mca") && size(file) > 0);
        }
    }

    private static long size(Path file) {
        try {
            return Files.size(file);
        } catch (IOException error) {
            return 0;
        }
    }

    private static Path setAside(Path root, Path march, int oldVersion) throws IOException {
        Path base = root.resolve("tribalpower_backups");
        Path backup = base.resolve("the_march_worldgen_" + oldVersion);
        for (int attempt = 2; Files.exists(backup); attempt++) backup = base.resolve("the_march_worldgen_" + oldVersion + "_" + attempt);
        Files.createDirectories(backup);
        for (String folder : CHUNK_FOLDERS) {
            Path source = march.resolve(folder);
            // Same volume, so this is a rename: instant, and either whole or not at all.
            if (Files.isDirectory(source)) Files.move(source, backup.resolve(folder));
        }
        return backup;
    }

    /** A player who logged out inside the old March wakes at coordinates that now mean something else. */
    public static void onLogin(PlayerEvent.PlayerLoggedInEvent event) {
        if (!(event.getEntity() instanceof ServerPlayer player)) return;
        var root = player.getPersistentData();
        var persisted = root.getCompound(Player.PERSISTED_NBT_TAG);
        root.put(Player.PERSISTED_NBT_TAG, persisted);
        int seen = persisted.getInt(PLAYER_VERSION);
        if (seen >= WORLDGEN_VERSION) return;
        persisted.putInt(PLAYER_VERSION, WORLDGEN_VERSION);
        if (!marchWasReset || !player.level().dimension().equals(ModDimensions.THE_MARCH)) return;
        BlockPos feet = ModDimensions.resolveArrival(player.serverLevel(), player.blockPosition());
        if (feet == null) feet = ModDimensions.resolveArrival(player.serverLevel(), player.serverLevel().getSharedSpawnPos());
        if (feet == null) return;
        player.teleportTo(feet.getX() + 0.5, feet.getY(), feet.getZ() + 0.5);
        player.fallDistance = 0;
        player.displayClientMessage(Component.translatable("message.tribalpower.march.retrogen"), false);
    }

    private record Marker(int version, boolean reset) {
        /** A save with no marker was last generated by worldgen 1, the terrain of 3.4.3 and earlier. */
        static Marker read(Path file) throws IOException {
            if (!Files.isRegularFile(file)) return new Marker(1, false);
            int version = 1;
            boolean reset = false;
            for (String line : Files.readAllLines(file, StandardCharsets.UTF_8)) {
                String[] pair = line.split("=", 2);
                if (pair.length != 2) continue;
                if (pair[0].trim().equals("version")) {
                    try {
                        version = Integer.parseInt(pair[1].trim());
                    } catch (NumberFormatException ignored) {
                        // A hand-edited marker that no longer parses counts as old.
                    }
                } else if (pair[0].trim().equals("reset")) reset = Boolean.parseBoolean(pair[1].trim());
            }
            return new Marker(version, reset);
        }

        void write(Path file) throws IOException {
            Files.write(file, List.of("# Tribal Power: the worldgen version this save's March was generated with.",
                    "# Deleting this file makes the next start treat the March as old and set it aside again.",
                    "version=" + version, "reset=" + reset), StandardCharsets.UTF_8);
        }
    }
}
