"""Single source for the standalone written book and machine-readable guide."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHAPTERS = [
    ('Spirit Codex', 'Shamanic technomancy begins with a rhythm. Raise a camp that answers you: living power, elemental workshops, woven equipment and paths between worlds.'),
    ('First camp', 'Craft a Bone Chime, Spirit Shard and Drumheart. Add a Pulse Cell. JEI shows crafting recipes; every system also works without another mod installed.'),
    ('Spirit Pulse', 'Pulse comes from rhythm, landscape and harmony. Keep a generator within 8 blocks of your workshop. Machines draw from generators first, then totem buffers.'),
    ('Drumheart', 'Strike empty-handed. Beats about one second apart yield 24 Pulse; offbeat hits yield 10. Redstone rising edges give 5, with an 8-tick cooldown. Build a clock to automate rhythm.'),
    ('Ley Collector', 'Open sky, night, rain, nearby water and living greenery strengthen collection. Place it thoughtfully. A redstone signal pauses generation.'),
    ('Pulse Resonator', 'Seat an Echo catalyst and place at least two different elemental totems within 8 blocks. More distinct voices and stronger catalysts increase generation. The catalyst is reusable.'),
    ('Harmonic ranks', 'Catalysts: Echo Shard, Attuned Echo, Bound Echo, Resonant Core. Coal and wood are not fuels. Sneak with an empty hand to recover the catalyst. Redstone pauses generation.'),
    ('Carry the beat', 'Use a Pulse Cell on a Drumheart or Resonator to charge it. Ordinary cells hold 200 Pulse; Greater Cells hold 1,200. Carry charged cells for spells, tools and travel.'),
    ('Six voices', 'Earth shatters. Fire attunes. Water binds. Spirit manifests. Air lends motion. Loom unweaves. Place the needed totem within 8 blocks of the station; missing voices pause work safely.'),
    ('Chalk and conductor', 'Mark two totems with Ritual Chalk to link them within 16 blocks. A Conductor moves Pulse through linked totems and routes Song Bench items through nearby Ancestral Caches.'),
    ('Echo workshops', 'The four Echo stations process real batches. Feed slot 0 from above or the sides; extract finished items below. Each has a work display and eight output slots. Full output pauses work.'),
    ('Shatter', 'Earth turns stone into Echo Shards. Raw iron, copper and gold become two grits each. Smelt or blast grits into ingots. Shared raw-material tags accept compatible ores from other mods.'),
    ('Attune and Bind', 'Fire turns Echo Shards into Attuned Echoes. Water binds them into Bound Echoes. Bind also turns wool into Spiritweave and dirt into clay. Check JEI for time and Pulse costs.'),
    ('Manifest', 'Spirit turns Bound Echoes into Manifested Ingots, then ingots into Resonant Cores. Cores unlock stronger cells, equipment and long-distance automation.'),
    ('Song Bench', 'The original single-item workshop remains. Insert an Echo-stage ingredient and click empty-handed to sing; sneak-click to retrieve it. Dedicated Echo stations are better for sustained batches.'),
    ('Ancestral Cache', 'A local 54-slot inventory for camp supplies. Hoppers and item pipes work normally. A redstone signal locks access and automation. A comparator reads how full it is.'),
    ('Deep Cache', 'A personal 54-slot vault shared between your Deep Caches. Visiting The March attunes you; otherwise opening costs 5 Pulse. A Wayfarer Satchel opens the same personal vault.'),
    ('Spirit Cistern', 'Stores 16 buckets of one fluid. Buckets and standard fluid pipes both work. Redstone locks filling and draining, including remote relays. A comparator reads fullness.'),
    ('Wireless cargo', 'Place an item or fluid relay above its source inventory or tank. Use the Lattice Tuner on a destination face, then on the relay. Sneak-use the tuner to replace a previous mark.'),
    ('Cargo tiers', 'Local relays reach 32 blocks. Longreach relays reach 128. Astral relays have no distance limit and can cross dimensions. Transfers cost 4, 8 or 16 Pulse per successful beat.'),
    ('Cargo rhythm', 'Each second, a relay moves up to 16 items or 250 mB. Both ends must already be loaded. Unloaded or full destinations pause safely. Relays never keep distant chunks loaded themselves.'),
    ('Cargo controls', 'Redstone pauses a relay. Comparator: 0 unlinked, 1 linked but waiting, 15 transferring. Lock the receiver with redstone when you need a remote stop. Bound links survive pickup.'),
    ('Pulse to FE', 'The Pulse Adapter converts 1 Pulse into 100 FE, up to 20 Pulse each second. It buffers 16,000 FE and exports to standard energy receivers. Redstone stops conversion and extraction.'),
    ('Waystone paths', 'Sneak-use a compass on the top of a solid floor to bind a landing. Use it to return. Keep two clear dry blocks above the floor. Power the landing floor with redstone to lock arrival.'),
    ('Travel tiers', 'Waystone Compass: 128 blocks, same world, 20 Pulse. Horizon Compass: any distance in one world, 40 Pulse. Astral Compass: across dimensions, 100 Pulse. Travel has a 5-second cooldown.'),
    ('The March', 'The Gate Drum opens the way to The March. Bring charged cells and prepare a return route. March materials unlock Astral transport, the final tier for both travellers and cargo.'),
    ('Sixfold Staff', 'Sneak-use to choose a voice; use to cast. Earth slows foes, Fire strikes and ignites, Water heals and cleanses, Air grants a short leap and slow falling, Spirit reveals nearby enemies, Loom tethers a foe toward you or, sneaking with no target, stitches you 6 blocks forward.'),
    ('Staff costs', 'Earth 12, Fire 18, Water 24, Air 16, Spirit 20 Pulse. Water rests for 8 seconds; other voices for 2. Offensive spells target hostile creatures and stop at solid obstacles.'),
    ('Resonance Maul', 'Hold the maul in your main hand. Sneak-use a stone face to excavate a 3-by-3 plane. Each block costs 8 Pulse. Tool requirements and normal player block protection still apply.'),
    ('Spiritweave', 'Hood: night sight. Robe: resistance. Leggings: speed. Boots: slow falling when descending. Each active piece spends 2 Pulse every four seconds. Carry spare cells for long expeditions.'),
    ('Ritual Brazier', 'Seat a reusable elemental seal. With its matching totem and Pulse nearby, the brazier sustains a blessing for players within 6 blocks. It spends 8 Pulse every two seconds.'),
    ('Camp blessings', 'Earth grants haste; Fire resists flame; Water regenerates; Air slows falls; Spirit grants night sight. Redstone pauses the brazier. Sneak empty-handed to recover its seal.'),
    ('Redstone language', 'High signal pauses workshops, conductors, resonators, collectors, relays and braziers; it locks storage and travel destinations. The Drumheart instead listens for rising edges to make beats.'),
    ('Read the camp', 'Comparators read stored Pulse, inventory or fluid fullness, FE buffer, and relay activity. A pause keeps stored resources intact. Use clocks, levers and comparators to choreograph the camp.'),
    ('Other workshops', 'Lattice recipes use the normal recipe manager and sync to clients. Datapacks can add tribalpower:lattice recipes using shared ingredient tags. JEI displays them when installed.'),
    ('The veil at night', 'After dusk, the sky unfolds in slow curtains of green and violet. The March carries a colder sky. Rain veils the aurora. Client settings can reduce its detail or disable it for shader packs.'),
    ('Gentle harvesting', 'Brush adult Dawn Stags, Lantern Foxes and Mossbacks for renewable reagents. Each rests for one minute between harvests. Young animals do not yield materials. Breed with wheat, sweet berries and seagrass respectively.'),
    ('Broken guardians', 'Ashbound, Rootbound and Reed Stalkers haunt forests and marshes in the Overworld. All can also be found in the March. Build lighted paths: hostile creatures require darkness.'),
    ('Beyond the Gate', 'Steppe: Ashbound, Rootbound, Rift Hounds and Echo Weavers. Highlands: Hollow Sentinels, Storm Moths, Cinder Imps and Rift Hounds. Crystal Fields: Shardbacks, Mourning Bells, Reed Stalkers and Echo Weavers.'),
    ('Answering a spell', 'Storm Moths, Cinder Imps and Mourning Bells gather visible motes before casting. Step behind solid cover to interrupt. Their magic never burns or replaces terrain. A charged staff is useful for keeping distance.'),
    ('Returning the song', 'Bring creature reagents to the Echo workshops. Gentle animal harvests, Storm Wings and Echo Silk bind into Spiritweave under Water. Other hostile remnants attune into two Attuned Echoes under Spirit. Existing recipes remain available.'),
]

CHAPTERS.extend((r["title"], r["text"]) for r in json.loads((ROOT/"tools/camp_guides.json").read_text(encoding="utf-8")))
CHAPTERS.append(('The sixth voice', 'The sixth voice is the thread itself. Loom Thread comes from Ancestor Halls and The Unsung; an Unsung Heart, two threads, four March Crystals and two March Planks make the Loom totem, a distinct voice for the Resonator. Echo Unweave reverses the lattice: ingots to echoes, cores to ingots, Spiritweave to wool, and worn Spiritgear to one Manifested Ingot. A Loom Seal in a Brazier threads 2 Pulse into carried cells every 2 seconds with Luck. The Sixfold Staff gains Tether and, sneaking with no target, Stitch.'))

CHAPTERS.append(('Bonded spirits', 'Craft a Bonding Charm from two Spiritweave, a Spirit Shard and a Lantern Down, Mossback Scale or Dawn Velvet. Use it on an adult Lantern Fox, Mossback or Dawn Stag: three tries in five succeed with hearts, and a failed charm is kept. A bonded animal follows within ten blocks, teleports to you past twelve, never despawns, ignores your blows and sheds double reagent when brushed. Sneak-use it to make it wait or follow again.'))
CHAPTERS.append(('Lantern Fox familiar', 'A bonded Lantern Fox lights the way: it carries an invisible Spirit Light with it, grants Night Vision while you stay within eight blocks, and every four seconds marks ores within six blocks of itself with glints only you can see.'))
CHAPTERS.append(('Mossback and Dawn Stag familiars', 'A bonded Mossback carries a nine-slot saddlebag: sneak-use it with an empty hand to open the bag; sneak-use holding an item to make it wait or follow. It drops the bag on death. A bonded Dawn Stag needs no saddle: use it to mount, steer with your gaze, hold jump for a short leap and sneak to dismount. It carries only the one it is bonded to.'))
CHAPTERS.append(('Shared camps', "Found a camp with /tribalpower camp create <name>, then invite with /tribalpower camp invite <player> or by using a Camp Charter (paper, Spiritweave, Spirit Shard) on them; invitations last five minutes and are accepted with /tribalpower camp join <name>. Members open one shared 54-slot camp vault from any Deep Cache or Wayfarer Satchel (sneak-use to switch back to your personal vault), count as owners of each other's camp devices, and share a budget of twelve Wayanchors instead of thirty-two per dimension. Leave, kick, rename and info complete the command."))

# Rites / QoL (design 3.0 §4, §7)
CHAPTERS.append(("World rites", "Carve a Rite Tablet from two stone, a creature reagent and the matching seal; the seal is handed back. Sneak-use the tablet on a Ritual Brazier holding that seal. The brazier draws the rite's Pulse from the lattice within 8 blocks; if there is not enough, nothing is spent. Rain Calling (Water, 400) brings twenty minutes of rain. Sky Clearing (Air, 400) clears forty minutes. Dawn Calling (Fire, 800) hurries the night to sunrise unless the game rule tribalpower:allowDawnRite is off."))
CHAPTERS.append(("Land rites", "Green Blessing (Earth, 600) blesses the nine chunks around the brazier for twenty minutes: crops, saplings and stems there take extra random ticks and sparkle green. Still Night (Spirit, 600) hushes hostile spawning within 64 blocks for fifteen minutes, like a wide Hush Totem. Ley Binding (Loom, 1,200) ties the brazier's nearest Resonance Totem to another within 64 blocks for thirty minutes; a Conductor routes Pulse along the humming thread as if the totems stood side by side. Seal-carvers sell tablets to Friends."))
CHAPTERS.append(("Ley Lens", "A glass pane, a Copper Resonator and a Spirit Shard make a lens for ley sight. Hold it in either hand: the HUD reads the ley strength where you stand and the ground around you glows in a 9-by-9 grid, blue where the land is quiet and gold where it sings. Open sky counts, night counts triple, rain, water and greenery each add. Sneak-use the lens on a Ley Collector to print that collector's exact factor breakdown."))
CHAPTERS.append(("Pulse logic", "The Pulse Gauge points its arrow at any Pulse holder and emits redstone 0 to 15 in proportion to its stored charge, refreshed every four ticks; a comparator reads the same number. The Pulse Threshold points the same way and emits a full signal only while the holder sits at or above 25, 50, 75 or 100 percent; use it empty-handed to cycle, and a comparator reads 1 to 4. Both craft from redstone, a Copper Resonator and March Stone."))
CHAPTERS.append(("Codex diagnostics", "Sneak-use the Spirit Codex on any Tribal block to hear it explain itself: stored Pulse, every generator within 8 blocks with its output this second, the attunements present, the Pulse it could draw, and whether redstone pauses it. Workshops name their recipe and any missing voice or full output; relays report unloaded or locked endpoints; braziers list the rites their seal allows."))

# The Nine Tribes (design 3.0 §2)
CHAPTERS.append(("Standing", "Nine tribes kept the Loom, one Strand each; their camps still keep time. Offer a favoured item at a Tribe Hearth for +3 standing, the tribe's reagent for +8, any food for +1, or a charged Pulse Cell for +2 per 10 Pulse. Hostile kills within 24 blocks of a hearth give +1, twenty per day per tribe; a trade gives +2. Ranks: Guest 50, Friend 150, Kin 400, Voice 800. Hurting Kin costs 25 and turns the camp's Hunters on you for a minute; breaking a hearth costs 40. /tribalpower standing prints all nine."))
CHAPTERS.append(("Tribal Kin", "Every camp keeps four Kin: an Elder who trades from the tribe's table once you are a Guest, a Drummer whose beat feeds 2 Pulse into generators within 8 blocks, a Hunter who strikes hostiles within 12 blocks, and a Weaver at the loom. Kin wander within 16 blocks of their camp and never despawn. Elders unlock two offers per rank and, at Voice, press a Tribe Mark into your hand."))
CHAPTERS.append(("Kinship Totem", "Craft a Tribe Mark with the Resonance Totem of the tribe's voice and two Spiritweave. The Kinship Totem stores its tribe: it lends the tribe's voice to nearby stations and counts as an extra distinct voice for the Pulse Resonator, tracked per tribe rather than per element. Nine tribes beside six totems make fifteen voices."))
CHAPTERS.append(("Pad-keepers", "Strand of Soil, voice of Earth. Craft: hearths and caches. Camps stand in plains; a March camp keeps the old road. Favoured offerings: dirt, moss, bread and Echo Shards.\n\n\"We never called it dirt. We called it what was left, and we kept it warm.\""))
CHAPTERS.append(("Grit-singers", "Strand of Stone, voice of Earth. Craft: echo shatter and meshes. Camps stand in mountains; a March camp keeps the old road. Favoured offerings: raw ores, grits and Attuned Echo.\n\n\"The mesh does not find the ore. The mesh gives the ore somewhere to land.\""))
CHAPTERS.append(("Rootbinders", "Strand of Sprout, voice of Water. Craft: living anchors and March flora. Camps stand in forests; a March camp keeps the old road. Favoured offerings: saplings, seeds and Mossback Scale.\n\n\"Roots are the only rope the void respects.\""))
CHAPTERS.append(("Edge-walkers", "Strand of Claw, voice of Fire. Craft: Spiritgear and footholds. Camps stand in taiga; a March camp keeps the old road. Favoured offerings: leather, iron and Rift Tooth.\n\n\"Boots first. Then the bridge. Then the courage; it arrives on its own.\""))
CHAPTERS.append(("Drumhearts", "Strand of Spark, voice of Fire. Craft: drums and Pulse. Camps stand in savanna; a March camp keeps the old road. Favoured offerings: copper, charged Pulse Cells and Bone Chimes.\n\n\"The drum is not loud. The drum is steady. Be the drum.\""))
CHAPTERS.append(("Pattern-weavers", "Strand of Clock, voice of Air. Craft: timed songs and automation. Camps stand in birch woods; a March camp keeps the old road. Favoured offerings: redstone, clocks and Storm Wing.\n\n\"A factory is a song that has stopped needing the singer.\""))
CHAPTERS.append(("Colony-keepers", "Strand of Swarm, voice of Air. Craft: hives and March flowers. Camps stand in flower meadows; a March camp keeps the old road. Favoured offerings: honey, flowers and Lantern Down.\n\n\"You do not own a hive. You are on good terms with it.\""))
CHAPTERS.append(("Seal-carvers", "Strand of Sigil, voice of Spirit. Craft: seals and rites. Camps stand in dark forests; a March camp keeps the old road. Favoured offerings: blank or element seals and Spirit Shards.\n\n\"Spirit goes where it is asked politely and stays where it is fed.\""))
CHAPTERS.append(("Loom-stitchers", "Strand of Spindle, voice of Loom. Craft: gate-paths and the reweave. Camps stand in the March crystal fields only; a March camp keeps the old road. Favoured offerings: March Crystal, Loom Thread and compasses.\n\n\"The Loom was never one thread. It was nine agreeing.\""))

def main():
    roster=json.loads((ROOT/'art/creatures/roster.json').read_text(encoding='utf-8'))
    chapters=CHAPTERS+[(r['name'],r['notes']) for r in roster]
    pages = [title.upper() + '\n\n' + body for title, body in chapters]
    source = 'package tk.darrow.tribalpower.guide;\n\nimport java.util.List;\n\n/** Generated by tools/generate_guide.py. */\npublic final class GuidePages {\n    private GuidePages() {}\n    public static List<String> allPages() {\n        return List.of(\n'
    source += ',\n'.join('            ' + json.dumps(page, ensure_ascii=True) for page in pages)
    source += '\n        );\n    }\n}\n'
    (ROOT/'src/main/java/tk/darrow/tribalpower/guide/GuidePages.java').write_text(source, encoding='utf-8')
    data = {'book':'Spirit Codex', 'chapters':[{'id':f'chapter_{i+1}', 'title':title, 'text':body} for i,(title,body) in enumerate(chapters)]}
    (ROOT/'src/main/resources/data/tribalpower/guide/spirit_codex.json').write_text(json.dumps(data,indent=2)+'\n', encoding='utf-8')
    print(f'Generated {len(pages)} guide pages.')

if __name__ == '__main__': main()
