"""Generate the native interactive Codex from the same teachings as the guide."""
import json
from pathlib import Path
from generate_guide import CHAPTERS

ROOT = Path(__file__).resolve().parents[1]
rows = json.loads((ROOT / 'tools/guide_catalog.json').read_text(encoding='utf-8'))
roster = json.loads((ROOT / 'art/creatures/roster.json').read_text(encoding='utf-8'))
texts = dict(CHAPTERS + [(r['name'], r['notes']) for r in roster])
for r in roster:
    texts[r['name']] += ('\n\nField notes\nHabitat: ' + r['habitat'].replace('_', ' ')
        + '.\nHealth: ' + str(r['health']) + ' | Armor: ' + str(r['armor'])
        + '.\nNature: ' + ('gentle animal' if r['kind']=='animal' else r['attack'].replace('_',' ') + ' hostile')
        + '.\nReagent: ' + r['reagent'].replace('_',' ') + '.\nUse Recipes to follow the reagent into your workshop.')
assert len(rows) == len(texts) and len({r['id'] for r in rows}) == len(rows)
source = '''package tk.darrow.tribalpower.guide;
import java.util.List;
/** Generated by tools/generate_wiki.py. */
public final class CodexEntries {
    public record Entry(String id, String title, String text, String category, String icon, boolean spoiler, String picture) {}
    public static final List<Entry> ALL = List.of(
'''
entries = []
for row in rows:
    values = [row['id'], row['title'], texts[row['title']], row['category'], row['icon'], row['spoiler'], row['picture']]
    entries.append('        new Entry(' + ', '.join(json.dumps(v, ensure_ascii=True) for v in values) + ')')
source += ',\n'.join(entries) + '\n    );\n    private CodexEntries() {}\n}\n'
(ROOT / 'src/main/java/tk/darrow/tribalpower/guide/CodexEntries.java').write_text(source, encoding='utf-8')
print(f'Generated {len(rows)} interactive Codex entries.')
