"""Single source for the standalone written book and machine-readable guide."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CHAPTERS = [
    ('Spirit Codex', 'Shamanic technomancy begins with a rhythm. Raise a camp that answers you: living power, elemental workshops, woven equipment and paths between worlds.'),
    ('First camp', 'Craft a Bone Chime, Spirit Shard and Drumheart. Add a Pulse Cell. JEI shows crafting recipes; every system also works without another mod installed.'),
    ('Spirit Pulse', 'Pulse comes from rhythm, landscape and harmony. Keep a generator within 8 blocks of your workshop. Machines draw from generators first, then totem buffers.'),
    ('Drumheart', 'Strike empty-handed. Beats about one second apart yield 24 Pulse; offbeat hits yield 10. Redstone now pays by the same tempo: a rising edge 17 to 23 ticks after the last one is worth 24, anything else 10, and nothing closer than 8 ticks counts at all. A well-built one-second clock makes 24 a second; a spam clock makes 10. The drum is not loud. The drum is steady.'),
    ('Ley Collector', 'Open sky, night, rain, nearby water and living greenery strengthen collection. Place it thoughtfully. A redstone signal pauses generation.'),
    ('Pulse Resonator', 'Seat an Echo catalyst and place at least two different elemental totems within 8 blocks. More distinct voices and stronger catalysts increase generation. The catalyst is reusable.'),
    ('Harmonic ranks', 'Catalysts: Echo Shard, Attuned Echo, Bound Echo, Resonant Core. Coal and wood are not fuels. Sneak with an empty hand to recover the catalyst. Redstone pauses generation.'),
    ('Carry the beat', 'Use a Pulse Cell on a Drumheart or Resonator to charge it. Ordinary cells hold 200 Pulse; Greater Cells hold 1,200. Carry charged cells for spells, tools and travel.'),
    ('Six voices', 'Earth shatters. Fire attunes. Water binds. Spirit manifests. Air lends motion. Loom unweaves. Place the needed totem within 8 blocks of the station; missing voices pause work safely.'),
    ('Chalk and conductor', 'Mark two totems with Ritual Chalk to link them within 16 blocks. A Conductor moves Pulse through linked totems and routes Song Bench items through nearby Ancestral Caches.'),
    ('Echo workshops', 'The four Echo stations process real batches. Feed slot 0 from above or the sides; extract finished items below. Each has a work display and eight output slots. Full output pauses work.'),
    ('Shatter', 'Earth turns stone into Echo Shards. Metals and gems are two different crafts: a metal goes raw item or silk-touched ore to grit, then grit to ingot in any furnace, while a gem or mineral goes silk-touched ore straight to the gem itself at twice the ore\u2019s own drop. The gem is never an input, because gem to gem would be a dupe. Every metal and mineral in the common tags is found automatically, so a modded ore works with no datapack.'),
    ('Attune and Bind', 'Fire turns Echo Shards into Attuned Echoes. Water binds them into Bound Echoes. Bind also turns wool into Spiritweave and dirt into clay. Check JEI for time and Pulse costs.'),
    ('Manifest', 'Spirit turns Bound Echoes into Manifested Ingots, then ingots into Resonant Cores. Cores unlock stronger cells, equipment and long-distance automation.'),
    ('Song Bench', 'The original single-item workshop remains. Insert an Echo-stage ingredient and click empty-handed to sing; sneak-click to retrieve it. Dedicated Echo stations are better for sustained batches.'),
    ('Ancestral Cache', 'A local 54-slot inventory for camp supplies. Hoppers and item pipes work normally. A redstone signal locks access and automation. A comparator reads how full it is.'),
    ('Deep Cache', 'A personal 54-slot vault shared between your Deep Caches. Visiting The March attunes you; otherwise opening costs 5 Pulse. A Wayfarer Satchel opens the same personal vault.'),
    ('Spirit Cistern', 'Stores 16 buckets of one fluid. Buckets and standard fluid pipes both work. Redstone locks filling and draining, including remote relays. A comparator reads fullness.'),
    ('Wireless cargo', 'Place an item or fluid relay above its source inventory or tank. Use the Lattice Tuner on a destination face, then on the relay. Sneak-use the tuner to replace a previous mark.'),
    ('Cargo tiers', 'Local relays reach 32 blocks. Longreach relays reach 128. Astral relays have no distance limit and can cross dimensions. Transfers cost 4, 8 or 16 Pulse per successful beat.'),
    ('Cargo rhythm', 'Each second, a relay moves up to 16 items or 250 mB. Both ends must already be loaded. Unloaded or full destinations pause safely. Relays never keep distant chunks loaded themselves.'),
    ('Cargo controls', 'Redstone pauses a relay. Comparator: 0 unlinked, 1 linked but waiting, 15 transferring. Lock the receiver with redstone when you need a remote stop. Bound links survive pickup.'),
    ('Pulse to FE', 'The Pulse Adapter converts 1 Pulse into 100 FE, up to 20 Pulse each second. It buffers 16,000 FE and exports to standard energy receivers. Redstone stops conversion and extraction.'),
    ('Waystone paths', 'Sneak-use a compass on the top of a solid floor to bind a landing. Use it to return. Keep two clear dry blocks above the floor. Power the landing floor with redstone to lock arrival.'),
    ('Travel tiers', 'Waystone Compass: 128 blocks, same world, 20 Pulse. Horizon Compass: any distance in one world, 40 Pulse. Astral Compass: across dimensions, 100 Pulse. Travel has a 5-second cooldown.'),
    ('The March', 'The Gate Drum opens the way to The March. Bring charged cells and prepare a return route. March materials unlock Astral transport, the final tier for both travellers and cargo.'),
    ('Sixfold Staff', 'Sneak-use to choose a voice; use to cast. Earth slows foes, Fire strikes and ignites, Water heals and cleanses, Air grants a short leap and slow falling, Spirit reveals nearby enemies, Loom tethers a foe toward you or, sneaking with no target, stitches you 6 blocks forward.'),
    ('Staff costs', 'Earth 12, Fire 18, Water 24, Air 16, Spirit 20 Pulse; Loom 6 to tether, 10 to stitch. Water rests for 8 seconds; other voices for 2. Offensive spells target hostile creatures and stop at solid obstacles.'),
    ('Resonance Maul', 'Hold the maul in your main hand. Sneak-use a stone face to excavate a 3-by-3 plane. Each block costs 8 Pulse. Tool requirements and normal player block protection still apply.'),
    ('Spiritweave', 'Hood: night sight. Robe: resistance. Leggings: speed. Boots: slow falling when descending. Each active piece spends 2 Pulse every four seconds. Carry spare cells for long expeditions.'),
    ('Ritual Brazier', 'Seat a reusable elemental seal. With its matching totem and Pulse nearby, the brazier sustains a blessing for players within 6 blocks. It spends 8 Pulse every two seconds.'),
    ('Camp blessings', 'Earth grants haste; Fire resists flame; Water regenerates; Air slows falls; Spirit grants night sight. Redstone pauses the brazier. Sneak empty-handed to recover its seal.'),
    ('Redstone language', 'A held signal stills the work. A struck signal calls it once. Holding a line high pauses workshops, conductors, resonators, collectors, relays, braziers, meshes, fonts, pedestals, gate keystones and every generator, and locks storage and travel destinations. A rising edge is a call, and only devices that do a discrete thing listen for one: a Drumheart takes a beat, a Ritual Brazier fires its seated rite, a keystone lights or darkens. Nothing is ever lost to a pause.'),
    ('Read the camp', 'Comparators read stored Pulse, inventory or fluid fullness, FE buffer, and relay activity. A pause keeps stored resources intact. Use clocks, levers and comparators to choreograph the camp.'),
    ('Other workshops', 'Lattice recipes use the normal recipe manager and sync to clients. Datapacks can add tribalpower:lattice recipes using shared ingredient tags. JEI displays them when installed.'),
    ('The veil at night', 'After dusk, the sky unfolds in slow curtains of green and violet. The March carries a colder sky. Rain veils the aurora. Client settings can reduce its detail or disable it for shader packs.'),
    ('Gentle harvesting', 'Brush adult Dawn Stags, Lantern Foxes and Mossbacks for renewable reagents. Each rests for one minute between harvests. Young animals do not yield materials. Breed with wheat, sweet berries and seagrass respectively.'),
    ('Broken guardians', 'Ashbound, Rootbound and Reed Stalkers haunt forests and marshes in the Overworld. All can also be found in the March. Build lighted paths: hostile creatures require darkness.'),
    ('Beyond the Gate', 'Steppe: Ashbound, Rootbound, Rift Hounds and Echo Weavers. Highlands: Hollow Sentinels, Storm Moths, Cinder Imps and Rift Hounds. Crystal Fields: Shardbacks, Mourning Bells, Reed Stalkers and Echo Weavers.'),
    ('Answering a spell', 'Storm Moths, Cinder Imps and Mourning Bells gather visible motes before casting. Step behind solid cover to interrupt. Their magic never burns or replaces terrain. A charged staff is useful for keeping distance.'),
    ('Returning the song', 'Bring creature reagents to the Echo workshops. Gentle animal harvests, Storm Wings and Echo Silk bind into Spiritweave under Water. Other hostile remnants attune into two Attuned Echoes under Spirit. Existing recipes remain available.'),
]

CHAPTERS.extend((r["title"], r["text"]) for r in json.loads((ROOT/"tools/camp_guides.json").read_text(encoding="utf-8")))
CHAPTERS.append(('The sixth voice', 'The sixth voice is the thread itself. Loom Thread comes from Ancestor Halls and The Unsung; an Unsung Heart, two threads, four March Crystals and two March Planks make the Loom totem, a distinct voice for the Resonator. Echo Unweave reverses the lattice: ingots to echoes, cores to ingots, Spiritweave to wool, and worn Spiritgear (only tools that have taken damage) to one Manifested Ingot. A Loom Seal in a Brazier threads 2 Pulse into carried cells every 2 seconds with Luck. The Sixfold Staff gains Tether and, sneaking with no target, Stitch.'))

CHAPTERS.append(('Bonded spirits', 'Craft a Bonding Charm from two Spiritweave, a Spirit Shard and a Lantern Down, Mossback Scale or Dawn Velvet. Use it on an adult Lantern Fox, Mossback or Dawn Stag: three tries in five succeed with hearts, and a failed charm is kept. A bonded animal follows within ten blocks, teleports to you past twelve, never despawns, ignores your blows and sheds double reagent when brushed. Sneak-use it to make it wait or follow again.'))
CHAPTERS.append(('Lantern Fox familiar', 'A bonded Lantern Fox lights the way: it carries an invisible Spirit Light with it, grants Night Vision while you stay within eight blocks, and every four seconds marks ores within six blocks of itself with glints only you can see.'))
CHAPTERS.append(('Mossback and Dawn Stag familiars', 'A bonded Mossback carries a nine-slot saddlebag: sneak-use it with an empty hand to open the bag; sneak-use holding an item to make it wait or follow. It drops the bag on death. A bonded Dawn Stag needs no saddle: use it to mount, steer with your gaze, hold jump for a short leap and sneak to dismount. It carries only the one it is bonded to.'))
CHAPTERS.append(('Shared camps', "Found a camp with /tribalpower camp create <name>, then invite with /tribalpower camp invite <player> or by using a Camp Charter (paper, Spiritweave, Spirit Shard) on them; invitations last five minutes and are accepted with /tribalpower camp join <name>. Members open one shared 54-slot camp vault from any Deep Cache or Wayfarer Satchel (sneak-use to switch back to your personal vault), count as owners of each other's camp devices, and share a budget of twelve Wayanchors instead of thirty-two per dimension. A quarter of every member's tribe standing also lands on the camp, and an Elder trades at the camp's rank when it beats your own. Leave, kick, rename and info complete the command."))

# Rites / QoL (design 3.0 §4, §7)
CHAPTERS.append(("World rites", "Carve a Rite Tablet from two stone, a creature reagent and the matching seal; the seal is handed back. Sneak-use the tablet on a Ritual Brazier holding that seal. The brazier draws the rite's Pulse from the lattice within 8 blocks; if there is not enough, nothing is spent. Rain Calling (Water, 400) brings twenty minutes of rain. Sky Clearing (Air, 400) clears forty minutes. Dawn Calling (Fire, 800) hurries the night to sunrise unless the game rule tribalpower:allowDawnRite is off."))
CHAPTERS.append(("Land rites", "Green Blessing (Earth, 600) blesses the nine chunks around the brazier for twenty minutes: crops, saplings and stems there take extra random ticks and sparkle green. Still Night (Spirit, 600) hushes hostile spawning within 64 blocks for fifteen minutes, like a wide Hush Totem. Ley Binding (Loom, 1,200) ties the brazier's nearest Resonance Totem to another within 64 blocks for thirty minutes; a Conductor routes Pulse along the humming thread as if the totems stood side by side. Seal-carvers sell the Still Night tablet to Friends."))
CHAPTERS.append(("Ley Lens", "A glass pane, a Copper Resonator and a Spirit Shard make a lens for ley sight. Hold it in either hand: the HUD reads the ley strength where you stand and the ground around you glows in a 9-by-9 grid, blue where the land is quiet and gold where it sings. Open sky counts, night counts triple, rain, water and greenery each add. Sneak-use the lens on a Ley Collector to print that collector's exact factor breakdown."))
CHAPTERS.append(("Pulse logic", "The Pulse Gauge points its arrow at any Pulse holder and emits redstone 0 to 15 in proportion to its stored charge, refreshed every four ticks; a comparator reads the same number. The Pulse Threshold points the same way and emits a full signal only while the holder sits at or above 25, 50, 75 or 100 percent; use it empty-handed to cycle, and a comparator reads 1 to 4. Both craft from redstone, a Copper Resonator and March Stone; the gauge adds quartz, the threshold a redstone torch."))
CHAPTERS.append(("Codex diagnostics", "Sneak-use the Spirit Codex on any Tribal block to hear it explain itself: stored Pulse, every generator within 8 blocks with its output this second, the attunements present, the Pulse it could draw, and whether redstone pauses it. Workshops name their recipe and any missing voice or full output; relays report unloaded or locked endpoints; braziers list the rites their seal allows."))

# The Nine Tribes (design 3.0 §2)
CHAPTERS.append(("Standing", "Nine tribes kept the Loom, one Strand each; their camps still keep time. Offer a favoured item at a Tribe Hearth for +3 standing, the tribe's reagent for +8, any food for +1, or a charged Pulse Cell for +2 per 10 Pulse. Hostile kills within 24 blocks of a hearth give +1, twenty per day per tribe; a trade gives +2. Ranks: Guest 50, Friend 150, Kin 400, Voice 800. Hurting Kin costs 25 and turns the camp's Hunters on you for a minute; breaking a hearth costs 40. /tribalpower standing prints all nine."))
CHAPTERS.append(("Tribal Kin", "Every camp keeps four Kin: an Elder who trades from the tribe's table once you are a Guest, a Drummer whose beat feeds 2 Pulse into generators within 8 blocks, a Hunter who strikes hostiles within 12 blocks, and a Weaver at the loom. Kin wander within 16 blocks of their camp and never despawn. Elders unlock two offers per rank and, at Voice, press a Tribe Mark into your hand."))
CHAPTERS.append(("Kinship Totem", "Craft a Tribe Mark with the Resonance Totem of the tribe's voice and two Spiritweave. The Kinship Totem stores its tribe: it lends the tribe's voice to nearby stations and counts as an extra distinct voice for the Pulse Resonator, tracked per tribe rather than per element. Nine tribes beside six totems make fifteen voices."))
CHAPTERS.append(("Pad-keepers", "Strand of Soil, voice of Earth. Craft: hearths and caches. Camps stand in plains; a March camp keeps the old road. Favoured offerings: dirt, moss, bread and Echo Shards.\n\n\"We never called it dirt. We called it what was left, and we kept it warm.\""))
CHAPTERS.append(("Grit-singers", "Strand of Stone, voice of Earth. Craft: echo shatter and meshes. Camps stand in mountains; a March camp keeps the old road. Favoured offerings: raw ores, grits and Attuned Echo.\n\n\"The mesh does not find the ore. The mesh gives the ore somewhere to land.\""))
CHAPTERS.append(("Rootbinders", "Strand of Sprout, voice of Water. Craft: living anchors and March flora. Camps stand in forests; a March camp keeps the old road. Favoured offerings: saplings, seeds and Mossback Scale.\n\n\"Roots are the only rope the void respects.\""))
CHAPTERS.append(("Edge-walkers", "Strand of Claw, voice of Fire. Craft: Spiritgear and footholds. Camps stand in taiga; a March camp keeps the old road. Favoured offerings: leather, iron and Rift Tooth.\n\n\"Boots first. Then the bridge. Then the courage; it arrives on its own.\""))
CHAPTERS.append(("Drumhearts", "Strand of Spark, voice of Fire. Craft: drums and Pulse. Camps stand in savanna; a March camp keeps the old road. Favoured offerings: copper, charged Pulse Cells and Bone Chimes.\n\n\"The drum is not loud. The drum is steady. Be the drum.\""))
CHAPTERS.append(("Pattern-weavers", "Strand of Clock, voice of Air. Craft: timed songs and automation. Camps stand in birch woods; a March camp keeps the old road. Favoured offerings: redstone, clocks and Storm Wing.\n\n\"A factory is a song that has stopped needing the singer.\""))
CHAPTERS.append(("Colony-keepers", "Strand of Swarm, voice of Air. Craft: hives and March flowers. Camps stand in flower meadows; a March camp keeps the old road. Favoured offerings: honey, flowers and Lantern Down.\n\n\"You do not own a hive. You are on good terms with it.\""))
CHAPTERS.append(("Seal-carvers", "Strand of Sigil, voice of Spirit. Craft: seals and rites. Camps stand in dark forests; a March camp keeps the old road. Favoured offerings: blank or element seals and Spirit Shards.\n\n\"Spirit goes where it is asked politely and stays where it is fed.\""))
CHAPTERS.append(("Loom-stitchers", "Strand of Spindle, voice of Loom. Craft: gate-paths and the reweave. Camps stand in the March crystal fields only; a March camp keeps the old road. Favoured offerings: March Crystal, Loom Thread and compasses.\n\n\"The Loom was never one thread. It was nine agreeing.\""))

# The March remembers (design 3.0 §3): halls, the Drum Circle, The Unsung and the twelve Lore Tablets
CHAPTERS.append(("Ancestor Hall", "Sunken stone halls lie in the March steppe and highlands, three rooms under Loom-wood beams with a ladder shaft to the surface. Four Lore Tablets hang on the walls and two chests hold Loom Thread, echoes, Spiritweave and seals. Hollow Sentinels keep the side rooms. Read every tablet you find: the Codex records them."))
CHAPTERS.append(("Drum Circle", "Twelve lantern-topped pillars ring a Silent Drum in the March highlands. Strike the drum empty-handed or with a Bone Chime: four beats about a second apart (16 to 28 ticks) wake what waits beneath. A wrong beat thuds and resets. Each drum answers once per twenty minutes of real time, and never while its keeper is already awake."))
CHAPTERS.append(("The Unsung", "A hollow drum-spirit with two rune arms and a cracked mask. Beat (above two thirds health): a shockwave every 3 seconds hits everyone within 8 blocks for 6 and knocks back; sneak to brace for half damage and no knockback; its swipe deals 10. Chorus: every 8 seconds it calls two Echo Weavers, up to six, and beats faster. Silence (below one third): it goes invulnerable over the drum and casts slow weaving bolts. Strike the Silent Drum with the four-beat to resync it: stunned 8 seconds at double damage, then silence returns 12 seconds after the resync. Drops an Unsung Heart, 16 to 24 Loom Thread and 4 Resonant Cores. Leave for 30 seconds and it resets."))
CHAPTERS.append(("Crystal Spire", "A tapering spire of March Crystal in the crystal fields, with a Loom-stitcher waystation at its foot: a hearth, a banner, a Loom totem and one Elder of the Spindle tribe. It is the only camp the Loom-stitchers keep, and the place to trade for Loom Thread once you are their friend."))
CHAPTERS.append(("Tablet: Pad-keepers' Hearth", "We never called it dirt. We called it what was left, and we kept it warm. When the ground fell away we carried it in baskets, a pad at a time, and set a hearth on every pad we saved. Feed the hearth bread and moss. It remembers who fed it."))
CHAPTERS.append(("Tablet: Grit-singers' Mesh", "The mesh does not find the ore. The mesh gives the ore somewhere to land. Sing low over raw stone and it loosens; sing lower and it shatters into echo. Our meshes still hang in the halls, humming to nothing. Bring them ore and they will hum to you."))
CHAPTERS.append(("Tablet: Rootbinders' Rope", "Roots are the only rope the void respects. We planted the first anchors on the falling islands and bound them island to island, root to root. Half of them held. Plant a sapling in the March soil and you will feel it pull toward the others."))
CHAPTERS.append(("Tablet: Edge-walkers' Boots", "Boots first. Then the bridge. Then the courage; it arrives on its own. We walked the rift edge where the thread frayed thinnest and set footholds for the rest. A foothold is iron, leather and a promise not to look down."))
CHAPTERS.append(("Tablet: Drumhearts' Beat", "The drum is not loud. The drum is steady. Be the drum. One beat a breath apart, and the copper answers; miss a beat and it forgets you. Every engine in the March still keeps our time. Strike, wait, strike. That is the whole of it."))
CHAPTERS.append(("Tablet: Pattern-weavers' Song", "A factory is a song that has stopped needing the singer. We wrote the timings on clock-wheels and moth dust and let the Loom carry the tune. When the Cut came the songs kept playing. Some are playing still. Listen for the click before the hum."))
CHAPTERS.append(("Tablet: Colony-keepers' Hive", "You do not own a hive. You are on good terms with it. Offer honey, plant the March flowers, and the swarm will route Pulse through the comb for you. Take without asking and the comb goes quiet. It is very patient about this."))
CHAPTERS.append(("Tablet: Seal-carvers' Rite", "Spirit goes where it is asked politely and stays where it is fed. A seal is a polite request carved in stone. A brazier is the meal. We cut blank seals by the thousand before the Cut, and asked for far too much. Ask for a little. Feed it well."))
CHAPTERS.append(("Tablet: Loom-stitchers' Thread", "The Loom was never one thread. It was nine agreeing. We held the Spindle and stitched the tribes' strands into one cloth over the sky. When eight pulls became eight arguments, the cloth tore along our seam. We are still stitching. Bring crystal. Bring thread."))
CHAPTERS.append(("Tablet: The Cut", "No one struck the Loom. It was pulled from nine sides until one strand gave, and then the rest went like a rope through a hand. The continents fell in the space of a drum-roll. What did not fall drifted into the March and sank slow. Nine tribes, one hall, no one to blame."))
CHAPTERS.append(("Tablet: The Unsung", "A drum was carried out of every falling camp so the beat would not stop. The last drum was carried into the circle and no one was left to strike it. Its keeper went hollow waiting. Wake it with the four-beat and it will rise to be struck. Sneak when it beats. Resync it when it goes silent. It only wants the rhythm back."))
CHAPTERS.append(("Tablet: The March", "The March is where the thread frayed thinnest and the fallen ground came to rest. Halls lie sunk to the lintel; camps keep time with no one at the drum; crystal grows where the Loom's tension still pools. Walk it with a full Pulse cell and a steady hand. Everything here still answers a beat."))

# Walkthroughs (3.0): step-by-step teachings that end with what the reader now has and where to go next
CHAPTERS.append(("Walkthrough: your first camp", "1. Find a tribe camp: a hearth, a banner and four Kin in plains, mountains, forest, taiga, savanna, birch woods, flower meadows or dark forest. The banner colour names the tribe; the tribe pages list what each favours.\n2. Read the hearth. Sneak-use the Spirit Codex on it, or simply watch what the Kin carry: bread and moss for Pad-keepers, ores for Grit-singers, saplings for Rootbinders.\n3. Offer. Use a favoured item on the Tribe Hearth for +3 standing, or the tribe's reagent for +8. Any food gives +1 and a charged Pulse Cell gives +2 per 10 Pulse. Seventeen favoured offerings, or seven reagents, reach Guest at 50.\n4. Trade. Use the Elder once you are a Guest. Every trade gives +2, and each rank unlocks two more offers.\n5. Keep the peace. Never hit Kin (-25 standing and an angry Hunter for a minute) and never break the hearth (-40). Kills of hostiles within 24 blocks of the hearth earn +1, twenty times a day.\nWhat you now have: Guest standing with one tribe, its first trades, and a hearth that remembers you. /tribalpower standing prints all nine.\nNext: Friend at 150 opens the seal and tablet trades; Voice at 800 earns a Tribe Mark, the key to a Kinship Totem."))
CHAPTERS.append(("Walkthrough: the sixth voice", "1. Loot an Ancestor Hall. The sunken halls in the March steppe and highlands keep Loom Thread in their two chests; read the four tablets on the way out.\n2. Carve a Loom Seal: a Blank Seal, one Loom Thread and a Spirit Shard, shapeless. Seat it in a Ritual Brazier with Pulse nearby to thread 2 Pulse into your carried cells every two seconds.\n3. Build Echo Unweave: March Stone around a Copper Resonator, a Spirit Shard and two Loom Thread. It needs the Loom voice within 8 blocks, which for now only a Kinship Totem of the Loom-stitchers or a Loom-stitcher camp can lend.\n4. Wake The Unsung at a Drum Circle (see that walkthrough) and take its Unsung Heart.\n5. Craft the Loom totem: four March Crystal, two Loom Thread, two March Planks around the Unsung Heart. Place it within 8 blocks of the Unweave and of a Pulse Resonator.\nWhat you now have: the sixth voice. Unweave turns ingots back to echoes, cores to ingots, Spiritweave to wool and damaged Spiritgear into one Manifested Ingot; the Resonator counts one more distinct voice.\nNext: the Sixfold Staff's Loom voice (Tether and Stitch) and the Ley Binding rite, which needs the Loom seal."))
CHAPTERS.append(("Walkthrough: wake The Unsung", "1. Prepare: full Pulse cells, food, a Bone Chime, and a bound return route. Bring a friend if you can; the fight lasts a few minutes.\n2. Find a Drum Circle in the March highlands: twelve lantern pillars around a Silent Drum.\n3. Beat four times. Strike the drum empty-handed or with the chime, about one second apart (16 to 28 ticks). A wrong beat thuds and resets the count. The drum answers once per twenty minutes and never while its keeper is awake.\n4. Beat phase: every three seconds a shockwave hits everyone within 8 blocks for 6 and knocks back. Sneak just before it lands to brace: half damage, no knockback. Its swipe deals 10, so keep the drum between you.\n5. Chorus, below two thirds health: it calls two Echo Weavers every eight seconds, up to six, and beats faster. Clear the weavers before they slow you.\n6. Silence, below one third: it hovers invulnerable over the drum and casts slow weaving bolts. Walk to the drum and play the four-beat again to resync it: eight seconds stunned at double damage. Silence returns twelve seconds after each resync, so repeat.\nWhat you now have: an Unsung Heart, 16 to 24 Loom Thread and 4 Resonant Cores. Leaving for thirty seconds resets the fight.\nNext: the Loom totem (The sixth voice) and the Loom-stitcher trades at the Crystal Spire."))
CHAPTERS.append(("Walkthrough: your first rite", "1. Choose the rite. Rain Calling needs the Water seal and 400 Pulse; Sky Clearing the Air seal and 400. Dawn Calling (Fire, 800) and the land rites cost more. Start with rain.\n2. Carve the tablet: two stone, the rite's creature reagent (a Reed Fang for rain) and the matching seal, shapeless. The seal is handed back.\n3. Seat the seal. Use the Water Seal on a Ritual Brazier; the brazier's usual blessing still runs, and the seal stays reusable.\n4. Gather 400 Pulse within 8 blocks of the brazier: a charged Greater Pulse Cell in a Drumheart, a Resonator with a good catalyst, or several generators together. A Pulse Gauge or the Codex diagnostics show the total.\n5. Cast. Sneak-use the tablet on the brazier. If the lattice holds less than the cost nothing is spent; otherwise the tablet is consumed and the Pulse drawn.\nWhat you now have: twenty minutes of rain (or forty minutes of clear sky), stronger Ley Collectors, and a brazier that knows how to answer tablets.\nNext: Green Blessing over your farm (Earth, 600), Still Night around the camp (Spirit, 600), or Ley Binding between two distant totems (Loom, 1,200)."))
CHAPTERS.append(("Walkthrough: bond a familiar", "1. Craft a Bonding Charm: two Spiritweave, a Spirit Shard and one reagent of the animal you want (Lantern Down, Mossback Scale or Dawn Velvet). Brush an adult of that species to get the reagent.\n2. Find an adult Lantern Fox (forests, dusk), Mossback (swamps) or Dawn Stag (forests, dawn). Young animals cannot be bonded.\n3. Use the charm on it. Three tries in five succeed with hearts; a failed charm is kept, so try again.\n4. Follow and stay. The familiar follows within ten blocks and teleports to you past twelve. Sneak-use it (empty-handed for a Mossback) to make it wait, and again to follow. It never despawns and ignores your blows.\n5. Learn its trick. Fox: an invisible Spirit Light travels with it, Night Vision within eight blocks, and ore glints only you can see. Mossback: sneak-use with an empty hand for a nine-slot saddlebag. Stag: use it to ride without a saddle, steer with your gaze, hold jump to leap, sneak to dismount.\n6. Brush it. A bonded animal sheds double reagent, once a minute.\nWhat you now have: a companion that lights, carries or carries you, and a renewable reagent supply.\nNext: Rootbinders favour Mossback Scale and Colony-keepers Lantern Down, so a brushed familiar also buys standing."))
CHAPTERS.append(("Walkthrough: found a camp", "1. Found it: /tribalpower camp create <name>. You become its first member.\n2. Invite. Craft a Camp Charter (paper, Spiritweave, Spirit Shard) and use it on a player, or run /tribalpower camp invite <player>. Invitations last five minutes; the invitee accepts with /tribalpower camp join <name>.\n3. Share the vault. Open any Deep Cache or Wayfarer Satchel: sneak-use switches between your personal vault and the shared 54-slot camp vault.\n4. Share the devices. Members count as owners of each other's camp devices: cradles, tenders, anchors and locked menus open for all of you.\n5. Budget anchors. The camp shares twelve Wayanchors per dimension instead of thirty-two each, so agree on which chunks matter.\n6. Manage it: /tribalpower camp info, rename, kick and leave. A quarter of every member's tribe standing lands on the camp, and an Elder trades at the camp's rank when it beats your own.\nWhat you now have: a named camp with one vault, shared devices and pooled tribe standing.\nNext: the Shared camps teaching for the fine print, and Kinship Totems to lend your camp every tribe's voice."))


# The Listening Pit and the Gates (3.1): patterns, the two crafts, the six voices and the contract
CHAPTERS.append(("Placement is the ritual", "A device that claims to be a rite has to be arranged, not scattered. A pattern is a shape you build around one anchor block: the Stone Font and its chalk, the Listening Pit and its anchor stones, the Rite Circle around a brazier, the Voice Ring around a Resonator, the Shatter Array around an Echo station, and both gates. Any rotation works. Sneak-use the Spirit Codex on the anchor to be told the tier, the facing, and the first three things that are missing, with ghosts where they should go."))
CHAPTERS.append(("Ritual Mark", "Draw marks with Ritual Chalk on the top of any solid block. They are flat, walked over rather than around, and removed by breaking them; they drop nothing, because the chalk was spent when the mark was made. Chalk keeps its other job of linking totems. Marks are what join a pattern together."))
CHAPTERS.append(("Anchor Stone", "Four March Stone and an Echo Shard make four anchor stones. They brace the corners of a pattern and do nothing else: no Pulse, no inventory, no upkeep. A pattern that has them is a tier higher than one that does not."))
CHAPTERS.append(("Stone Font", "Stone is not made. Stone is asked to stay. Four stone, two Echo Shards and a Drumheart. Put a font down with four chalk marks around it and it asks for cobblestone every two seconds at 4 Pulse a second \\u2014 slow enough to run on a hand-drummed Drumheart, which is the point. Brace the corners with anchor stones and bring the Earth voice and it asks for stone at 8 Pulse a second. Add Fire and Water both and it asks for obsidian at 24. Below y 0 it gives the deepslate of each tier instead."))
CHAPTERS.append(("Listening Pit", "The mesh does not find the ore. The mesh gives the ore somewhere to land. Lay stone or deepslate, brace four corners with anchor stones, chalk from each edge to the middle, and set a Resonance Mesh at the centre with an Ancestral Cache beside it and the Earth voice within eight blocks. Feed substrate from the sides, seat a sample on top, take ore from the bottom \\u2014 or let the mesh empty itself into the cache, which is what the normal build does."))
CHAPTERS.append(("Deep Listening", "The seven by seven doubles the corner bracing, seats a totem at each cardinal edge, and wants a Tribe Hearth or a Grit-singer Kinship Totem standing inside the pattern. It is what opens the deep, hot and rare bands. The Grit-singers gate all of it by standing: Friend for the common band, Kin for the deep, Voice and their kinship for the rare."))
CHAPTERS.append(("What the ground offers", "The pit calls up exactly what a silk-touch mining trip would: the raw item for a metal, the ore block for a gem. Common is coal, copper and iron at 10 seconds and 14 Pulse a second on two stone. Deep is gold, redstone, lapis and quartz at 15 seconds and 18, on two March Stone. Hot is the Nether\\u2019s quartz and gold at 20 seconds and 36. Rare is diamond, emerald and whatever a modded pack added, at 40 seconds and 24, on four March Stone and a Spirit Shard, twice as much a quarter of the time."))
CHAPTERS.append(("Sample and substrate", "A sample is a filter, never an ingredient: it is not consumed, and a material it names weighs six times as much as anything else in the band. A sample the band does not hold is simply ignored, and the Codex says so. Substrates are all renewable on purpose \\u2014 stone from a Stone Font, March Stone from cobble \\u2014 so no tier is ever throttled behind a pickaxe. Per iron ingot the pit costs about 70 Pulse against 20 for shattering ore you mined. Mining stays efficient. The pit buys walking away."))
CHAPTERS.append(("Voices at the pit", "Each voice trades one thing for another; none of them is a plain multiplier. Earth is required. Water washes for 250 mB a cycle and gives one extra output every third cycle. Air quickens the cycle to about two thirds and charges half again as much a second, so the Pulse per item does not move and only throughput does. Fire opens the hot band at twice the Pulse. Spirit listens a band deeper and opens the rare one. The Loom halves the substrate, rounded up."))
CHAPTERS.append(("Way Gate", "Six March Stone, two copper and an Echo Shard make four Gate Frames; four frames, a Resonant Core, a Spirit Shard and a Pulse Cell make the keystone. Build a five by five ring without its corners and put the keystone at the bottom centre. Charge it from a Pulse Cell, then light it by hand or with a struck signal: 400 Pulse out of its own 600. Twenty Pulse carries anything that walks in \\u2014 players, mobs and dropped items alike, which is what makes a gate pair bulk logistics."))
CHAPTERS.append(("Far Gate", "A taller frame around a three by four interior, braced by four anchor stones at the corners of its footprint, with the Loom voice within eight blocks \\u2014 so crossing dimensions sits behind The Unsung. Link two of them with a Gate Sigil: a Blank Seal, a Loom Thread and a Spirit Shard. Sneak-use it on one keystone to write that gate down, then use it on the other to tie the pair both ways. Travel is 120 Pulse with a two-second breath afterwards."))
CHAPTERS.append(("Keeping the way", "Way Gates link locally: sneak-use a bound Waystone Compass on a keystone, or draw chalk from one keystone to the other within 64 blocks. A gate always lands you inside the far gate\\u2019s own interior and never terraforms; if there is nowhere to stand the trip refuses and the Pulse comes back. The far end is held loaded for ten seconds around your arrival, so an unloaded partner still answers. Break a keystone and its partner is released and anyone standing near it is told. /tribalpower gate list and /tribalpower gate unlink read and cut the threads."))
CHAPTERS.append(("Ember Horn", "The Drumhearts\\u2019 craft. Feed it any furnace fuel by hand, hopper or relay: burn time divided by twenty is Pulse, delivered at up to 20 a second. Coal is 80, a coal block 800, a lava bucket 1,000, a blaze rod 120. The rate is the real cap, so scaling means more horns \\u2014 and horns are a tribe craft. Nothing you can automate turns fuel into more fuel than it burns."))
CHAPTERS.append(("Wind Harp", "The Pattern-weavers\\u2019 craft, and free, so it is capped instead. One Pulse a second as a base and one more under open sky; one more above y 128 and two above y 192; one more in rain or two in a storm. Six a second is the whole of the wind. Harps within twelve blocks divide it between them, so a wall of harps is a wall of decorations. Under a roof it makes nothing at all."))
CHAPTERS.append(("Wave Drum", "The Rootbinders\\u2019 craft, and the second job for fluid transport. Three a second standing beside water, shared with any drum within eight blocks. Give it its own water instead \\u2014 a bucket, a cistern, a fluid relay \\u2014 and it makes ten a second for 100 mB a second, which nothing crowds out because the water is already the limit. Rain doubles either tier."))
CHAPTERS.append(("Wake Bell", "The Seal-carvers\\u2019 craft, and what turns a mob farm into a power plant. Twenty Pulse for a hostile death within sixteen blocks and five for a passive one, gathered into a reservoir of 2,000 that lets out at most eight a second. A big farm fills the reservoir and then idles rather than scaling to absurdity. Only the nearest bell hears a death, so stacking bells buys nothing."))
CHAPTERS.append(("Loom Anchor", "The Loom-stitchers\\u2019 craft, and the one that pays for completeness. One Pulse a second per distinct voice within eight blocks, to a maximum of six, doubled while a Ley Binding is live nearby. It generates from the system itself, so it needs no cap of its own: there are only six voices."))
CHAPTERS.append(("Pulse Cairn", "Six March Stone, two Bound Echoes and a Pulse Cell. Each cairn holds 4,000 Pulse and draws surplus out of nearby generators; stack up to five in a column and the sixth stone is just a stone. A comparator reads how full it is. A cairn is what turns a Wake Bell\\u2019s bursts into the steady draw a Listening Pit wants."))
CHAPTERS.append(("Spring Calling", "Rain Calling\\u2019s small sibling: two stone, a Spirit Reed and the Water Seal, and the seal comes back. Three hundred Pulse at a brazier with a Spirit Cistern beside it marks that cistern a spring, and it refills 100 mB a second for ten minutes. Cheap and repeatable, and it is where the water for a Wave Drum, for Washing and for anything else that drinks comes from. March-side lava stays a manual haul: the Ember Horn\\u2019s best fuel should cost a trip."))
CHAPTERS.append(("Draw the circle", "A brazier\\u2019s blessing still needs nothing but a seated seal. A tablet rite now wants its circle: the brazier in the middle, four Rite Pedestals on the diagonals, and chalk joining them. Seat four totems of the rite\\u2019s own voice on the cardinals and it costs a quarter less and lasts twice as long. This is the one deliberate change to something that already worked, and the failure message says so."))
CHAPTERS.append(("A rite on a clock", "A Rite Pedestal now holds and shows one item, and a comparator reads whether it is occupied. That is the whole of what an automatic rite loop needs: a relay restocks a pedestal with a tablet, a clock strikes the brazier, the rite fires and spends the tablet, and the comparator reports the pedestal empty. No fake players, no hidden inventories \\u2014 everything a player can do by hand, a base can do on a clock."))
CHAPTERS.append(("Metals and gems", "Grit means one thing now: crushed metal waiting for the fire. A metal is raw item or silk-touched ore to grit, then grit to ingot in a furnace or blast furnace. A gem or mineral skips the fire entirely \\u2014 silk-touched ore shatters straight into the gem at twice the ore\\u2019s own drop, so coal, diamond, emerald and quartz give two and redstone and lapis give eight. The gem itself is never an input. Modded metals ride one Mineral Grit item that names its own material, and light up with no datapack."))
CHAPTERS.append(("Voice Ring", "A Pulse Resonator surrounded by totems standing at radius three, on its own level, counts every voice among them. Totems merely near it still work exactly as they did, but a heap counts at most five voices: six-voice resonance only counts when the voices are actually arranged."))
CHAPTERS.append(("Shatter Array", "Centre an Echo station in a five by five with four totems of the recipe\\u2019s own attunement at the corners and an Ancestral Cache beneath. The station then costs a quarter less Pulse and empties itself into the cache. Entirely optional, and every station works exactly as before without it."))

def main():
    roster=json.loads((ROOT/'art/creatures/roster.json').read_text(encoding='utf-8'))
    chapters=CHAPTERS+[(r['name'],r['notes']) for r in roster]
    pages = [title.upper() + '\n\n' + body for title, body in chapters]
    source = 'package tk.darrow.tribalpower.guide;\n\nimport java.util.List;\n\n/** Generated by tools/generate_guide.py. */\npublic final class GuidePages {\n    private GuidePages() {}\n    public static List<String> allPages() {\n        return List.of(\n'
    source += ',\n'.join('            ' + json.dumps(page, ensure_ascii=True) for page in pages)
    source += '\n        );\n    }\n}\n'
    (ROOT/'src/main/java/tk/darrow/tribalpower/guide/GuidePages.java').write_text(source, encoding='utf-8')
    data = {'book':'Spirit Codex', 'chapters':[{'id':f'chapter_{i+1}', 'title':title, 'text':body} for i,(title,body) in enumerate(chapters)]}
    (ROOT/'src/main/resources/data/tribalpower/guide/spirit_codex.json').write_text(json.dumps(data,indent=2)+'\n', encoding='utf-8')
    print(f'Generated {len(pages)} guide pages.')

if __name__ == '__main__': main()
